-- Task 3.1: username/password authentication and the four owner-approved
-- initial account identities. Passwords are deliberately absent: the owner
-- initializes each one through the interactive local command after review.

ALTER TABLE public.people
  ADD COLUMN is_application_native boolean NOT NULL DEFAULT false;

CREATE TABLE public.user_accounts (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  person_id integer NOT NULL,
  username text NOT NULL,
  username_normalized text NOT NULL,
  password_hash text,
  role_code text NOT NULL,
  is_enabled boolean NOT NULL DEFAULT true,
  must_change_password boolean NOT NULL DEFAULT true,
  failed_login_attempts integer NOT NULL DEFAULT 0,
  locked_until timestamptz(6),
  session_version integer NOT NULL DEFAULT 0,
  password_changed_at timestamptz(6),
  last_login_at timestamptz(6),
  created_at timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by integer,
  updated_at timestamptz(6) NOT NULL,
  updated_by integer,
  CONSTRAINT user_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT user_accounts_person_id_key UNIQUE (person_id),
  CONSTRAINT user_accounts_username_normalized_key UNIQUE (username_normalized),
  CONSTRAINT user_accounts_person_id_fkey
    FOREIGN KEY (person_id) REFERENCES public.people(id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT user_accounts_username_display_shape CHECK (
    username = btrim(username)
    AND username ~ '^[A-Za-z][A-Za-z0-9._-]{2,63}$'::text
  ),
  CONSTRAINT user_accounts_username_normalized_shape CHECK (
    username_normalized = lower(username)
    AND username_normalized ~ '^[a-z][a-z0-9._-]{2,63}$'::text
  ),
  CONSTRAINT user_accounts_role_code_shape CHECK (
    role_code = ANY (ARRAY[
      'Administrator'::text,
      'Litigation Assistant'::text,
      'Lawyer'::text,
      'Paralegal'::text
    ])
  ),
  CONSTRAINT user_accounts_lockout_shape CHECK (
    failed_login_attempts BETWEEN 0 AND 5
    AND (
      (failed_login_attempts < 5 AND locked_until IS NULL)
      OR (failed_login_attempts = 5 AND locked_until IS NOT NULL)
    )
  ),
  CONSTRAINT user_accounts_session_version_shape CHECK (session_version >= 0),
  CONSTRAINT user_accounts_password_state_shape CHECK (
    (
      password_hash IS NULL
      AND must_change_password
      AND password_changed_at IS NULL
      AND failed_login_attempts = 0
      AND locked_until IS NULL
    )
    OR (
      password_hash ~ '^\$argon2id\$v=19\$m=19456,p=1,t=2\$[A-Za-z0-9+/]+={0,2}\$[A-Za-z0-9+/]+={0,2}$'::text
      AND password_changed_at IS NOT NULL
    )
  )
);

CREATE FUNCTION public.guard_user_account_security()
RETURNS trigger
LANGUAGE plpgsql
VOLATILE
SECURITY INVOKER
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF NEW.person_id <> OLD.person_id THEN
    RAISE EXCEPTION 'A user account cannot be moved to another person';
  END IF;
  IF NEW.session_version < OLD.session_version THEN
    RAISE EXCEPTION 'A user account session version cannot decrease';
  END IF;
  IF OLD.password_hash IS NOT NULL AND NEW.password_hash IS NULL THEN
    RAISE EXCEPTION 'An initialized user password cannot be cleared';
  END IF;
  IF NEW.password_hash IS DISTINCT FROM OLD.password_hash
     OR (OLD.is_enabled AND NOT NEW.is_enabled) THEN
    IF NEW.session_version <= OLD.session_version THEN
      RAISE EXCEPTION 'Password changes and account disabling must invalidate sessions';
    END IF;
    IF NEW.failed_login_attempts <> 0 OR NEW.locked_until IS NOT NULL THEN
      RAISE EXCEPTION 'Password changes and account disabling must clear lockout state';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER user_accounts_security_guard
BEFORE UPDATE OF person_id, password_hash, is_enabled, failed_login_attempts,
  locked_until, session_version ON public.user_accounts
FOR EACH ROW EXECUTE FUNCTION public.guard_user_account_security();

CREATE FUNCTION public.enforce_person_login_eligibility()
RETURNS trigger
LANGUAGE plpgsql
VOLATILE
SECURITY INVOKER
SET search_path = pg_catalog, public
AS $$
BEGIN
  NEW.can_login := NEW.is_active AND EXISTS (
    SELECT 1 FROM public.user_accounts a
     WHERE a.person_id = NEW.id AND a.is_enabled
  );
  RETURN NEW;
END;
$$;

CREATE TRIGGER people_login_eligibility_guard
BEFORE INSERT OR UPDATE OF is_active, can_login ON public.people
FOR EACH ROW EXECUTE FUNCTION public.enforce_person_login_eligibility();

CREATE FUNCTION public.sync_user_account_person_login()
RETURNS trigger
LANGUAGE plpgsql
VOLATILE
SECURITY INVOKER
SET search_path = pg_catalog, public
AS $$
DECLARE
  affected_person_id integer;
BEGIN
  affected_person_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.person_id ELSE NEW.person_id END;
  UPDATE public.people
     SET can_login = is_active AND EXISTS (
           SELECT 1 FROM public.user_accounts a
            WHERE a.person_id = affected_person_id AND a.is_enabled
         ),
         updated_at = CURRENT_TIMESTAMP
   WHERE id = affected_person_id;
  RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$$;

CREATE TRIGGER user_accounts_sync_person_login
AFTER INSERT OR DELETE OR UPDATE OF is_enabled ON public.user_accounts
FOR EACH ROW EXECUTE FUNCTION public.sync_user_account_person_login();

-- Identity preconditions. Rule 15 applies: existing people resolve through
-- person_name_alias, even when the canonical name is known.
DO $$
DECLARE
  ihab_id integer;
  samy_id integer;
BEGIN
  SELECT min(person_id) INTO ihab_id
    FROM public.person_name_alias WHERE alias_ar = 'إيهاب حمدي'
   HAVING count(*) = 1;
  IF ihab_id IS DISTINCT FROM 4 THEN
    RAISE EXCEPTION 'Ihab Hamdy must resolve once through alias to person 4';
  END IF;

  SELECT min(person_id) INTO samy_id
    FROM public.person_name_alias WHERE alias_ar = 'سامي إبراهيم خطاب'
   HAVING count(*) = 1;
  IF samy_id IS NULL OR
     (SELECT name_ar FROM public.people WHERE id = samy_id) <> 'سامي إبراهيم خطاب' THEN
    RAISE EXCEPTION 'Samy Khattab exact self-alias must resolve once to the canonical person';
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.people
     WHERE ar_normalise(name_ar) IN (ar_normalise('خالد حلمي'), ar_normalise('محمد حسين'))
        OR lower(btrim(coalesce(name_en, ''))) IN ('khaled helmy', 'mohamed hussien')
        OR lower(btrim(coalesce(email, ''))) IN (
          'khelmy@sarieldin.com', 'mhussien@sarieldin.com',
          'ihamdy@sarieldin.com', 'skhattab@sarieldin.com'
        )
  ) OR EXISTS (
    SELECT 1 FROM public.person_name_alias
     WHERE ar_normalise(alias_ar) IN (ar_normalise('خالد حلمي'), ar_normalise('محمد حسين'))
  ) THEN
    RAISE EXCEPTION 'A Task 3.1 native identity or approved email already exists';
  END IF;
END;
$$;

INSERT INTO public.people (
  name_ar, name_en, email, is_staff, is_active, is_trainee, can_login,
  is_application_native, updated_at
) VALUES
  ('خالد حلمي', 'Khaled Helmy', 'khelmy@sarieldin.com', true, true, false, false, true, CURRENT_TIMESTAMP),
  ('محمد حسين', 'Mohamed Hussien', 'mhussien@sarieldin.com', true, true, false, false, true, CURRENT_TIMESTAMP);

INSERT INTO public.person_name_alias (person_id, alias_ar, is_primary)
SELECT id, name_ar, true FROM public.people
 WHERE name_ar IN ('خالد حلمي', 'محمد حسين')
 ORDER BY name_ar;

UPDATE public.people p
   SET email = approved.email,
       updated_at = CURRENT_TIMESTAMP
  FROM (VALUES
    ('إيهاب حمدي'::text, 'ihamdy@sarieldin.com'::text),
    ('سامي إبراهيم خطاب'::text, 'skhattab@sarieldin.com'::text)
  ) AS approved(alias_ar, email)
  JOIN public.person_name_alias a ON a.alias_ar = approved.alias_ar
 WHERE p.id = a.person_id;

INSERT INTO public.user_accounts (
  person_id, username, username_normalized, role_code, updated_at
)
SELECT a.person_id, approved.username, lower(approved.username), approved.role_code,
       CURRENT_TIMESTAMP
  FROM (VALUES
    ('خالد حلمي'::text, 'KHelmy'::text, 'Administrator'::text),
    ('محمد حسين'::text, 'MHussien'::text, 'Litigation Assistant'::text),
    ('إيهاب حمدي'::text, 'IHamdy'::text, 'Lawyer'::text),
    ('سامي إبراهيم خطاب'::text, 'SKhattab'::text, 'Paralegal'::text)
  ) AS approved(alias_ar, username, role_code)
  JOIN public.person_name_alias a ON a.alias_ar = approved.alias_ar;

DO $$
DECLARE
  problems integer;
BEGIN
  SELECT count(*) INTO problems FROM (
    VALUES
      ('KHelmy'::text, 'خالد حلمي'::text, 'khelmy@sarieldin.com'::text, 'Administrator'::text, true),
      ('MHussien'::text, 'محمد حسين'::text, 'mhussien@sarieldin.com'::text, 'Litigation Assistant'::text, true),
      ('IHamdy'::text, 'إيهاب حمدي'::text, 'ihamdy@sarieldin.com'::text, 'Lawyer'::text, false),
      ('SKhattab'::text, 'سامي إبراهيم خطاب'::text, 'skhattab@sarieldin.com'::text, 'Paralegal'::text, false)
  ) expected(username, name_ar, email, role_code, native)
  LEFT JOIN public.user_accounts u ON u.username = expected.username
  LEFT JOIN public.people p ON p.id = u.person_id
  WHERE u.id IS NULL
     OR p.name_ar IS DISTINCT FROM expected.name_ar
     OR p.email IS DISTINCT FROM expected.email
     OR u.role_code IS DISTINCT FROM expected.role_code
     OR p.is_application_native IS DISTINCT FROM expected.native
     OR p.can_login IS NOT TRUE
     OR u.password_hash IS NOT NULL;

  IF problems <> 0 OR (SELECT count(*) FROM public.user_accounts) <> 4 THEN
    RAISE EXCEPTION 'Task 3.1 account mapping postcondition failed';
  END IF;
  IF (SELECT count(*) FROM public.people WHERE NOT is_application_native) <> 135
     OR (SELECT count(*) FROM public.people WHERE is_application_native) <> 2
     OR (SELECT count(*) FROM public.person_name_alias) <> 350 THEN
    RAISE EXCEPTION 'Task 3.1 protected/native roster postcondition failed';
  END IF;
END;
$$;
