import { defineConfig, globalIgnores } from 'eslint/config';
import nextVitals from 'eslint-config-next/core-web-vitals';
import nextTs from 'eslint-config-next/typescript';
import prettier from 'eslint-config-prettier';

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,

  // Must come last: switches off every rule that only argues about
  // formatting, so ESLint and Prettier never disagree.
  prettier,

  globalIgnores([
    '.next/**',
    'out/**',
    'build/**',
    'coverage/**',
    'next-env.d.ts',
    // Generated by Prisma from prisma/schema.prisma. Not ours to lint.
    'src/generated/**',
  ]),
]);

export default eslintConfig;
