BEGIN;

-- Task 2.9D: fee-letter parents, both deliberately separate matter-link
-- directions, source identity and immutable evidence.
ALTER TABLE public.fee_letters
    ADD COLUMN legacy_mfiles_id_raw text,
    ADD COLUMN legacy_source_record_key text,
    ADD COLUMN legacy_source_extraction_sha256 text,
    ADD COLUMN legacy_source_payload jsonb,
    ADD CONSTRAINT fee_letters_source_identity_shape CHECK (
        (legacy_source_record_key IS NULL
         AND legacy_source_extraction_sha256 IS NULL
         AND legacy_source_payload IS NULL
         AND legacy_mfiles_id_raw IS NULL)
        OR
        (legacy_source_record_key ~ '^[0-9a-f]{64}:[0-9]{6}$'
         AND legacy_source_extraction_sha256 ~ '^[0-9A-F]{64}$'
         AND jsonb_typeof(legacy_source_payload)='object'
         AND contract_id IS NOT NULL
         AND mfiles_id IS NOT DISTINCT FROM legacy_mfiles_id_raw)
    );
CREATE UNIQUE INDEX fee_letters_legacy_source_record_key_key
    ON public.fee_letters(legacy_source_record_key);

ALTER TABLE public.fee_letter_matters
    ADD COLUMN legacy_parent_contract_id_raw text,
    ADD COLUMN legacy_source_record_key text,
    ADD COLUMN legacy_source_extraction_sha256 text,
    ADD COLUMN legacy_source_payload jsonb,
    ADD CONSTRAINT fee_letter_matters_source_identity_shape CHECK (
        (legacy_source_record_key IS NULL
         AND legacy_source_extraction_sha256 IS NULL
         AND legacy_source_payload IS NULL
         AND legacy_parent_contract_id_raw IS NULL)
        OR
        (legacy_source_record_key ~ '^[0-9a-f]{64}:[0-9]{6}$'
         AND legacy_source_extraction_sha256 ~ '^[0-9A-F]{64}$'
         AND jsonb_typeof(legacy_source_payload)='object'
         AND legacy_parent_contract_id_raw IS NOT NULL
         AND legacy_matter_ref IS NOT NULL
         AND ordinal IS NOT NULL)
    );
CREATE UNIQUE INDEX fee_letter_matters_legacy_source_record_key_key
    ON public.fee_letter_matters(legacy_source_record_key);

CREATE TABLE public.matter_fee_letter_references(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matter_id integer NOT NULL UNIQUE,
    fee_letter_id integer NOT NULL,
    identifier_space text NOT NULL,
    legacy_reference_raw text NOT NULL,
    legacy_source_record_key text NOT NULL UNIQUE,
    legacy_source_extraction_sha256 text NOT NULL,
    legacy_source_payload jsonb NOT NULL,
    created_at timestamptz(6) NOT NULL DEFAULT current_timestamp,
    created_by integer,
    updated_at timestamptz(6) NOT NULL DEFAULT current_timestamp,
    updated_by integer,
    CONSTRAINT matter_fee_letter_references_identity_shape CHECK (
        identifier_space IN ('contract_id','mfiles_id')
        AND legacy_source_record_key ~ '^[0-9a-f]{64}:[0-9]{6}$'
        AND legacy_source_extraction_sha256 ~ '^[0-9A-F]{64}$'
        AND jsonb_typeof(legacy_source_payload)='object'),
    CONSTRAINT matter_fee_letter_references_matter_fk FOREIGN KEY(matter_id)
        REFERENCES public.matters(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT matter_fee_letter_references_fee_fk FOREIGN KEY(fee_letter_id)
        REFERENCES public.fee_letters(id) ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE INDEX matter_fee_letter_references_fee_letter_id_idx
    ON public.matter_fee_letter_references(fee_letter_id);

CREATE TABLE quarantine.fee_letter_transform(
    src_record_key text PRIMARY KEY,extraction_sha256 text NOT NULL,src_file text NOT NULL,
    src_row_num integer NOT NULL,contract_id_raw text,reason_codes text[] NOT NULL,
    reason_details jsonb NOT NULL,source_payload jsonb NOT NULL,
    created_at timestamptz(6) NOT NULL DEFAULT current_timestamp,
    CONSTRAINT fee_letter_transform_identity_shape CHECK(src_record_key~'^[0-9a-f]{64}:[0-9]{6}$' AND extraction_sha256~'^[0-9A-F]{64}$'),
    CONSTRAINT fee_letter_transform_reason_shape CHECK(cardinality(reason_codes)>0 AND jsonb_typeof(reason_details)='array' AND jsonb_array_length(reason_details)=cardinality(reason_codes) AND jsonb_typeof(source_payload)='object')
);
CREATE TABLE quarantine.fee_letter_matter_transform(
    src_record_key text PRIMARY KEY,extraction_sha256 text NOT NULL,src_file text NOT NULL,
    src_row_num integer NOT NULL,parent_contract_id_raw text,ordinal_raw text,matter_ref_raw text,
    reason_codes text[] NOT NULL,reason_details jsonb NOT NULL,source_payload jsonb NOT NULL,
    created_at timestamptz(6) NOT NULL DEFAULT current_timestamp,
    CONSTRAINT fee_letter_matter_transform_identity_shape CHECK(src_record_key~'^[0-9a-f]{64}:[0-9]{6}$' AND extraction_sha256~'^[0-9A-F]{64}$'),
    CONSTRAINT fee_letter_matter_transform_reason_shape CHECK(cardinality(reason_codes)>0 AND jsonb_typeof(reason_details)='array' AND jsonb_array_length(reason_details)=cardinality(reason_codes) AND jsonb_typeof(source_payload)='object')
);
CREATE TABLE quarantine.matter_fee_letter_reference(
    src_record_key text PRIMARY KEY,extraction_sha256 text NOT NULL,src_file text NOT NULL,
    src_row_num integer NOT NULL,legacy_matter_id text,reference_raw text NOT NULL,
    identifier_space text NOT NULL,resolved_fee_letter_source_key text NOT NULL,
    reason_codes text[] NOT NULL,reason_details jsonb NOT NULL,source_payload jsonb NOT NULL,
    created_at timestamptz(6) NOT NULL DEFAULT current_timestamp,
    CONSTRAINT matter_fee_letter_reference_identity_shape CHECK(src_record_key~'^[0-9a-f]{64}:[0-9]{6}$' AND extraction_sha256~'^[0-9A-F]{64}$' AND identifier_space IN('contract_id','mfiles_id') AND resolved_fee_letter_source_key~'^[0-9a-f]{64}:[0-9]{6}$'),
    CONSTRAINT matter_fee_letter_reference_reason_shape CHECK(cardinality(reason_codes)>0 AND jsonb_typeof(reason_details)='array' AND jsonb_array_length(reason_details)=cardinality(reason_codes) AND jsonb_typeof(source_payload)='object')
);

CREATE OR REPLACE FUNCTION quarantine.refuse_fee_letter_evidence_change()RETURNS trigger
LANGUAGE plpgsql VOLATILE CALLED ON NULL INPUT SECURITY INVOKER PARALLEL UNSAFE
AS $FEE_EVIDENCE$
BEGIN
 IF TG_OP='UPDATE' THEN RAISE EXCEPTION 'Task 2.9D immutable migration evidence cannot be updated'; END IF;
 RAISE EXCEPTION 'Task 2.9D migration evidence DELETE/TRUNCATE is refused';
END;
$FEE_EVIDENCE$;
CREATE TRIGGER fee_letter_transform_no_change BEFORE UPDATE OR DELETE ON quarantine.fee_letter_transform FOR EACH ROW EXECUTE FUNCTION quarantine.refuse_fee_letter_evidence_change();
CREATE TRIGGER fee_letter_transform_no_truncate BEFORE TRUNCATE ON quarantine.fee_letter_transform FOR EACH STATEMENT EXECUTE FUNCTION quarantine.refuse_fee_letter_evidence_change();
CREATE TRIGGER fee_letter_matter_transform_no_change BEFORE UPDATE OR DELETE ON quarantine.fee_letter_matter_transform FOR EACH ROW EXECUTE FUNCTION quarantine.refuse_fee_letter_evidence_change();
CREATE TRIGGER fee_letter_matter_transform_no_truncate BEFORE TRUNCATE ON quarantine.fee_letter_matter_transform FOR EACH STATEMENT EXECUTE FUNCTION quarantine.refuse_fee_letter_evidence_change();
CREATE TRIGGER matter_fee_letter_reference_no_change BEFORE UPDATE OR DELETE ON quarantine.matter_fee_letter_reference FOR EACH ROW EXECUTE FUNCTION quarantine.refuse_fee_letter_evidence_change();
CREATE TRIGGER matter_fee_letter_reference_no_truncate BEFORE TRUNCATE ON quarantine.matter_fee_letter_reference FOR EACH STATEMENT EXECUTE FUNCTION quarantine.refuse_fee_letter_evidence_change();

COMMIT;
