BEGIN;

-- Task 2.9B: durable POA provenance, reviewed lawyer rows and immutable
-- relationship evidence. The data transform is a separate serializable run.
ALTER TABLE public.migration_multi_person_rule
    ADD COLUMN poa_match_mode text,
    ADD CONSTRAINT migration_multi_person_rule_poa_match_mode_check
        CHECK (poa_match_mode IS NULL OR poa_match_mode = 'substring');

UPDATE public.migration_multi_person_rule
   SET poa_match_mode = 'substring'
 WHERE raw_value IN (
    'خالد محمود حمدي عبد العزيز وأحمد عبد الله محمد ومحمد عبد العزيز عبد الحافظ وشريف أبو المكارم صالح وأحمد سعيد أحمد ومحمد مجدي أحمد الغرابلي',
    'خالد محمود حمدي عبد العزيز وأحمد عبد الله محمد ومحمد عبد العزيز عبد الحافظ وأحمد سعيد أحمد ومحمد مجدي أحمد الغرابلي',
    'هاني سري الدين - أميرة شريف - إيهاب حمدي - محمد عبد العزيز - أحمد سعيد - محمد حمدي - هاني الدالي - عبد الرحمن البنا'
 );

DO $ASSERT$
BEGIN
    IF (SELECT count(*) FROM public.migration_multi_person_rule WHERE poa_match_mode='substring') <> 3 THEN
        RAISE EXCEPTION 'Task 2.9B expected exactly three approved POA substring rules';
    END IF;
END;
$ASSERT$;

ALTER TABLE public.powers_of_attorney
    RENAME COLUMN inventory TO show_on_poa_report;

ALTER TABLE public.powers_of_attorney
    ADD COLUMN legacy_source_record_key text,
    ADD COLUMN legacy_source_extraction_sha256 text,
    ADD COLUMN legacy_source_payload jsonb,
    ADD CONSTRAINT powers_of_attorney_source_identity_shape CHECK (
        (legacy_source_record_key IS NULL
         AND legacy_source_extraction_sha256 IS NULL
         AND legacy_source_payload IS NULL)
        OR
        (legacy_source_record_key ~ '^[0-9a-f]{64}:[0-9]{6}$'
         AND legacy_source_extraction_sha256 ~ '^[0-9A-F]{64}$'
         AND jsonb_typeof(legacy_source_payload) = 'object')
    );

CREATE UNIQUE INDEX powers_of_attorney_legacy_source_record_key_key
    ON public.powers_of_attorney (legacy_source_record_key);

CREATE TABLE public.power_of_attorney_lawyers (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    power_of_attorney_id integer NOT NULL,
    person_id integer NOT NULL,
    legacy_source_record_key text,
    legacy_source_extraction_sha256 text,
    legacy_lawyers_raw text,
    reviewed_rule_id integer,
    source_member_ordinal integer,
    created_at timestamptz(6) NOT NULL DEFAULT current_timestamp,
    created_by integer,
    updated_at timestamptz(6) NOT NULL DEFAULT current_timestamp,
    updated_by integer,
    CONSTRAINT power_of_attorney_lawyers_source_shape CHECK (
        (legacy_source_record_key IS NULL
         AND legacy_source_extraction_sha256 IS NULL
         AND legacy_lawyers_raw IS NULL
         AND reviewed_rule_id IS NULL
         AND source_member_ordinal IS NULL)
        OR
        (legacy_source_record_key ~ '^[0-9a-f]{64}:[0-9]{6}$'
         AND legacy_source_extraction_sha256 ~ '^[0-9A-F]{64}$'
         AND legacy_lawyers_raw IS NOT NULL
         AND source_member_ordinal > 0)
    ),
    CONSTRAINT power_of_attorney_lawyers_poa_fk FOREIGN KEY (power_of_attorney_id)
        REFERENCES public.powers_of_attorney(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT power_of_attorney_lawyers_person_fk FOREIGN KEY (person_id)
        REFERENCES public.people(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT power_of_attorney_lawyers_rule_fk FOREIGN KEY (reviewed_rule_id)
        REFERENCES public.migration_multi_person_rule(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE UNIQUE INDEX power_of_attorney_lawyers_poa_person_key
    ON public.power_of_attorney_lawyers (power_of_attorney_id, person_id);
CREATE UNIQUE INDEX power_of_attorney_lawyers_source_rule_ordinal_key
    ON public.power_of_attorney_lawyers
       (legacy_source_record_key, reviewed_rule_id, source_member_ordinal);
CREATE INDEX power_of_attorney_lawyers_person_id_idx
    ON public.power_of_attorney_lawyers (person_id);
CREATE INDEX power_of_attorney_lawyers_reviewed_rule_id_idx
    ON public.power_of_attorney_lawyers (reviewed_rule_id);

CREATE SCHEMA IF NOT EXISTS quarantine;

CREATE TABLE quarantine.power_of_attorney_transform (
    src_record_key text PRIMARY KEY,
    extraction_sha256 text NOT NULL,
    src_file text NOT NULL,
    src_row_num integer NOT NULL,
    reason_codes text[] NOT NULL,
    reason_details jsonb NOT NULL,
    source_payload jsonb NOT NULL,
    created_at timestamptz(6) NOT NULL DEFAULT current_timestamp,
    CONSTRAINT power_of_attorney_transform_identity_shape CHECK (
        src_record_key ~ '^[0-9a-f]{64}:[0-9]{6}$'
        AND extraction_sha256 ~ '^[0-9A-F]{64}$'),
    CONSTRAINT power_of_attorney_transform_reason_shape CHECK (
        cardinality(reason_codes) > 0
        AND jsonb_typeof(reason_details) = 'array'
        AND jsonb_array_length(reason_details) = cardinality(reason_codes)
        AND jsonb_typeof(source_payload) = 'object')
);

CREATE TABLE quarantine.power_of_attorney_relationship (
    src_record_key text NOT NULL,
    relationship_kind text NOT NULL,
    extraction_sha256 text NOT NULL,
    src_file text NOT NULL,
    src_row_num integer NOT NULL,
    raw_value text,
    reviewed_rule_ids integer[] NOT NULL DEFAULT '{}',
    resolved_member_count integer NOT NULL DEFAULT 0,
    reason_codes text[] NOT NULL,
    reason_details jsonb NOT NULL,
    source_payload jsonb NOT NULL,
    created_at timestamptz(6) NOT NULL DEFAULT current_timestamp,
    PRIMARY KEY (src_record_key, relationship_kind),
    CONSTRAINT power_of_attorney_relationship_identity_shape CHECK (
        src_record_key ~ '^[0-9a-f]{64}:[0-9]{6}$'
        AND extraction_sha256 ~ '^[0-9A-F]{64}$'
        AND relationship_kind IN ('client', 'lawyers')),
    CONSTRAINT power_of_attorney_relationship_reason_shape CHECK (
        cardinality(reason_codes) > 0
        AND resolved_member_count >= 0
        AND jsonb_typeof(reason_details) = 'array'
        AND jsonb_array_length(reason_details) = cardinality(reason_codes)
        AND jsonb_typeof(source_payload) = 'object')
);

CREATE OR REPLACE FUNCTION public.enforce_poa_lawyer_provenance()
RETURNS trigger
LANGUAGE plpgsql
VOLATILE
CALLED ON NULL INPUT
SECURITY INVOKER
PARALLEL UNSAFE
AS $POA_MEMBER$
DECLARE
    parent_source record;
BEGIN
    IF NEW.legacy_source_record_key IS NULL THEN
        RETURN NEW;
    END IF;

    SELECT legacy_source_record_key, legacy_source_extraction_sha256, legacy_lawyers_raw
      INTO parent_source
      FROM public.powers_of_attorney
     WHERE id = NEW.power_of_attorney_id;
    IF parent_source.legacy_source_record_key IS DISTINCT FROM NEW.legacy_source_record_key
       OR parent_source.legacy_source_extraction_sha256 IS DISTINCT FROM NEW.legacy_source_extraction_sha256
       OR parent_source.legacy_lawyers_raw IS DISTINCT FROM NEW.legacy_lawyers_raw THEN
        RAISE EXCEPTION 'POA lawyer provenance does not match its source POA';
    END IF;

    IF NEW.reviewed_rule_id IS NULL THEN
        IF NEW.source_member_ordinal <> 1 OR NOT EXISTS (
            SELECT 1 FROM public.person_name_alias a
             WHERE a.alias_ar = NEW.legacy_lawyers_raw AND a.person_id = NEW.person_id
        ) THEN
            RAISE EXCEPTION 'Direct POA lawyer must resolve through one exact alias';
        END IF;
    ELSIF NOT EXISTS (
        SELECT 1
          FROM public.migration_multi_person_rule r
          JOIN public.migration_multi_person_rule_member m ON m.rule_id = r.id
         WHERE r.id = NEW.reviewed_rule_id
           AND position(r.raw_value in NEW.legacy_lawyers_raw) > 0
           AND m.ordinal = NEW.source_member_ordinal
           AND m.person_id = NEW.person_id
    ) THEN
        RAISE EXCEPTION 'POA lawyer does not match the reviewed rule member';
    END IF;
    RETURN NEW;
END;
$POA_MEMBER$;

CREATE TRIGGER power_of_attorney_lawyers_provenance
BEFORE INSERT OR UPDATE ON public.power_of_attorney_lawyers
FOR EACH ROW EXECUTE FUNCTION public.enforce_poa_lawyer_provenance();

CREATE OR REPLACE FUNCTION quarantine.refuse_poa_evidence_change()
RETURNS trigger
LANGUAGE plpgsql
VOLATILE
CALLED ON NULL INPUT
SECURITY INVOKER
PARALLEL UNSAFE
AS $POA_EVIDENCE$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION 'Task 2.9B immutable migration evidence cannot be updated';
    END IF;
    RAISE EXCEPTION 'Task 2.9B migration evidence DELETE/TRUNCATE is refused';
END;
$POA_EVIDENCE$;

CREATE TRIGGER power_of_attorney_transform_no_change
BEFORE UPDATE OR DELETE ON quarantine.power_of_attorney_transform
FOR EACH ROW EXECUTE FUNCTION quarantine.refuse_poa_evidence_change();
CREATE TRIGGER power_of_attorney_transform_no_truncate
BEFORE TRUNCATE ON quarantine.power_of_attorney_transform
FOR EACH STATEMENT EXECUTE FUNCTION quarantine.refuse_poa_evidence_change();
CREATE TRIGGER power_of_attorney_relationship_no_change
BEFORE UPDATE OR DELETE ON quarantine.power_of_attorney_relationship
FOR EACH ROW EXECUTE FUNCTION quarantine.refuse_poa_evidence_change();
CREATE TRIGGER power_of_attorney_relationship_no_truncate
BEFORE TRUNCATE ON quarantine.power_of_attorney_relationship
FOR EACH STATEMENT EXECUTE FUNCTION quarantine.refuse_poa_evidence_change();

COMMIT;
