-- CreateTable
CREATE TABLE "people" (
    "id" SERIAL NOT NULL,
    "name_ar" TEXT NOT NULL,
    "name_en" TEXT,
    "email" TEXT,
    "is_staff" BOOLEAN NOT NULL DEFAULT true,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "is_trainee" BOOLEAN NOT NULL DEFAULT false,
    "can_login" BOOLEAN NOT NULL DEFAULT false,
    "team_id" SMALLINT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" INTEGER,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_by" INTEGER,

    CONSTRAINT "people_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "person_name_alias" (
    "id" SERIAL NOT NULL,
    "person_id" INTEGER NOT NULL,
    "alias_ar" TEXT NOT NULL,
    "is_primary" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "person_name_alias_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "lookup_team" (
    "id" SMALLSERIAL NOT NULL,
    "code" TEXT,
    "label_ar" TEXT NOT NULL,
    "specialisms" TEXT,
    "reviewer_id" INTEGER,
    "sort_order" SMALLINT NOT NULL DEFAULT 100,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" INTEGER,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_by" INTEGER,

    CONSTRAINT "lookup_team_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "people_name_ar_key" ON "people"("name_ar");

-- CreateIndex
CREATE UNIQUE INDEX "people_email_key" ON "people"("email");

-- CreateIndex
CREATE INDEX "people_is_staff_is_active_idx" ON "people"("is_staff", "is_active");

-- CreateIndex
CREATE UNIQUE INDEX "person_name_alias_alias_ar_key" ON "person_name_alias"("alias_ar");

-- CreateIndex
CREATE INDEX "person_name_alias_person_id_idx" ON "person_name_alias"("person_id");

-- CreateIndex
CREATE UNIQUE INDEX "lookup_team_label_ar_key" ON "lookup_team"("label_ar");

-- AddForeignKey
ALTER TABLE "people" ADD CONSTRAINT "people_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "lookup_team"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "person_name_alias" ADD CONSTRAINT "person_name_alias_person_id_fkey" FOREIGN KEY ("person_id") REFERENCES "people"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "lookup_team" ADD CONSTRAINT "lookup_team_reviewer_id_fkey" FOREIGN KEY ("reviewer_id") REFERENCES "people"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- ==========================================================================
--  SEED — the people roster
--
--  GENERATED by scripts/generate-roster-seed.ts from
--    sql/people-roster-and-aliases.sql   people, aliases, split rules
--    sql/lookups-part2-and-teams.sql     teams and membership
--
--  Do not hand-edit: change the source and regenerate.
--
--  138 people, from 373 spellings typed into 18 columns over six years.
--  Two of those spellings differ from another only by a hamza, and that
--  pair has already produced two duplicate people in this project.
-- ==========================================================================

-- ---- people: 138 rows ----------------------------------------
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('محمود علي', 'Mahmoud Ali', true, true, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('هاني الدالي', 'Hani El-Daly', true, true, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('محمد عبد العزيز عبد الحافظ', 'Mohamed Abd El-Aziz', true, true, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('إيهاب حمدي', 'Ehab Hamdy', true, true, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('سامي إبراهيم خطاب', 'Samy Khattab', true, true, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('أحمد سعيد', 'Ahmed Said', true, true, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('ناجي رمضان', 'Nagy Ramadan', true, true, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('هاني سري الدين', 'Dr. Hani Sarie El-Din', true, true, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('محمد حمدي', NULL, true, true, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('عبد الرحمن البنا', 'Abd Al-Rahman Al-Bana', true, true, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('نهى رضوان', NULL, true, true, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('أميرة شريف', NULL, true, true, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('عمرو سليم', 'Amr Mohammed', true, true, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('عبد الله حافظ', NULL, true, true, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('أحمد سيف', 'Ahmed Seif', true, true, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('شريف شكري', NULL, true, true, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('احمد أبو العباس الاتربي', NULL, true, true, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('أحمد رزق', NULL, true, true, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('كريم أيمن', NULL, true, true, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('عمرو صقر', 'Amr Sakr', true, true, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('نيرمين حجازي', NULL, true, true, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('محمود شعبان', 'Mahmoud Sha’ban', true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('مؤمن سليم', 'Mo''men Selim', true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('أحمد إسماعيل', 'Ahmed Ismail', true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('أحمد عبد الله', 'Dr. Ahmed Abdullah', true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('محمد الغرابلي', 'Moahmed El-Gharably', true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('شريف أبو المكارم', NULL, true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('خالد عطيه', NULL, true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('محمد طارق', 'Mohammed Tarek', true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('أحمد الصيرفي', NULL, true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('حسام الدين عمر', NULL, true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('عمرو حسني', NULL, true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('أحمد فرحات', NULL, true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('منة الله البلتاجي', NULL, true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('ليلى حسني', NULL, true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('مريهان خالد', NULL, true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('عادل عبد الرحمن', NULL, true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('مصطفى نصار', 'Mostafa Nassar', true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('منة صبري', NULL, true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('باسم عبد الرحمن', NULL, true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('خالد كمال', 'Khaled Kamal', true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('محمد أبو النجا', NULL, true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('رامي البرعي', NULL, true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('إسلام سمير', NULL, true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('معتز الدريني', NULL, true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('حسن خلف', NULL, true, false, true, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('عمر عصام', NULL, true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('حسام الدين فداء', NULL, true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('أحمد جمال', NULL, true, false, true, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('عمر شادي', NULL, true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('منتصر المصري', NULL, true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('بسام الزيات', NULL, true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('محمود الغرباوي', NULL, true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('نيرمين هاني', 'Nermin Hani', true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('علي سالم', NULL, true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('حبيبة عيسى', NULL, true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('احمد عبدالله', NULL, true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('أحمد يوسف الصيرفي', NULL, true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('لينه قناوي', NULL, true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('محمد والي', NULL, true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('احمد فرحات', NULL, true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('وسام صالح', NULL, true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('عبد الله الشهابي', NULL, true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('ليلى طموم', NULL, true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('هانيا أبو العيون', NULL, true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('مكتب سري الدين وشركاه', NULL, true, false, false, now());
INSERT INTO people (name_ar, name_en, is_staff, is_active, is_trainee, updated_at) VALUES ('خالد عطية', NULL, true, false, false, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('خالد محمود حمدي عبد العزيز', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('حسني حمزة عبدالله', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('طه خميس', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('أحمد حسن البرعي', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('طه خميس أبو الليل', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('محمد مدبولي', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('محمود مصطفى عوض', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('طارق بهجت', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('علاء محي الدين', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('محمود جمال', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('أستاذة', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('سيد كيلاني', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('طارق محمد بهجت', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('طه أبو الليل', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('عصام عبد الغني غباشي', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('عمرو محمد أحمد إسماعيل', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('محمد جوهر أحمد زغلول', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('محمد شديد لبيب الحناوي', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('محمود جمال محمود عبد العزيز', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('ناجي السيد أبو العزم', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('أحمد عبد المجيد محمود خليل', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('سامي عبد الباقي', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('طه خميس أو الليل حسن', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('عدلي سعيد', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('غبريال قسطور غبريال قسطور', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('محمد بهاء الدين أبو شقة', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('نيرمين عبد العال', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('إبراهيم محمد أحمد أبو النيل', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('إيهاب عادل رمزي', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('أحمد البرعي', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('أحمد محمد عبد الخالق سيد أحمد', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('أسامة يحيى محمود مخلوف', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('بدر الدين هاشم محجوب إبراهيم', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('ثروت صمويل ساويرس', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('حسين سيد عبد المنعم', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('حسين محمد حسين عبد العال', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('دينا يحيى قدري', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('ذكي محمد النجار', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('سامي ثابت', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('سيد توني عبد الباقي', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('شعبان', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('شعبان عبد النبي السيد', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('طارق محمد بهجت قايد', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('طه خميس أب', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('طه خميس أبو الليل حسن', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('طه خيس أبو زيد', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('عباس عبد الرحمن محمد', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('عبد الرؤوف محمد أحمد مهدي', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('عصام فواز أمين فواز', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('علاء كمال حجازي', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('على شريف', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('عمر أحمدج علي أحمد', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('ماجد فرج ميخائيل سمان', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('محسن محمد محمد زكي', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('محمد حسن علي عبد المولى', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('محمد سعد مصطفى', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('محمد سيد مصطفى الجمال', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('محمد عبد الرحيم حسن', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('محمد عبد اللطيف محموده', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('محمد محمد عيد السيد محمد', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('محمد مدبولي رمضان', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('محمد مصطفى محمد علي ناصر', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('محمود مصطفى عوض أحمد', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('محمود مصطفى معوض', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('منى لطفي زكي وهبه', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('مينا حنا شاكر', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('مينا مجدي عبده إبراهيم', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('ندى محمد احمد على', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('هاني عبدالحميد أبو سمرة', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('يحيى علي قدري', false, true, now());
INSERT INTO people (name_ar, is_staff, is_active, updated_at) VALUES ('يسري سعدي لبيب أحمد', false, true, now());

-- ---- lookup_team: 2 rows -----------------------------------
INSERT INTO lookup_team (code, label_ar, sort_order, updated_at) VALUES ('A', 'الفريق أ', 10, now());
INSERT INTO lookup_team (code, label_ar, sort_order, updated_at) VALUES ('B', 'الفريق ب', 20, now());

-- ---- person_name_alias: 339 rows -----------------------------
--
--  Each of these is an INSERT ... SELECT that matches on people.name_ar.
--  A name that matches nothing inserts nothing and reports success, which
--  is exactly the bug that created two duplicate people. The assertion
--  block at the foot catches it: the total comes up short and the whole
--  migration rolls back.
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'احمد إسماعيل', false FROM people WHERE name_ar = 'أحمد إسماعيل';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, '10- محمود شعبان', false FROM people WHERE name_ar = 'محمود شعبان';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد شعبان', false FROM people WHERE name_ar = 'محمود شعبان';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمود', false FROM people WHERE name_ar = 'محمود شعبان';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمود شعبان', true FROM people WHERE name_ar = 'محمود شعبان';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمود شعبان محمود', false FROM people WHERE name_ar = 'محمود شعبان';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'أحمد أبو العباس', false FROM people WHERE name_ar = 'احمد أبو العباس الاتربي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'أحمد الأتربي', false FROM people WHERE name_ar = 'احمد أبو العباس الاتربي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'احمد أبو العباس', false FROM people WHERE name_ar = 'احمد أبو العباس الاتربي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'احمد الاتربي', false FROM people WHERE name_ar = 'احمد أبو العباس الاتربي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'أميرة شريف', true FROM people WHERE name_ar = 'أميرة شريف';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'أميرة شريف أحمد سعيد', false FROM people WHERE name_ar = 'أميرة شريف';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'أميرة شريف أحمد فرحات', false FROM people WHERE name_ar = 'أميرة شريف';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'أميرة على شريف', false FROM people WHERE name_ar = 'أميرة شريف';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'أميرة محمد شريف', false FROM people WHERE name_ar = 'أميرة شريف';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'أميرة محمد على', false FROM people WHERE name_ar = 'أميرة شريف';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'أميرة محمد على شريف', false FROM people WHERE name_ar = 'أميرة شريف';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'أميرة محمد علي شريف', false FROM people WHERE name_ar = 'أميرة شريف';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'الاستاذه أميرة محمد على شريف', false FROM people WHERE name_ar = 'أميرة شريف';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'اميرة شريف', false FROM people WHERE name_ar = 'أميرة شريف';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'اميرة محمد على شريف', false FROM people WHERE name_ar = 'أميرة شريف';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'اميرة محمد علي شريف', false FROM people WHERE name_ar = 'أميرة شريف';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'الاستاذه منه الله صبري', false FROM people WHERE name_ar = 'منة صبري';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'منة الله السنوسي', false FROM people WHERE name_ar = 'منة صبري';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'منة الله صبري', false FROM people WHERE name_ar = 'منة صبري';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'منة صبري', true FROM people WHERE name_ar = 'منة صبري';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'منه الله صبري', false FROM people WHERE name_ar = 'منة صبري';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'منه الله صبري محمد السنوسي', false FROM people WHERE name_ar = 'منة صبري';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'الاستاذه منه الله نبيل البلتاجي', false FROM people WHERE name_ar = 'منة الله البلتاجي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'من الله البلتاجي', false FROM people WHERE name_ar = 'منة الله البلتاجي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'منة البلتاجي', false FROM people WHERE name_ar = 'منة الله البلتاجي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'منة الله البلتاجي', true FROM people WHERE name_ar = 'منة الله البلتاجي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'منة الله محمد', false FROM people WHERE name_ar = 'منة الله البلتاجي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'منة الله نبيل البلتاجي', false FROM people WHERE name_ar = 'منة الله البلتاجي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'منة الله نبيل محمد البلتاجي', false FROM people WHERE name_ar = 'منة الله البلتاجي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'منة نبيل البلتاجي', false FROM people WHERE name_ar = 'منة الله البلتاجي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'منه الله البلتاجي', false FROM people WHERE name_ar = 'منة الله البلتاجي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'الاستاذه نهى عمرو رضوان', false FROM people WHERE name_ar = 'نهى رضوان';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'نهى رضوان', true FROM people WHERE name_ar = 'نهى رضوان';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'نهى عمرو', false FROM people WHERE name_ar = 'نهى رضوان';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'نهى عمرو محمد رضوان', false FROM people WHERE name_ar = 'نهى رضوان';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'نهي رضوان', false FROM people WHERE name_ar = 'نهى رضوان';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'نهي عمرو', false FROM people WHERE name_ar = 'نهى رضوان';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'نهي عمرو محمد', false FROM people WHERE name_ar = 'نهى رضوان';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'إبراهيم محمد أحمد أبو النيل', true FROM people WHERE name_ar = 'إبراهيم محمد أحمد أبو النيل';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'إسلام سمير', true FROM people WHERE name_ar = 'إسلام سمير';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'أيهاب حمدي', false FROM people WHERE name_ar = 'إيهاب حمدي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'أيهاب حمدي إبراهيم', false FROM people WHERE name_ar = 'إيهاب حمدي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'إيهاب', false FROM people WHERE name_ar = 'إيهاب حمدي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'إيهاب حمدى', false FROM people WHERE name_ar = 'إيهاب حمدي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'إيهاب حمدي', true FROM people WHERE name_ar = 'إيهاب حمدي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'إيهاب حمدي إبراهيم', false FROM people WHERE name_ar = 'إيهاب حمدي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'إيهاب حمدي إبراهيم إمام', false FROM people WHERE name_ar = 'إيهاب حمدي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'إيهاب حمدي إبراهيم امام', false FROM people WHERE name_ar = 'إيهاب حمدي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'إيهاب حمدي إمام', false FROM people WHERE name_ar = 'إيهاب حمدي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'إيهاب عادل رمزي', true FROM people WHERE name_ar = 'إيهاب عادل رمزي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'أحمد البرعي', true FROM people WHERE name_ar = 'أحمد البرعي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'أحمد الصيرفي', true FROM people WHERE name_ar = 'أحمد الصيرفي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'أحمد إسماعيل', true FROM people WHERE name_ar = 'أحمد إسماعيل';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'أحمد إسماعيل (متابعة)', false FROM people WHERE name_ar = 'أحمد إسماعيل';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'أحمد جمال', true FROM people WHERE name_ar = 'أحمد جمال';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'أحمد جمال (متدرب)', false FROM people WHERE name_ar = 'أحمد جمال';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'أحمد حسن البرعي', true FROM people WHERE name_ar = 'أحمد حسن البرعي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'أحمد رزق', true FROM people WHERE name_ar = 'أحمد رزق';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'أحمد سعيد', true FROM people WHERE name_ar = 'أحمد سعيد';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'أحمد سعيد أحمد', false FROM people WHERE name_ar = 'أحمد سعيد';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'أحمد سعيد أحمد علي', false FROM people WHERE name_ar = 'أحمد سعيد';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'أحمد سعيد أحمد محمد علي', false FROM people WHERE name_ar = 'أحمد سعيد';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'احمد سعيد', false FROM people WHERE name_ar = 'أحمد سعيد';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'احمد سعيد احمد', false FROM people WHERE name_ar = 'أحمد سعيد';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'أحمد سيف', true FROM people WHERE name_ar = 'أحمد سيف';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'أحمد عبد الله', true FROM people WHERE name_ar = 'أحمد عبد الله';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'أحمد عبد الله أحمد', false FROM people WHERE name_ar = 'أحمد عبد الله';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'أحمد عبد الله محمد', false FROM people WHERE name_ar = 'أحمد عبد الله';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'أحمد عبد الله محمد علي', false FROM people WHERE name_ar = 'أحمد عبد الله';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'أحمد عبدالله', false FROM people WHERE name_ar = 'أحمد عبد الله';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'أحمد عبدالله محمد', false FROM people WHERE name_ar = 'أحمد عبد الله';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'احمد عبد الله', false FROM people WHERE name_ar = 'أحمد عبد الله';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'أحمد عبد المجيد محمود خليل', true FROM people WHERE name_ar = 'أحمد عبد المجيد محمود خليل';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'أحمد فرحات', true FROM people WHERE name_ar = 'أحمد فرحات';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'أحمد نبيل علي شريف فرحات', false FROM people WHERE name_ar = 'أحمد فرحات';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'أحمد نبيل فرحات', false FROM people WHERE name_ar = 'أحمد فرحات';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'أحمد نبيل محمد جمال الدين فرحات', false FROM people WHERE name_ar = 'أحمد فرحات';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'أحمد محمد عبد الخالق سيد أحمد', true FROM people WHERE name_ar = 'أحمد محمد عبد الخالق سيد أحمد';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'أحمد يوسف', false FROM people WHERE name_ar = 'أحمد يوسف الصيرفي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'أحمد يوسف الصيرفي', true FROM people WHERE name_ar = 'أحمد يوسف الصيرفي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'أسامة يحيى محمود مخلوف', true FROM people WHERE name_ar = 'أسامة يحيى محمود مخلوف';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'أستاذة', true FROM people WHERE name_ar = 'أستاذة';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'باسم عبد الرحمن', true FROM people WHERE name_ar = 'باسم عبد الرحمن';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'باسم عبد الرحمن محمد', false FROM people WHERE name_ar = 'باسم عبد الرحمن';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'وباسم عبد الرحمن', false FROM people WHERE name_ar = 'باسم عبد الرحمن';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'بدر الدين هاشم محجوب إبراهيم', true FROM people WHERE name_ar = 'بدر الدين هاشم محجوب إبراهيم';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'بسام', false FROM people WHERE name_ar = 'بسام الزيات';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'بسام الزيات', true FROM people WHERE name_ar = 'بسام الزيات';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'بسام عبد الكريم الزيات', false FROM people WHERE name_ar = 'بسام الزيات';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'ثروت صمويل ساويرس', true FROM people WHERE name_ar = 'ثروت صمويل ساويرس';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'حبيبة عيسى', true FROM people WHERE name_ar = 'حبيبة عيسى';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'حبيبة محمود سمير', false FROM people WHERE name_ar = 'حبيبة عيسى';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'حسام الدين أبراهيم عمر', false FROM people WHERE name_ar = 'حسام الدين عمر';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'حسام الدين إبراهيم', false FROM people WHERE name_ar = 'حسام الدين عمر';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'حسام الدين إبراهيم عمر', false FROM people WHERE name_ar = 'حسام الدين عمر';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'حسام الدين إبراهييم عمر', false FROM people WHERE name_ar = 'حسام الدين عمر';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'حسام الدين عمر', true FROM people WHERE name_ar = 'حسام الدين عمر';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'حسام الدين عمر إبراهيم', false FROM people WHERE name_ar = 'حسام الدين عمر';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'حسام الدين عمرإبراهيم', false FROM people WHERE name_ar = 'حسام الدين عمر';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'حسام عمر', false FROM people WHERE name_ar = 'حسام الدين عمر';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'والأساتذه حسام الدين عمر إبراهيم', false FROM people WHERE name_ar = 'حسام الدين عمر';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'وحسام الدين عمر', false FROM people WHERE name_ar = 'حسام الدين عمر';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'حسام الدين فداء', true FROM people WHERE name_ar = 'حسام الدين فداء';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'حسام الدين فداء محمد', false FROM people WHERE name_ar = 'حسام الدين فداء';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'حسام فداء', false FROM people WHERE name_ar = 'حسام الدين فداء';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'وحسام فداءمحمد حمدي كامل', false FROM people WHERE name_ar = 'حسام الدين فداء';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'حسن خلف', true FROM people WHERE name_ar = 'حسن خلف';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'حسن خلف (متدرب)', false FROM people WHERE name_ar = 'حسن خلف';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'حسن عادل "متدرب', false FROM people WHERE name_ar = 'حسن خلف';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'حسني حم', false FROM people WHERE name_ar = 'حسني حمزة عبدالله';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'حسني حمزة', false FROM people WHERE name_ar = 'حسني حمزة عبدالله';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'حسني حمزة عبد', false FROM people WHERE name_ar = 'حسني حمزة عبدالله';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'حسني حمزه', false FROM people WHERE name_ar = 'حسني حمزة عبدالله';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'حسني حمزه ع', false FROM people WHERE name_ar = 'حسني حمزة عبدالله';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'حسني حمزه عبد الله', false FROM people WHERE name_ar = 'حسني حمزة عبدالله';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'حسني حمزه عبدالله', false FROM people WHERE name_ar = 'حسني حمزة عبدالله';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'وحسني حمزة', false FROM people WHERE name_ar = 'حسني حمزة عبدالله';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'حسين سيد عبد المنعم', true FROM people WHERE name_ar = 'حسين سيد عبد المنعم';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'حسين محمد حسين عبد العال', true FROM people WHERE name_ar = 'حسين محمد حسين عبد العال';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'حمدي عبد العزيز', false FROM people WHERE name_ar = 'خالد عطيه';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'خالد حمدي', false FROM people WHERE name_ar = 'خالد عطيه';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'خالد حمدي عبد العزيز', false FROM people WHERE name_ar = 'خالد عطيه';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'خالد حمدي عبد العزيز عطية', false FROM people WHERE name_ar = 'خالد عطيه';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'خالد حمدي عبد العزيز عطيه', false FROM people WHERE name_ar = 'خالد عطيه';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'خالد حمدي عطية', false FROM people WHERE name_ar = 'خالد عطيه';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'خالد حمدي عطيه', false FROM people WHERE name_ar = 'خالد عطيه';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'خالد عطية', false FROM people WHERE name_ar = 'خالد عطيه';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'خالد عطيه', true FROM people WHERE name_ar = 'خالد عطيه';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'خالد محمود حمدي', false FROM people WHERE name_ar = 'خالد عطيه';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'خالد محمود حمدي عبد العزيز عطية والأساتذة', false FROM people WHERE name_ar = 'خالد عطيه';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'خالد محمود حمدي عطية', false FROM people WHERE name_ar = 'خالد عطيه';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'خالد محمود حمدي عطيه', false FROM people WHERE name_ar = 'خالد عطيه';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'خالد كمال', true FROM people WHERE name_ar = 'خالد كمال';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'خالد محمود حمدي عبد العزيز', true FROM people WHERE name_ar = 'خالد محمود حمدي عبد العزيز';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'دينا يحيى قدري', true FROM people WHERE name_ar = 'دينا يحيى قدري';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'ذكي محمد النجار', true FROM people WHERE name_ar = 'ذكي محمد النجار';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'رامي أحمد حسن البرعي', false FROM people WHERE name_ar = 'رامي البرعي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'رامي البرعي', true FROM people WHERE name_ar = 'رامي البرعي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'سامي إبراهيم', false FROM people WHERE name_ar = 'سامي إبراهيم خطاب';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'سامي إبراهيم محمد يوسف', false FROM people WHERE name_ar = 'سامي إبراهيم خطاب';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'سامي خطاب', false FROM people WHERE name_ar = 'سامي إبراهيم خطاب';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'سامي خطب', false FROM people WHERE name_ar = 'سامي إبراهيم خطاب';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'سامي ثابت', true FROM people WHERE name_ar = 'سامي ثابت';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'سامي عبد الباقي', true FROM people WHERE name_ar = 'سامي عبد الباقي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'سيد توني عبد الباقي', true FROM people WHERE name_ar = 'سيد توني عبد الباقي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'سيد كيلاني', true FROM people WHERE name_ar = 'سيد كيلاني';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'شريف أبو ا لمكارم صالح', false FROM people WHERE name_ar = 'شريف أبو المكارم';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'شريف أبو المكارم', true FROM people WHERE name_ar = 'شريف أبو المكارم';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'شريف أبو المكارم صالح', false FROM people WHERE name_ar = 'شريف أبو المكارم';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'شريف أبو المكارم صالح سليمان', false FROM people WHERE name_ar = 'شريف أبو المكارم';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'شريف أبو المكارم صالح والأستاذ', false FROM people WHERE name_ar = 'شريف أبو المكارم';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'شريف أبوالمكارم', false FROM people WHERE name_ar = 'شريف أبو المكارم';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'وشريف أبو المكارم', false FROM people WHERE name_ar = 'شريف أبو المكارم';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'شريف شكري', true FROM people WHERE name_ar = 'شريف شكري';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'شعبان', true FROM people WHERE name_ar = 'شعبان';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'شعبان عبد النبي السيد', true FROM people WHERE name_ar = 'شعبان عبد النبي السيد';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'طارق بهجت', true FROM people WHERE name_ar = 'طارق بهجت';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'طارق محمد بهجت', true FROM people WHERE name_ar = 'طارق محمد بهجت';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'طارق محمد بهجت قايد', true FROM people WHERE name_ar = 'طارق محمد بهجت قايد';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'طه أبو الليل', true FROM people WHERE name_ar = 'طه أبو الليل';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'طه خميس', true FROM people WHERE name_ar = 'طه خميس';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'طه خميس أب', true FROM people WHERE name_ar = 'طه خميس أب';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'طه خميس أبو الليل', true FROM people WHERE name_ar = 'طه خميس أبو الليل';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'طه خميس أبو الليل حسن', true FROM people WHERE name_ar = 'طه خميس أبو الليل حسن';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'طه خميس أو الليل حسن', true FROM people WHERE name_ar = 'طه خميس أو الليل حسن';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'طه خيس أبو زيد', true FROM people WHERE name_ar = 'طه خيس أبو زيد';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'عادل عبد الرحمن', true FROM people WHERE name_ar = 'عادل عبد الرحمن';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'عادل عبد الرحمن عبد الجليل محمد', false FROM people WHERE name_ar = 'عادل عبد الرحمن';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'عادل عبدالرحمن', false FROM people WHERE name_ar = 'عادل عبد الرحمن';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'عباس عبد الرحمن محمد', true FROM people WHERE name_ar = 'عباس عبد الرحمن محمد';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'عبد الرحمن أحمد عبد العزيز', false FROM people WHERE name_ar = 'عبد الرحمن البنا';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'عبد الرحمن احمد', false FROM people WHERE name_ar = 'عبد الرحمن البنا';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'عبد الرحمن احمد عبد العزيز', false FROM people WHERE name_ar = 'عبد الرحمن البنا';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'عبد الرحمن البنا', true FROM people WHERE name_ar = 'عبد الرحمن البنا';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'عبد الرؤوف محمد أحمد مهدي', true FROM people WHERE name_ar = 'عبد الرؤوف محمد أحمد مهدي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'عبد الله الشهبي', false FROM people WHERE name_ar = 'عبد الله الشهابي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'عبد الله يحي عبد الله الشهابي', false FROM people WHERE name_ar = 'عبد الله الشهابي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'عبد الله حافظ', true FROM people WHERE name_ar = 'عبد الله حافظ';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'عبد الله عمرو', false FROM people WHERE name_ar = 'عبد الله حافظ';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'عبدالله عمرو', false FROM people WHERE name_ar = 'عبد الله حافظ';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'عدلي سعيد', true FROM people WHERE name_ar = 'عدلي سعيد';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'عصام عبد الغني غباشي', true FROM people WHERE name_ar = 'عصام عبد الغني غباشي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'عصام فواز أمين فواز', true FROM people WHERE name_ar = 'عصام فواز أمين فواز';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'علاء كمال حجازي', true FROM people WHERE name_ar = 'علاء كمال حجازي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'علاء محي الدين', true FROM people WHERE name_ar = 'علاء محي الدين';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'على شريف', true FROM people WHERE name_ar = 'على شريف';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'علي سالم', true FROM people WHERE name_ar = 'علي سالم';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'عمر', false FROM people WHERE name_ar = 'عمر عصام';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'عمر عصام', true FROM people WHERE name_ar = 'عمر عصام';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'عمر عصام حنفي', false FROM people WHERE name_ar = 'عمر عصام';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'عمر عصام حنفي محمد', false FROM people WHERE name_ar = 'عمر عصام';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'عمر أحمدج علي أحمد', true FROM people WHERE name_ar = 'عمر أحمدج علي أحمد';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'عمر شادي', true FROM people WHERE name_ar = 'عمر شادي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'عمرو حسني', true FROM people WHERE name_ar = 'عمرو حسني';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'عمرو حسني سالم', false FROM people WHERE name_ar = 'عمرو حسني';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'عمرو حسني سالم سيد', false FROM people WHERE name_ar = 'عمرو حسني';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'عمرو حسني سالم سيد أحمد', false FROM people WHERE name_ar = 'عمرو حسني';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'عمرو سليم', true FROM people WHERE name_ar = 'عمرو سليم';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'عمرو محمد', false FROM people WHERE name_ar = 'عمرو سليم';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'عمرو محمد عبد الحميد', false FROM people WHERE name_ar = 'عمرو سليم';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'عمرو محمد عبد الحميد عبده سليم', false FROM people WHERE name_ar = 'عمرو سليم';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'عمرو صقر', true FROM people WHERE name_ar = 'عمرو صقر';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'عمرو محمد أحمد إسماعيل', true FROM people WHERE name_ar = 'عمرو محمد أحمد إسماعيل';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'غبريال قسطور غبريال قسطور', true FROM people WHERE name_ar = 'غبريال قسطور غبريال قسطور';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'كريم أيمن', true FROM people WHERE name_ar = 'كريم أيمن';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'كريم أيمن محمد', false FROM people WHERE name_ar = 'كريم أيمن';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'كريم ايمن محمد', false FROM people WHERE name_ar = 'كريم أيمن';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'ليلى أمين طموم', false FROM people WHERE name_ar = 'ليلى طموم';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'ليلى طموم', true FROM people WHERE name_ar = 'ليلى طموم';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'ليلى حسني', true FROM people WHERE name_ar = 'ليلى حسني';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'ليلى يحي حسني', false FROM people WHERE name_ar = 'ليلى حسني';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'ليلى يحيى حسني', false FROM people WHERE name_ar = 'ليلى حسني';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'ليلي يحي حسني', false FROM people WHERE name_ar = 'ليلى حسني';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'ليلي يحيى حسن', false FROM people WHERE name_ar = 'ليلى حسني';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'ليلي يحيى حسني', false FROM people WHERE name_ar = 'ليلى حسني';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'ليلي يحيي حسني', false FROM people WHERE name_ar = 'ليلى حسني';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'لينه قناوي', true FROM people WHERE name_ar = 'لينه قناوي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'ماجد فرج ميخائيل سمان', true FROM people WHERE name_ar = 'ماجد فرج ميخائيل سمان';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محسن محمد محمد زكي', true FROM people WHERE name_ar = 'محسن محمد محمد زكي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد الغرابلي', true FROM people WHERE name_ar = 'محمد الغرابلي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد الغرابي', false FROM people WHERE name_ar = 'محمد الغرابلي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد الغربالي', false FROM people WHERE name_ar = 'محمد الغرابلي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد الغربلي', false FROM people WHERE name_ar = 'محمد الغرابلي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد مجدي', false FROM people WHERE name_ar = 'محمد الغرابلي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد مجدي الغرابلي', false FROM people WHERE name_ar = 'محمد الغرابلي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد مجدي الغربلي', false FROM people WHERE name_ar = 'محمد الغرابلي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد مجدي سيد أحمد', false FROM people WHERE name_ar = 'محمد الغرابلي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد مجدي سيد أحمد الغرابلي', false FROM people WHERE name_ar = 'محمد الغرابلي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد مجدي سيد أحمد رمضان', false FROM people WHERE name_ar = 'محمد الغرابلي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد مجدي سيد احمد الغرابلي', false FROM people WHERE name_ar = 'محمد الغرابلي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'ومحمد مجدي أحمد الغرابلي', false FROM people WHERE name_ar = 'محمد الغرابلي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد أبو النج', false FROM people WHERE name_ar = 'محمد أبو النجا';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد أبو النجا', true FROM people WHERE name_ar = 'محمد أبو النجا';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد عصام', false FROM people WHERE name_ar = 'محمد أبو النجا';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد بهاء الدين أبو شقة', true FROM people WHERE name_ar = 'محمد بهاء الدين أبو شقة';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد بهاء الدين أبو شقه', false FROM people WHERE name_ar = 'محمد بهاء الدين أبو شقة';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد جوهر أحمد زغلول', true FROM people WHERE name_ar = 'محمد جوهر أحمد زغلول';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد حسن علي عبد المولى', true FROM people WHERE name_ar = 'محمد حسن علي عبد المولى';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد حمدي', true FROM people WHERE name_ar = 'محمد حمدي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد حمدي كامب', false FROM people WHERE name_ar = 'محمد حمدي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد حمدي كامل', false FROM people WHERE name_ar = 'محمد حمدي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد حمدي كامل مصطفى', false FROM people WHERE name_ar = 'محمد حمدي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمدي', false FROM people WHERE name_ar = 'محمد حمدي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'ومحمد حمدي', false FROM people WHERE name_ar = 'محمد حمدي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد سعد مصطفى', true FROM people WHERE name_ar = 'محمد سعد مصطفى';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد سيد مصطفى الجمال', true FROM people WHERE name_ar = 'محمد سيد مصطفى الجمال';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد شديد لبيب الحناوي', true FROM people WHERE name_ar = 'محمد شديد لبيب الحناوي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد طارق', true FROM people WHERE name_ar = 'محمد طارق';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد عبد الحافظ عبد العزيز', false FROM people WHERE name_ar = 'محمد عبد العزيز عبد الحافظ';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد عبد العزيز', false FROM people WHERE name_ar = 'محمد عبد العزيز عبد الحافظ';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد عبد العزيز (تليفونياً)', false FROM people WHERE name_ar = 'محمد عبد العزيز عبد الحافظ';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد عبد العزيز عبد الحافظ', true FROM people WHERE name_ar = 'محمد عبد العزيز عبد الحافظ';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد عبد العزيز عبد الحافظ محمد', false FROM people WHERE name_ar = 'محمد عبد العزيز عبد الحافظ';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد عبد الهزيز عبد الحافظ', false FROM people WHERE name_ar = 'محمد عبد العزيز عبد الحافظ';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد عبدالعزيز', false FROM people WHERE name_ar = 'محمد عبد العزيز عبد الحافظ';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد عبدالعزيز عبدالحافظ', false FROM people WHERE name_ar = 'محمد عبد العزيز عبد الحافظ';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد عدبد العزيز', false FROM people WHERE name_ar = 'محمد عبد العزيز عبد الحافظ';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمدعبد العزيز', false FROM people WHERE name_ar = 'محمد عبد العزيز عبد الحافظ';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد عبد الرحيم حسن', true FROM people WHERE name_ar = 'محمد عبد الرحيم حسن';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد عبد اللطيف محموده', true FROM people WHERE name_ar = 'محمد عبد اللطيف محموده';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد محمد عيد السيد محمد', true FROM people WHERE name_ar = 'محمد محمد عيد السيد محمد';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد مدبولي', true FROM people WHERE name_ar = 'محمد مدبولي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد مدبولي رمضان', true FROM people WHERE name_ar = 'محمد مدبولي رمضان';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد مصطفى محمد علي ناصر', true FROM people WHERE name_ar = 'محمد مصطفى محمد علي ناصر';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد والي', true FROM people WHERE name_ar = 'محمد والي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد والي عبد الهادي', false FROM people WHERE name_ar = 'محمد والي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمد والي عبد الهادي محمد', false FROM people WHERE name_ar = 'محمد والي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمود الغرباوي', true FROM people WHERE name_ar = 'محمود الغرباوي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمود جمال', true FROM people WHERE name_ar = 'محمود جمال';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمود جمال محمود عبد العزيز', true FROM people WHERE name_ar = 'محمود جمال محمود عبد العزيز';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمود علي', true FROM people WHERE name_ar = 'محمود علي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمود علي محمود حسين', false FROM people WHERE name_ar = 'محمود علي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمودعلي', false FROM people WHERE name_ar = 'محمود علي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمود مصطفى عوض', true FROM people WHERE name_ar = 'محمود مصطفى عوض';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمود مصطفى عوض أحمد', true FROM people WHERE name_ar = 'محمود مصطفى عوض أحمد';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'محمود مصطفى معوض', true FROM people WHERE name_ar = 'محمود مصطفى معوض';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'مريهان خالد', true FROM people WHERE name_ar = 'مريهان خالد';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'مصطفى', false FROM people WHERE name_ar = 'مصطفى نصار';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'مصطفى خالد محمد خير الدين نصار', false FROM people WHERE name_ar = 'مصطفى نصار';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'مصطفى محمود عبدالمنعم', false FROM people WHERE name_ar = 'مصطفى نصار';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'مصطفى نصار', true FROM people WHERE name_ar = 'مصطفى نصار';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'معتز الدريني', true FROM people WHERE name_ar = 'معتز الدريني';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'معتز عبد العزيز الدريني', false FROM people WHERE name_ar = 'معتز الدريني';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'معتز عبد العزيز الدريني والأستاذ', false FROM people WHERE name_ar = 'معتز الدريني';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'ومعتز الدريني', false FROM people WHERE name_ar = 'معتز الدريني';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'مكتب سري الدين وشركاه', true FROM people WHERE name_ar = 'مكتب سري الدين وشركاه';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'منتصر المصري', true FROM people WHERE name_ar = 'منتصر المصري';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'منى لطفي زكي وهبه', true FROM people WHERE name_ar = 'منى لطفي زكي وهبه';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'مؤمن سليم', true FROM people WHERE name_ar = 'مؤمن سليم';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'مؤمن عبد الله محمد أحمد سليم', false FROM people WHERE name_ar = 'مؤمن سليم';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'مينا حنا شاكر', true FROM people WHERE name_ar = 'مينا حنا شاكر';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'مينا مجدي عبده إبراهيم', true FROM people WHERE name_ar = 'مينا مجدي عبده إبراهيم';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'ناجي السيد أبو العزم', true FROM people WHERE name_ar = 'ناجي السيد أبو العزم';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'ناجي رمضان', true FROM people WHERE name_ar = 'ناجي رمضان';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'ناجي رمضان أمين', false FROM people WHERE name_ar = 'ناجي رمضان';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'ناجي رمضان أمين محمد', false FROM people WHERE name_ar = 'ناجي رمضان';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'ناجي رمضان امين', false FROM people WHERE name_ar = 'ناجي رمضان';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'نبيل فرحات', false FROM people WHERE name_ar = 'احمد فرحات';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'ندى محمد احمد على', true FROM people WHERE name_ar = 'ندى محمد احمد على';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'نيرمين حجازي', true FROM people WHERE name_ar = 'نيرمين حجازي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'نيرمين عبد العال', true FROM people WHERE name_ar = 'نيرمين عبد العال';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'نيرمين هاني', true FROM people WHERE name_ar = 'نيرمين هاني';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'هاني أحمد الدالي', false FROM people WHERE name_ar = 'هاني الدالي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'هاني أحمد عبد المجيد الدالي', false FROM people WHERE name_ar = 'هاني الدالي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'هاني احمد عبد المجيد', false FROM people WHERE name_ar = 'هاني الدالي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'هاني الدالي', true FROM people WHERE name_ar = 'هاني الدالي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'هاني الدالي (صباحي)', false FROM people WHERE name_ar = 'هاني الدالي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'هاني الدالي (مسائي)', false FROM people WHERE name_ar = 'هاني الدالي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'هاني الدالي متابعة للشطب', false FROM people WHERE name_ar = 'هاني الدالي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'هاني عبد المجيد الدالي', false FROM people WHERE name_ar = 'هاني الدالي';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'هاني سري الدين', true FROM people WHERE name_ar = 'هاني سري الدين';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'هاني سري الدين والأساتذة', false FROM people WHERE name_ar = 'هاني سري الدين';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'هاني سري الدينِ', false FROM people WHERE name_ar = 'هاني سري الدين';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'هاني سريّ الدين', false FROM people WHERE name_ar = 'هاني سري الدين';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'هاني صلاح الدين', false FROM people WHERE name_ar = 'هاني سري الدين';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'هاني صلاح سري الدين', false FROM people WHERE name_ar = 'هاني سري الدين';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'هاني صلاح سري الدين والأستاذ', false FROM people WHERE name_ar = 'هاني سري الدين';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'هاني صلاح سري الدين ود', false FROM people WHERE name_ar = 'هاني سري الدين';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'هاني صلاح محمد سؤي الدين', false FROM people WHERE name_ar = 'هاني سري الدين';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'هاني صلاح محمد سري الدن', false FROM people WHERE name_ar = 'هاني سري الدين';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'هاني صلاح محمد سري الدين', false FROM people WHERE name_ar = 'هاني سري الدين';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'هاني صلاح محمد سيف الدين', false FROM people WHERE name_ar = 'هاني سري الدين';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'هاني صلح الدين', false FROM people WHERE name_ar = 'هاني سري الدين';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'هاني عبدالحميد أبو سمرة', true FROM people WHERE name_ar = 'هاني عبدالحميد أبو سمرة';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'هانيا أبو العيون', true FROM people WHERE name_ar = 'هانيا أبو العيون';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'وأحمد عبد الله محمد', false FROM people WHERE name_ar = 'احمد عبدالله';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'والأساتذه أحمد عبد الله محمد علي', false FROM people WHERE name_ar = 'احمد عبدالله';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'وأحمد سعيد أحمد', false FROM people WHERE name_ar = 'أحمد سعيد';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'ود. خالد محمود حمدي عبد العزيز عطية', false FROM people WHERE name_ar = 'خالد عطية';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'وسام صالح', true FROM people WHERE name_ar = 'وسام صالح';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'ىأحمد إسماعيل', false FROM people WHERE name_ar = 'أحمد إسماعيل';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'يحيى علي قدري', true FROM people WHERE name_ar = 'يحيى علي قدري';
INSERT INTO person_name_alias (person_id, alias_ar, is_primary) SELECT id, 'يسري سعدي لبيب أحمد', true FROM people WHERE name_ar = 'يسري سعدي لبيب أحمد';

-- ---- teams: reviewer and membership ------------------------------------
--
--  Matched through person_name_alias, never through people.name_ar — a
--  hamza variant would otherwise update nothing and report success.
UPDATE lookup_team SET reviewer_id = (SELECT id FROM people WHERE name_ar = 'ناجي رمضان')
WHERE code = 'A';
UPDATE lookup_team SET reviewer_id = (SELECT id FROM people WHERE name_ar = 'ناجي رمضان')
WHERE code = 'B';
UPDATE people p SET team_id = (SELECT id FROM lookup_team WHERE code = 'A')
WHERE EXISTS (
    SELECT 1 FROM person_name_alias a
    WHERE a.person_id = p.id
      AND a.alias_ar IN ('إيهاب حمدي', 'مؤمن سليم', 'أحمد إسماعيل', 'أحمد سيف')
);
UPDATE people p SET team_id = (SELECT id FROM lookup_team WHERE code = 'B')
WHERE EXISTS (
    SELECT 1 FROM person_name_alias a
    WHERE a.person_id = p.id
      AND a.alias_ar IN ('محمد عبد العزيز عبد الحافظ', 'محمد عبد العزيز',
                         'أحمد سعيد', 'هاني الدالي', 'محمود شعبان')
);

-- ==========================================================================
--  ASSERT — rule 15
--
--  Every figure, not just the headline two. These five moved together once
--  already: merging two duplicate people changed people 140->138, staff
--  69->67, current 23->21, unassigned 18->16 and aliases 338->339. One was
--  corrected and four were left stale, and the assertion written at the
--  time would have FAILED on correct data.
-- ==========================================================================
DO $ROSTER$
DECLARE
    actual integer;
BEGIN
    SELECT count(*) FROM people INTO actual;
    IF actual <> 138 THEN
        RAISE EXCEPTION 'people: % , expected 138', actual;
    END IF;

    SELECT count(*) FROM person_name_alias INTO actual;
    IF actual <> 339 THEN
        RAISE EXCEPTION 'person_name_alias: % , expected 339', actual;
    END IF;

    SELECT count(*) FROM people WHERE is_staff INTO actual;
    IF actual <> 67 THEN
        RAISE EXCEPTION 'firm staff: % , expected 67', actual;
    END IF;

    SELECT count(*) FROM people WHERE is_staff AND is_active INTO actual;
    IF actual <> 21 THEN
        RAISE EXCEPTION 'current staff: % , expected 21', actual;
    END IF;

    SELECT count(*) FROM people WHERE is_staff AND NOT is_active INTO actual;
    IF actual <> 46 THEN
        RAISE EXCEPTION 'former staff: % , expected 46', actual;
    END IF;

    SELECT count(*) FROM people WHERE NOT is_staff INTO actual;
    IF actual <> 71 THEN
        RAISE EXCEPTION 'external people: % , expected 71', actual;
    END IF;

    SELECT count(*) FROM lookup_team INTO actual;
    IF actual <> 2 THEN
        RAISE EXCEPTION 'teams: % , expected 2', actual;
    END IF;

    SELECT count(*) FROM people WHERE team_id IS NOT NULL INTO actual;
    IF actual <> 8 THEN
        RAISE EXCEPTION 'people with a team: % , expected 8', actual;
    END IF;

    SELECT count(*) FROM people WHERE is_staff AND is_active AND team_id IS NOT NULL INTO actual;
    IF actual <> 5 THEN
        RAISE EXCEPTION 'current staff with a team: % , expected 5', actual;
    END IF;

    SELECT count(*) FROM people WHERE is_staff AND is_active AND team_id IS NULL INTO actual;
    IF actual <> 16 THEN
        RAISE EXCEPTION 'current staff without a team: % , expected 16', actual;
    END IF;

    -- The two hamza pairs must resolve to ONE person each, reached through
    -- the alias. This is the bug that created the duplicates: the spelling
    -- without the hamza must be an ALIAS, not a person of its own.
    SELECT count(*) INTO actual FROM people WHERE name_ar IN ('احمد إسماعيل', 'احمد سعيد');
    IF actual <> 0 THEN
        RAISE EXCEPTION 'the hamza-less spellings are people again: % rows', actual;
    END IF;

    SELECT count(*) INTO actual FROM people WHERE name_ar = 'أحمد إسماعيل';
    IF actual <> 1 THEN
        RAISE EXCEPTION 'أحمد إسماعيل appears % times as a person, expected exactly 1', actual;
    END IF;

    SELECT count(*) INTO actual FROM people WHERE name_ar = 'أحمد سعيد';
    IF actual <> 1 THEN
        RAISE EXCEPTION 'أحمد سعيد appears % times as a person, expected exactly 1', actual;
    END IF;

    -- ...and each hamza-less spelling must reach that one person through
    -- the alias table. Absent from people AND absent from aliases would
    -- also satisfy the check above, and would lose every row using it.
    SELECT count(*) INTO actual
      FROM person_name_alias a JOIN people p ON p.id = a.person_id
     WHERE a.alias_ar = 'احمد إسماعيل' AND p.name_ar = 'أحمد إسماعيل';
    IF actual <> 1 THEN
        RAISE EXCEPTION 'احمد إسماعيل does not resolve to أحمد إسماعيل';
    END IF;

    SELECT count(*) INTO actual
      FROM person_name_alias a JOIN people p ON p.id = a.person_id
     WHERE a.alias_ar = 'احمد سعيد' AND p.name_ar = 'أحمد سعيد';
    IF actual <> 1 THEN
        RAISE EXCEPTION 'احمد سعيد does not resolve to أحمد سعيد';
    END IF;

    -- No spelling may belong to two people. The unique index enforces it;
    -- this says so out loud, because it is the whole point of the table.
    SELECT count(*) INTO actual FROM (
        SELECT alias_ar FROM person_name_alias GROUP BY alias_ar HAVING count(*) > 1
    ) d;
    IF actual <> 0 THEN
        RAISE EXCEPTION '% spellings map to more than one person', actual;
    END IF;

    RAISE NOTICE 'roster seeded: 138 people, 339 aliases, 2 teams';
END
$ROSTER$;
