/*
 * Turns sql/people-roster-and-aliases.sql and the teams half of
 * sql/lookups-part2-and-teams.sql into the seed of a Prisma migration.
 *
 *     npm run generate:roster-seed <path to migration.sql>
 *
 * Same principle as scripts/generate-lookup-seed.ts, and the same reason:
 * 138 people and 339 spellings, almost all Arabic, many differing by one
 * character. Two of them differ ONLY by a hamza — احمد إسماعيل against
 * أحمد إسماعيل — and that pair has already produced two duplicate people in
 * this project, one carrying 1,309 hearings. Nobody retypes this.
 *
 * WHAT THIS SCRIPT WATCHES FOR
 *
 * The alias inserts in the source are written as
 *
 *     INSERT INTO person_name_alias (...) SELECT id, 'x' FROM people
 *      WHERE name_ar = 'y';
 *
 * If 'y' matches no person, that statement inserts NOTHING and reports
 * success. That is the exact shape of the bug that created the duplicates:
 * a generator "found 0 mentions" and carried on. So every count is asserted
 * after loading — a statement that quietly did nothing shows up as a short
 * total, and the migration aborts inside its transaction.
 */

import { readFileSync, writeFileSync } from 'node:fs';

const ROSTER = 'sql/people-roster-and-aliases.sql';
const TEAMS = 'sql/lookups-part2-and-teams.sql';

/*
 * Expected counts. Every one of these is derived from the others, and they
 * have moved together before: merging two duplicate people changed five
 * figures at once and four were left stale. So all of them are stated, and
 * the arithmetic between them is checked too.
 */
/*
 * These are the figures THIS migration loads. Two later migrations change
 * them, and db:check asserts the live values:
 *   0005 alias_completeness            aliases 339 -> 347
 *   0006 merge_name_variant_duplicates people  138 -> 135, staff 67 -> 64,
 *                                      former  46 -> 43
 */
const EXPECTED = {
  people: 138,
  /*
   * 339 is what THIS migration loads. Migration 0005 (alias_completeness)
   * then adds 8 more — six people's own names, which were missing, plus two
   * spacing variants — taking the live total to 347. db:check asserts 347.
   */
  aliases: 339,
  staff: 67,
  currentStaff: 21,
  formerStaff: 46,
  external: 71,
  teams: 2,
  teamMembers: 8,
  currentWithTeam: 5,
  currentWithoutTeam: 16,
  multiPersonRules: 33,
  multiPersonMembers: 84,
  excludedNames: 38,
} as const;

/* Cross-checks between the figures above, so a stale one cannot survive. */
const ARITHMETIC: Array<[string, number, number]> = [
  ['staff + external = people', EXPECTED.staff + EXPECTED.external, EXPECTED.people],
  ['current + former = staff', EXPECTED.currentStaff + EXPECTED.formerStaff, EXPECTED.staff],
  [
    'current with a team + current without = current staff',
    EXPECTED.currentWithTeam + EXPECTED.currentWithoutTeam,
    EXPECTED.currentStaff,
  ],
];

for (const [name, left, right] of ARITHMETIC) {
  if (left !== right) {
    throw new Error(`the expected figures disagree with each other: ${name} (${left} ≠ ${right})`);
  }
}

function statements(file: string, prefix: string, expected: number, what: string): string[] {
  const found = readFileSync(file, 'utf8')
    .split('\n')
    .filter((line) => line.startsWith(prefix));
  if (found.length !== expected) {
    throw new Error(
      `${what}: found ${found.length} statements in ${file}, expected ${expected}. ` +
        `Either the source changed or the match is wrong. Neither may be seeded.`,
    );
  }
  return found;
}

/* people has audit columns the source does not know about. */
function withUpdatedAt(insert: string): string {
  const open = insert.indexOf('(');
  const close = insert.indexOf(')');
  const valuesAt = insert.indexOf('VALUES (');
  const end = insert.lastIndexOf(');');
  if (open === -1 || close === -1 || valuesAt === -1 || end === -1) {
    throw new Error(`could not read this INSERT: ${insert}`);
  }
  const columns = insert.slice(open + 1, close);
  const values = insert.slice(valuesAt + 'VALUES ('.length, end);
  return `INSERT INTO people (${columns}, updated_at) VALUES (${values}, now());`;
}

const out: string[] = [];
const push = (...lines: string[]) => out.push(...lines);

push(
  '-- ==========================================================================',
  '--  SEED — the people roster',
  '--',
  '--  GENERATED by scripts/generate-roster-seed.ts from',
  '--    sql/people-roster-and-aliases.sql   people, aliases, split rules',
  '--    sql/lookups-part2-and-teams.sql     teams and membership',
  '--',
  '--  Do not hand-edit: change the source and regenerate.',
  '--',
  '--  138 people, from 373 spellings typed into 18 columns over six years.',
  '--  Two of those spellings differ from another only by a hamza, and that',
  '--  pair has already produced two duplicate people in this project.',
  '-- ==========================================================================',
  '',
);

// ---- people ---------------------------------------------------------------
const people = statements(ROSTER, 'INSERT INTO people (', EXPECTED.people, 'people');
push(`-- ---- people: ${people.length} rows ----------------------------------------`);
push(...people.map(withUpdatedAt), '');

// ---- teams, before the aliases that no rule needs, but after people -------
const teamInserts = statements(TEAMS, 'INSERT INTO lookup_team (', EXPECTED.teams, 'lookup_team');
push(`-- ---- lookup_team: ${teamInserts.length} rows -----------------------------------`);
push(
  ...teamInserts.map((s) =>
    s
      .replace('VALUES (', 'VALUES (')
      .replace(');', ', now());')
      .replace(
        'INSERT INTO lookup_team (code, label_ar, sort_order)',
        'INSERT INTO lookup_team (code, label_ar, sort_order, updated_at)',
      ),
  ),
  '',
);

// ---- aliases --------------------------------------------------------------
const aliases = statements(
  ROSTER,
  'INSERT INTO person_name_alias (',
  EXPECTED.aliases,
  'person_name_alias',
);
push(
  `-- ---- person_name_alias: ${aliases.length} rows -----------------------------`,
  '--',
  '--  Each of these is an INSERT ... SELECT that matches on people.name_ar.',
  '--  A name that matches nothing inserts nothing and reports success, which',
  '--  is exactly the bug that created two duplicate people. The assertion',
  '--  block at the foot catches it: the total comes up short and the whole',
  '--  migration rolls back.',
);
push(...aliases, '');

// ---- team reviewer and membership -----------------------------------------
const teamUpdates = readFileSync(TEAMS, 'utf8')
  .split('\n')
  .filter(
    (l) =>
      l.startsWith('UPDATE lookup_team SET reviewer_id') ||
      l.startsWith('UPDATE people p SET team_id'),
  );
push(
  '-- ---- teams: reviewer and membership ------------------------------------',
  '--',
  '--  Matched through person_name_alias, never through people.name_ar — a',
  '--  hamza variant would otherwise update nothing and report success.',
);
{
  /* The UPDATEs span several lines each; take them whole. */
  const lines = readFileSync(TEAMS, 'utf8').split('\n');
  const blocks: string[] = [];
  for (let i = 0; i < lines.length; i += 1) {
    const line = lines[i] ?? '';
    if (!line.startsWith('UPDATE ')) continue;
    const block: string[] = [];
    for (let j = i; j < lines.length; j += 1) {
      const l = lines[j] ?? '';
      block.push(l);
      if (l.trimEnd().endsWith(';')) {
        i = j;
        break;
      }
    }
    blocks.push(block.join('\n'));
  }
  if (blocks.length !== 4) {
    throw new Error(`expected 4 team UPDATE statements, found ${blocks.length}`);
  }
  push(...blocks, '');
}
void teamUpdates;

/*
 * The multi-person split rules and excluded names are DEFERRED to task 2.7.
 * The reviewed export originally contained 66 member rows. Task 2.7 applies
 * the firm's three corrections without removing any valid member: two empty
 * rules gain 6 and 5 members, while one malformed pseudo-member becomes 8
 * real members. The corrected canonical total is therefore 84.
 */

// ---- assertions -----------------------------------------------------------
push(
  '-- ==========================================================================',
  '--  ASSERT — rule 15',
  '--',
  '--  Every figure, not just the headline two. These five moved together once',
  '--  already: merging two duplicate people changed people 140->138, staff',
  '--  69->67, current 23->21, unassigned 18->16 and aliases 338->339. One was',
  '--  corrected and four were left stale, and the assertion written at the',
  '--  time would have FAILED on correct data.',
  '-- ==========================================================================',
  'DO $ROSTER$',
  'DECLARE',
  '    actual integer;',
  'BEGIN',
);

const assertion = (label: string, sql: string, expected: number) => {
  push(
    `    SELECT ${sql} INTO actual;`,
    `    IF actual <> ${expected} THEN`,
    `        RAISE EXCEPTION '${label}: % , expected ${expected}', actual;`,
    '    END IF;',
    '',
  );
};

assertion('people', 'count(*) FROM people', EXPECTED.people);
assertion('person_name_alias', 'count(*) FROM person_name_alias', EXPECTED.aliases);
assertion('firm staff', 'count(*) FROM people WHERE is_staff', EXPECTED.staff);
assertion(
  'current staff',
  'count(*) FROM people WHERE is_staff AND is_active',
  EXPECTED.currentStaff,
);
assertion(
  'former staff',
  'count(*) FROM people WHERE is_staff AND NOT is_active',
  EXPECTED.formerStaff,
);
assertion('external people', 'count(*) FROM people WHERE NOT is_staff', EXPECTED.external);
assertion('teams', 'count(*) FROM lookup_team', EXPECTED.teams);
assertion(
  'people with a team',
  'count(*) FROM people WHERE team_id IS NOT NULL',
  EXPECTED.teamMembers,
);
assertion(
  'current staff with a team',
  'count(*) FROM people WHERE is_staff AND is_active AND team_id IS NOT NULL',
  EXPECTED.currentWithTeam,
);
assertion(
  'current staff without a team',
  'count(*) FROM people WHERE is_staff AND is_active AND team_id IS NULL',
  EXPECTED.currentWithoutTeam,
);
push(
  '    -- The two hamza pairs must resolve to ONE person each, reached through',
  '    -- the alias. This is the bug that created the duplicates: the spelling',
  '    -- without the hamza must be an ALIAS, not a person of its own.',
  "    SELECT count(*) INTO actual FROM people WHERE name_ar IN ('احمد إسماعيل', 'احمد سعيد');",
  '    IF actual <> 0 THEN',
  "        RAISE EXCEPTION 'the hamza-less spellings are people again: % rows', actual;",
  '    END IF;',
  '',
  "    SELECT count(*) INTO actual FROM people WHERE name_ar = 'أحمد إسماعيل';",
  '    IF actual <> 1 THEN',
  "        RAISE EXCEPTION 'أحمد إسماعيل appears % times as a person, expected exactly 1', actual;",
  '    END IF;',
  '',
  "    SELECT count(*) INTO actual FROM people WHERE name_ar = 'أحمد سعيد';",
  '    IF actual <> 1 THEN',
  "        RAISE EXCEPTION 'أحمد سعيد appears % times as a person, expected exactly 1', actual;",
  '    END IF;',
  '',
  '    -- ...and each hamza-less spelling must reach that one person through',
  '    -- the alias table. Absent from people AND absent from aliases would',
  '    -- also satisfy the check above, and would lose every row using it.',
  '    SELECT count(*) INTO actual',
  '      FROM person_name_alias a JOIN people p ON p.id = a.person_id',
  "     WHERE a.alias_ar = 'احمد إسماعيل' AND p.name_ar = 'أحمد إسماعيل';",
  '    IF actual <> 1 THEN',
  "        RAISE EXCEPTION 'احمد إسماعيل does not resolve to أحمد إسماعيل';",
  '    END IF;',
  '',
  '    SELECT count(*) INTO actual',
  '      FROM person_name_alias a JOIN people p ON p.id = a.person_id',
  "     WHERE a.alias_ar = 'احمد سعيد' AND p.name_ar = 'أحمد سعيد';",
  '    IF actual <> 1 THEN',
  "        RAISE EXCEPTION 'احمد سعيد does not resolve to أحمد سعيد';",
  '    END IF;',
  '',
  '    -- No spelling may belong to two people. The unique index enforces it;',
  '    -- this says so out loud, because it is the whole point of the table.',
  '    SELECT count(*) INTO actual FROM (',
  '        SELECT alias_ar FROM person_name_alias GROUP BY alias_ar HAVING count(*) > 1',
  '    ) d;',
  '    IF actual <> 0 THEN',
  "        RAISE EXCEPTION '% spellings map to more than one person', actual;",
  '    END IF;',
  '',
  `    RAISE NOTICE 'roster seeded: ${EXPECTED.people} people, ${EXPECTED.aliases} aliases, ${EXPECTED.teams} teams';`,
  'END',
  '$ROSTER$;',
  '',
);

const target = process.argv[2];
if (!target) {
  throw new Error('usage: tsx scripts/generate-roster-seed.ts <path to migration.sql>');
}
const existing = readFileSync(target, 'utf8');

/*
 * REFUSE TO WRITE INTO THE WRONG MIGRATION.
 *
 * This is here because it happened. The caller picked the target with
 * `find prisma/migrations -name migration.sql | sort | tail -1`, assuming the
 * newest folder sorts last. `prisma migrate dev --create-only` had failed, so
 * no new folder existed, and 638 lines of roster seed were appended to an
 * ALREADY-APPLIED migration. Prisma then failed replaying it in the shadow
 * database — INSERT INTO people before people exists — which is the only
 * reason it was noticed.
 *
 * Trusting the shape of an input instead of checking it, again. So check.
 */
if (existing.includes('--  SEED — the people roster')) {
  throw new Error(`${target} already contains a roster seed. Regenerate from a fresh migration.`);
}
if (
  existing.includes('--  SEED — the nine lookup lists') ||
  existing.includes('LOOKUP CORRECTIONS')
) {
  throw new Error(
    `${target} is a different migration — it already holds the lookup seed or the\n` +
      `lookup corrections. This script only ever writes into a NEW, EMPTY migration\n` +
      `created by: npx prisma migrate dev --create-only --name people_roster_and_teams`,
  );
}
if (!existing.includes('CREATE TABLE "people"')) {
  throw new Error(
    `${target} does not create the "people" table, so it is not the roster migration.\n` +
      `Create one first:\n` +
      `  npx prisma migrate dev --create-only --name people_roster_and_teams`,
  );
}
writeFileSync(target, existing.trimEnd() + '\n\n' + out.join('\n'), 'utf8');

console.log(`Roster seed written to ${target}`);
for (const [key, value] of Object.entries(EXPECTED)) {
  console.log(`  ${key.padEnd(22)} ${String(value).padStart(4)}`);
}
