BEGIN;

-- Task 3.3B: append-only, redacted chronological events. The migration starts
-- the trail at deployment with one aggregate baseline event; it never invents
-- a historical event for an existing business row.

DO $PRECONDITION$
DECLARE
    actor_rows bigint;
    null_updates bigint;
BEGIN
    IF session_user IS DISTINCT FROM current_user
       OR NOT coalesce((SELECT rolsuper FROM pg_roles WHERE rolname=session_user),false) THEN
        RAISE EXCEPTION 'Task 3.3B requires D35 direct-superuser migration identity';
    END IF;
    IF to_regclass('public.audit_events') IS NOT NULL
       OR to_regclass('public.audit_event_table_rules') IS NOT NULL
       OR to_regclass('public.audit_event_fields') IS NOT NULL
       OR to_regclass('public.audit_event_checkpoints') IS NOT NULL THEN
        RAISE EXCEPTION 'Task 3.3B requires no pre-existing event foundation';
    END IF;
    SELECT count(*) INTO actor_rows FROM public.audit_actors;
    IF actor_rows<>7 THEN
        RAISE EXCEPTION 'Task 3.3B expected the exact seven-actor registry, found %',actor_rows;
    END IF;
    SELECT count(*) FILTER(WHERE updated_by IS NULL)
      INTO null_updates FROM public.user_accounts;
    -- The complete 38-table totals are re-proved below and permanently by
    -- db:check. This precondition catches an unaccepted Task 3.3A state before
    -- any Task 3.3B object is created.
    IF null_updates<>4 THEN
        RAISE EXCEPTION 'Task 3.3B expected exactly four historical unknown update actors';
    END IF;
    IF NOT (
        ((SELECT count(*) FROM public.invoices)=543
         AND (SELECT count(*) FROM public.payments)=597
         AND (SELECT count(*) FROM public.invoice_allocations)=47
         AND (SELECT count(*) FROM public.attendance)=4022)
        OR
        ((SELECT count(*) FROM public.invoices)=0
         AND (SELECT count(*) FROM public.payments)=0
         AND (SELECT count(*) FROM public.invoice_allocations)=0
         AND (SELECT count(*) FROM public.attendance)=0)
    ) THEN
        RAISE EXCEPTION 'Task 3.3B protected historical-live/clean-replay profile differs';
    END IF;
END
$PRECONDITION$;

CREATE TABLE public.audit_event_table_rules (
    entity_schema text NOT NULL,
    entity_table text NOT NULL,
    entity_kind text NOT NULL,
    key_fields text[] NOT NULL,
    CONSTRAINT audit_event_table_rules_pkey PRIMARY KEY(entity_schema,entity_table),
    CONSTRAINT audit_event_table_rules_schema_shape CHECK (entity_schema='public'),
    CONSTRAINT audit_event_table_rules_table_shape CHECK (
        entity_table ~ '^[a-z][a-z0-9_]{0,62}$'),
    CONSTRAINT audit_event_table_rules_kind_shape CHECK (
        entity_kind IN ('record','relationship')),
    CONSTRAINT audit_event_table_rules_key_shape CHECK (key_fields=ARRAY['id']::text[])
);

CREATE TABLE public.audit_event_fields (
    entity_schema text NOT NULL,
    entity_table text NOT NULL,
    field_name text NOT NULL,
    max_text_characters smallint NOT NULL DEFAULT 1024,
    capture_mode text NOT NULL DEFAULT 'value',
    CONSTRAINT audit_event_fields_pkey PRIMARY KEY(entity_schema,entity_table,field_name),
    CONSTRAINT audit_event_fields_table_fkey
        FOREIGN KEY(entity_schema,entity_table)
        REFERENCES public.audit_event_table_rules(entity_schema,entity_table)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT audit_event_fields_name_shape CHECK (
        field_name ~ '^[a-z][a-z0-9_]{0,62}$'),
    CONSTRAINT audit_event_fields_bound CHECK (
        max_text_characters BETWEEN 64 AND 2048),
    CONSTRAINT audit_event_fields_capture_mode CHECK (
        capture_mode IN ('value','redacted'))
);

CREATE TABLE public.audit_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    event_version smallint NOT NULL DEFAULT 1,
    occurred_at timestamptz(6) NOT NULL DEFAULT statement_timestamp(),
    actor_id integer NOT NULL,
    actor_key_snapshot text NOT NULL,
    actor_username_snapshot text,
    actor_display_name_snapshot text NOT NULL,
    actor_role_snapshot text,
    target_actor_id integer,
    target_actor_key_snapshot text,
    target_username_snapshot text,
    target_display_name_snapshot text,
    target_role_snapshot text,
    action text NOT NULL,
    outcome text NOT NULL,
    entity_schema text,
    entity_table text,
    entity_key jsonb,
    changed_fields text[] NOT NULL DEFAULT ARRAY[]::text[],
    before_values jsonb NOT NULL DEFAULT '{}'::jsonb,
    after_values jsonb NOT NULL DEFAULT '{}'::jsonb,
    request_id uuid NOT NULL,
    correlation_id uuid NOT NULL,
    audit_session_id uuid NOT NULL,
    ip_address inet,
    user_agent varchar(512),
    user_agent_truncated boolean NOT NULL DEFAULT false,
    device_class varchar(32) NOT NULL,
    attempted_username varchar(64),
    attempted_username_truncated boolean NOT NULL DEFAULT false,
    resource_identifier varchar(256),
    reason_code varchar(64),
    parameters jsonb NOT NULL DEFAULT '{}'::jsonb,
    event_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT audit_events_pkey PRIMARY KEY(id),
    CONSTRAINT audit_events_actor_fkey FOREIGN KEY(actor_id)
        REFERENCES public.audit_actors(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT audit_events_target_actor_fkey FOREIGN KEY(target_actor_id)
        REFERENCES public.audit_actors(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT audit_events_version_shape CHECK (event_version=1),
    CONSTRAINT audit_events_action_shape CHECK (action IN (
        'record_created','record_updated',
        'relationship_added','relationship_updated','relationship_removed',
        'login_succeeded','login_failed','account_locked',
        'password_changed','password_initialized','password_reset',
        'archive','restore','account_created','account_enabled','account_disabled',
        'role_changed','report_executed','export_completed','download_completed',
        'audit_baseline_established'
    )),
    CONSTRAINT audit_events_outcome_shape CHECK (outcome IN ('succeeded','failed','blocked')),
    CONSTRAINT audit_events_actor_snapshot_shape CHECK (
        actor_key_snapshot=btrim(actor_key_snapshot) AND actor_key_snapshot<>''
        AND actor_display_name_snapshot=btrim(actor_display_name_snapshot)
        AND actor_display_name_snapshot<>''
        AND (actor_username_snapshot IS NULL OR
             (actor_username_snapshot=btrim(actor_username_snapshot)
              AND actor_username_snapshot<>'' AND char_length(actor_username_snapshot)<=64))
        AND (actor_role_snapshot IS NULL OR actor_role_snapshot IN
             ('Administrator','Litigation Assistant','Lawyer','Paralegal'))
    ),
    CONSTRAINT audit_events_target_snapshot_shape CHECK ((
        target_actor_id IS NULL AND target_actor_key_snapshot IS NULL
        AND target_username_snapshot IS NULL AND target_display_name_snapshot IS NULL
        AND target_role_snapshot IS NULL
    ) OR (
        target_actor_id IS NOT NULL AND target_actor_key_snapshot IS NOT NULL
        AND target_display_name_snapshot IS NOT NULL
        AND (target_role_snapshot IS NULL OR target_role_snapshot IN
             ('Administrator','Litigation Assistant','Lawyer','Paralegal'))
    )),
    CONSTRAINT audit_events_entity_shape CHECK ((
        entity_schema IS NULL AND entity_table IS NULL AND entity_key IS NULL
    ) OR (
        entity_schema IS NOT NULL AND entity_table IS NOT NULL AND entity_key IS NOT NULL
        AND entity_schema ~ '^[a-z][a-z0-9_]{0,62}$'
        AND entity_table ~ '^[a-z][a-z0-9_]{0,62}$'
        AND jsonb_typeof(entity_key)='object'
        AND octet_length(entity_key::text)<=2048
    )),
    CONSTRAINT audit_events_change_shape CHECK (
        cardinality(changed_fields)<=64
        AND jsonb_typeof(before_values)='object'
        AND jsonb_typeof(after_values)='object'
        AND octet_length(before_values::text)<=65536
        AND octet_length(after_values::text)<=65536
    ),
    CONSTRAINT audit_events_request_shape CHECK (
        request_id<>'00000000-0000-0000-0000-000000000000'::uuid
        AND correlation_id<>'00000000-0000-0000-0000-000000000000'::uuid
        AND audit_session_id<>'00000000-0000-0000-0000-000000000000'::uuid
    ),
    CONSTRAINT audit_events_device_shape CHECK (
        device_class IN ('system','desktop','mobile','tablet','bot','unknown')),
    CONSTRAINT audit_events_metadata_shape CHECK (
        jsonb_typeof(parameters)='object' AND jsonb_typeof(event_metadata)='object'
        AND octet_length(parameters::text)<=16384
        AND octet_length(event_metadata::text)<=16384),
    CONSTRAINT audit_events_attempt_shape CHECK (
        attempted_username IS NULL OR attempted_username<>''),
    CONSTRAINT audit_events_resource_shape CHECK (
        resource_identifier IS NULL OR resource_identifier<>''),
    CONSTRAINT audit_events_reason_shape CHECK (
        reason_code IS NULL OR reason_code ~ '^[a-z][a-z0-9_]{0,63}$')
);

CREATE TABLE public.audit_event_checkpoints (
    checkpoint_key text NOT NULL,
    migration_name text NOT NULL,
    baseline_profile text NOT NULL,
    event_count bigint NOT NULL,
    first_event_id bigint NOT NULL,
    through_event_id bigint NOT NULL,
    event_digest char(64) NOT NULL,
    allowlist_digest char(64) NOT NULL,
    created_at timestamptz(6) NOT NULL DEFAULT statement_timestamp(),
    CONSTRAINT audit_event_checkpoints_pkey PRIMARY KEY(checkpoint_key),
    CONSTRAINT audit_event_checkpoints_event_first_fkey FOREIGN KEY(first_event_id)
        REFERENCES public.audit_events(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT audit_event_checkpoints_event_through_fkey FOREIGN KEY(through_event_id)
        REFERENCES public.audit_events(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT audit_event_checkpoints_key_shape CHECK (
        checkpoint_key='task_3_3b_baseline'),
    CONSTRAINT audit_event_checkpoints_migration_shape CHECK (
        migration_name='20260902180000_append_only_audit_events'),
    CONSTRAINT audit_event_checkpoints_profile_shape CHECK (
        baseline_profile IN ('historical-live','canonical-clean-replay')),
    CONSTRAINT audit_event_checkpoints_count_shape CHECK (
        event_count=1 AND first_event_id=through_event_id),
    CONSTRAINT audit_event_checkpoints_digest_shape CHECK (
        event_digest ~ '^[0-9a-f]{64}$' AND allowlist_digest ~ '^[0-9a-f]{64}$')
);

INSERT INTO public.audit_event_table_rules(entity_schema,entity_table,entity_kind,key_fields)
VALUES
('public','admin_tasks','record',ARRAY['id']),
('public','attendance','record',ARRAY['id']),
('public','client_logos','record',ARRAY['id']),
('public','clients','record',ARRAY['id']),
('public','contacts','record',ARRAY['id']),
('public','documents','record',ARRAY['id']),
('public','fee_letter_matters','relationship',ARRAY['id']),
('public','fee_letters','record',ARRAY['id']),
('public','hearing_attendees','relationship',ARRAY['id']),
('public','hearings','record',ARRAY['id']),
('public','invoice_allocations','relationship',ARRAY['id']),
('public','invoices','record',ARRAY['id']),
('public','lookup_client_branch','record',ARRAY['id']),
('public','lookup_court','record',ARRAY['id']),
('public','lookup_degree','record',ARRAY['id']),
('public','lookup_hearing_action','record',ARRAY['id']),
('public','lookup_importance','record',ARRAY['id']),
('public','lookup_invoice_status','record',ARRAY['id']),
('public','lookup_invoice_type','record',ARRAY['id']),
('public','lookup_lawyer_share_role','record',ARRAY['id']),
('public','lookup_matter_category','record',ARRAY['id']),
('public','lookup_matter_destination','record',ARRAY['id']),
('public','lookup_matter_type','record',ARRAY['id']),
('public','lookup_party_role','record',ARRAY['id']),
('public','lookup_team','record',ARRAY['id']),
('public','lookup_venue','record',ARRAY['id']),
('public','matter_fee_letter_references','relationship',ARRAY['id']),
('public','matter_lawyers','relationship',ARRAY['id']),
('public','matter_parties','relationship',ARRAY['id']),
('public','matter_party_roles','relationship',ARRAY['id']),
('public','matters','record',ARRAY['id']),
('public','payments','record',ARRAY['id']),
('public','people','record',ARRAY['id']),
('public','person_name_alias','record',ARRAY['id']),
('public','power_of_attorney_lawyers','relationship',ARRAY['id']),
('public','powers_of_attorney','record',ARRAY['id']),
('public','task_actions','record',ARRAY['id']),
('public','user_accounts','record',ARRAY['id']);

WITH field_sets(entity_table,fields) AS (VALUES
('admin_tasks',ARRAY['matter_id','required_work','assigned_to_person_id','task_created_date','execution_date','result','previous_decision','last_followup','deadline','court_id','circuit','destination_id','status','alert']),
('attendance',ARRAY['person_id','attendance_date','situation']),
('client_logos',ARRAY['client_id','relative_path','file_name','content_type','byte_size','sha256']),
('clients',ARRAY['name_ar','name_en','full_name','branch_id','cash_or_probono','status','poa_location','documents_location','client_start','client_end','contact_person_id']),
('contacts',ARRAY['client_id','address','business_phone','city','contact_name','country_region','email','fax_number','full_name','home_phone','job_title','mobile_phone','state_province','web_page','zip_postal_code']),
('documents',ARRAY['matter_id','description','page_count','deposit_date','responsible_person_id','movement_card','storage_location','mfiles_id','client_id','document_date','notes']),
('fee_letter_matters',ARRAY['fee_letter_id','matter_id','ordinal']),
('fee_letters',ARRAY['contract_id','client_id','mfiles_id','client_name','contract_date','contract_details','contract_structure','contract_type','status']),
('hearing_attendees',ARRAY['hearing_id','person_id','ordinal']),
('hearings',ARRAY['matter_id','hearing_date','next_hearing_date','action_id','decision','outcome','court_id','circuit','client_notified','report','previous_decision','destination_id','notes','short_decision']),
('invoice_allocations',ARRAY['invoice_id','person_id','share','lawyer_role_id']),
('invoices',ARRAY['invoice_no','currency','amount','invoice_date','amount_usd','details','fee_letter_id','receipt_amount','status_id','type_id','receipt_currency','report','vat']),
('lookup_client_branch',ARRAY['label_ar','label_en','sort_order','is_active']),
('lookup_court',ARRAY['label_ar','label_en','sort_order','is_active']),
('lookup_degree',ARRAY['label_ar','label_en','sort_order','is_active']),
('lookup_hearing_action',ARRAY['label_ar','label_en','sort_order','is_active']),
('lookup_importance',ARRAY['label_ar','label_en','sort_order','is_active']),
('lookup_invoice_status',ARRAY['code','label_ar','sort_order','is_active']),
('lookup_invoice_type',ARRAY['code','label_ar','sort_order','is_active']),
('lookup_lawyer_share_role',ARRAY['code','label_ar','sort_order','is_active']),
('lookup_matter_category',ARRAY['label_ar','label_en','sort_order','is_active']),
('lookup_matter_destination',ARRAY['label_ar','label_en','sort_order','is_active']),
('lookup_matter_type',ARRAY['label_ar','label_en','sort_order','is_active','is_default']),
('lookup_party_role',ARRAY['code','label_ar_m','label_ar_f','label_en','sort_order','is_active']),
('lookup_team',ARRAY['code','label_ar','specialisms','reviewer_id','sort_order','is_active']),
('lookup_venue',ARRAY['label_ar','label_en','sort_order','is_active']),
('matter_fee_letter_references',ARRAY['matter_id','fee_letter_id','identifier_space']),
('matter_lawyers',ARRAY['matter_id','person_id','role','position']),
('matter_parties',ARRAY['matter_id','side','party_name','gender','ordinal']),
('matter_party_roles',ARRAY['party_id','role_id','ordinal']),
('matters',ARRAY['case_number_ar','subject','client_id','matter_type_id','matter_category_id','degree_id','venue_id','importance_id','destination_id','status','court_id','circuit','court_floor','court_hall','court_shelf','court_secretary_room','fee_letter_ref','case_number_en','branch_id','notes_1','notes_2','start_date','end_date','circuit_secretary','asked_amount','judged_amount','evaluation','current_status','legal_opinion']),
('payments',ARRAY['invoice_id','currency','payment_date','credit','debit','details']),
('people',ARRAY['name_ar','name_en','email','is_staff','is_active','is_trainee','can_login','team_id','is_application_native']),
('person_name_alias',ARRAY['person_id','alias_ar','is_primary']),
('power_of_attorney_lawyers',ARRAY['power_of_attorney_id','person_id']),
('powers_of_attorney',ARRAY['client_id','client_name','copies_count','issue_date','issuing_authority','notes','poa_letter','poa_number','poa_year','principal_name','serial_no','poa_capacity','poa_capacity_duplicate','show_on_poa_report']),
('task_actions',ARRAY['task_id','action_date','next_appointment','performed_by_person_id','report','result']),
('user_accounts',ARRAY['person_id','username','role_code','is_enabled','must_change_password','failed_login_attempts','locked_until','session_version','password_changed_at','last_login_at'])
)
INSERT INTO public.audit_event_fields(entity_schema,entity_table,field_name)
SELECT 'public',field_sets.entity_table,field_name
  FROM field_sets CROSS JOIN LATERAL unnest(field_sets.fields) AS field_name;

INSERT INTO public.audit_event_fields(
    entity_schema,entity_table,field_name,max_text_characters,capture_mode
) VALUES ('public','user_accounts','password_hash',1024,'redacted');

CREATE FUNCTION public.refuse_audit_event_change()
RETURNS trigger
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $IMMUTABLE$
BEGIN
    RAISE EXCEPTION USING ERRCODE='55000',
        MESSAGE='Audit events, rules and checkpoints are append-only and immutable';
END;
$IMMUTABLE$;

CREATE FUNCTION public.audit_contains_secret_pattern(p_value text)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
SET search_path = pg_catalog, public, pg_temp
RETURN p_value ~* '(auth_secret|database_url|connection[_ -]?string|password|passwd|bearer[[:space:]]|authorization|cookie|private[_ -]?key|api[_ -]?key|postgres(?:ql)?://|-----begin [a-z ]*private key-----|\$argon2(?:id|i|d)\$)';

CREATE FUNCTION public.audit_bound_json_value(
    p_value jsonb,
    p_max_characters integer,
    p_capture_mode text
)
RETURNS jsonb
LANGUAGE plpgsql
IMMUTABLE
PARALLEL SAFE
SET search_path = pg_catalog, public, pg_temp
AS $BOUND_VALUE$
DECLARE
    text_value text;
BEGIN
    IF p_capture_mode='redacted' THEN
        RETURN jsonb_build_object('$redacted',true,'$reason','sensitive_field');
    END IF;
    IF p_capture_mode<>'value' THEN
        RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='Unknown audit capture mode';
    END IF;
    IF p_value IS NULL OR jsonb_typeof(p_value)='null' THEN
        RETURN 'null'::jsonb;
    END IF;
    IF jsonb_typeof(p_value) IN ('object','array') THEN
        RETURN jsonb_build_object('$redacted',true,'$reason','structured_value');
    END IF;
    IF jsonb_typeof(p_value)<>'string' THEN
        RETURN p_value;
    END IF;
    text_value := p_value #>> '{}';
    IF public.audit_contains_secret_pattern(text_value) THEN
        RETURN jsonb_build_object('$redacted',true,'$reason','secret_pattern');
    END IF;
    IF char_length(text_value)>p_max_characters THEN
        RETURN jsonb_build_object(
            '$value',left(text_value,p_max_characters),
            '$truncated',true,
            '$original_characters',char_length(text_value)
        );
    END IF;
    RETURN p_value;
END;
$BOUND_VALUE$;

CREATE FUNCTION public.audit_safe_flat_object(p_value jsonb)
RETURNS boolean
LANGUAGE plpgsql
IMMUTABLE
PARALLEL SAFE
SET search_path = pg_catalog, public, pg_temp
AS $SAFE_OBJECT$
DECLARE
    item record;
    item_count integer := 0;
    text_value text;
BEGIN
    IF p_value IS NULL OR jsonb_typeof(p_value)<>'object' OR octet_length(p_value::text)>16384 THEN
        RETURN false;
    END IF;
    FOR item IN SELECT key,value FROM jsonb_each(p_value) LOOP
        item_count := item_count+1;
        IF item_count>32
           OR item.key !~ '^[a-z][a-z0-9_]{0,63}$'
           OR item.key ~* '(password|token|cookie|secret|credential|authorization|private_key|api_key|database_url|connection_string|payload|binary|content)' THEN
            RETURN false;
        END IF;
        IF jsonb_typeof(item.value) NOT IN ('string','number','boolean','null') THEN
            RETURN false;
        END IF;
        IF jsonb_typeof(item.value)='string' THEN
            text_value := item.value #>> '{}';
            IF char_length(text_value)>256 OR public.audit_contains_secret_pattern(text_value) THEN
                RETURN false;
            END IF;
        END IF;
    END LOOP;
    RETURN true;
END;
$SAFE_OBJECT$;

CREATE FUNCTION public.audit_set_event_context(
    p_request_id uuid,
    p_correlation_id uuid,
    p_audit_session_id uuid,
    p_ip_address inet,
    p_user_agent text,
    p_device_class text
)
RETURNS void
LANGUAGE plpgsql
VOLATILE
CALLED ON NULL INPUT
SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $SET_CONTEXT$
DECLARE
    safe_agent text;
    agent_truncated boolean;
BEGIN
    IF p_request_id IS NULL OR p_correlation_id IS NULL OR p_audit_session_id IS NULL
       OR p_request_id='00000000-0000-0000-0000-000000000000'::uuid
       OR p_correlation_id='00000000-0000-0000-0000-000000000000'::uuid
       OR p_audit_session_id='00000000-0000-0000-0000-000000000000'::uuid
       OR p_device_class NOT IN ('system','desktop','mobile','tablet','bot','unknown') THEN
        RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='Invalid server audit event context';
    END IF;
    agent_truncated := p_user_agent IS NOT NULL AND char_length(p_user_agent)>512;
    safe_agent := CASE
        WHEN p_user_agent IS NULL OR p_user_agent='' THEN ''
        WHEN public.audit_contains_secret_pattern(p_user_agent) THEN '[redacted]'
        ELSE left(p_user_agent,512)
    END;
    IF safe_agent='[redacted]' THEN agent_truncated := true; END IF;
    PERFORM set_config('litigation.audit_request_id',p_request_id::text,true);
    PERFORM set_config('litigation.audit_correlation_id',p_correlation_id::text,true);
    PERFORM set_config('litigation.audit_session_id',p_audit_session_id::text,true);
    PERFORM set_config('litigation.audit_ip_address',coalesce(p_ip_address::text,''),true);
    PERFORM set_config('litigation.audit_user_agent',safe_agent,true);
    PERFORM set_config('litigation.audit_user_agent_truncated',agent_truncated::text,true);
    PERFORM set_config('litigation.audit_device_class',p_device_class,true);
END;
$SET_CONTEXT$;

CREATE FUNCTION public.audit_ensure_event_context()
RETURNS jsonb
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $ENSURE_CONTEXT$
DECLARE
    request_value text := current_setting('litigation.audit_request_id',true);
    correlation_value text := current_setting('litigation.audit_correlation_id',true);
    session_value text := current_setting('litigation.audit_session_id',true);
    ip_value text := current_setting('litigation.audit_ip_address',true);
    agent_value text := current_setting('litigation.audit_user_agent',true);
    truncated_value text := current_setting('litigation.audit_user_agent_truncated',true);
    device_value text := current_setting('litigation.audit_device_class',true);
BEGIN
    IF coalesce(request_value,'')='' THEN
        IF coalesce(correlation_value,'')<>'' OR coalesce(session_value,'')<>'' THEN
            RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Partial audit event context is refused';
        END IF;
        request_value := gen_random_uuid()::text;
        correlation_value := gen_random_uuid()::text;
        session_value := gen_random_uuid()::text;
        ip_value := '';
        agent_value := '';
        truncated_value := 'false';
        device_value := CASE WHEN public.audit_current_actor_id()=1 THEN 'system' ELSE 'unknown' END;
        PERFORM set_config('litigation.audit_request_id',request_value,true);
        PERFORM set_config('litigation.audit_correlation_id',correlation_value,true);
        PERFORM set_config('litigation.audit_session_id',session_value,true);
        PERFORM set_config('litigation.audit_ip_address','',true);
        PERFORM set_config('litigation.audit_user_agent','',true);
        PERFORM set_config('litigation.audit_user_agent_truncated','false',true);
        PERFORM set_config('litigation.audit_device_class',device_value,true);
    END IF;
    BEGIN
        PERFORM request_value::uuid,correlation_value::uuid,session_value::uuid;
        IF coalesce(ip_value,'')<>'' THEN PERFORM ip_value::inet; END IF;
        IF coalesce(truncated_value,'') NOT IN ('true','false')
           OR coalesce(device_value,'') NOT IN ('system','desktop','mobile','tablet','bot','unknown')
           OR char_length(coalesce(agent_value,''))>512 THEN
            RAISE invalid_parameter_value;
        END IF;
    EXCEPTION WHEN OTHERS THEN
        RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Invalid transaction-local audit event context';
    END;
    RETURN jsonb_build_object(
        'request_id',request_value,
        'correlation_id',correlation_value,
        'audit_session_id',session_value,
        'ip_address',nullif(ip_value,''),
        'user_agent',nullif(agent_value,''),
        'user_agent_truncated',truncated_value::boolean,
        'device_class',device_value
    );
END;
$ENSURE_CONTEXT$;

CREATE FUNCTION public.audit_write_event(
    p_action text,
    p_outcome text,
    p_entity_schema text,
    p_entity_table text,
    p_entity_key jsonb,
    p_changed_fields text[],
    p_before_values jsonb,
    p_after_values jsonb,
    p_target_actor_id integer,
    p_attempted_username text,
    p_resource_identifier text,
    p_parameters jsonb,
    p_reason_code text,
    p_event_metadata jsonb
)
RETURNS bigint
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $WRITE_EVENT$
DECLARE
    current_actor_id integer := public.audit_current_actor_id();
    context_value jsonb := public.audit_ensure_event_context();
    actor_row record;
    target_actor_key text;
    target_username text;
    target_display_name text;
    target_role text;
    safe_attempt text;
    safe_attempt_truncated boolean := false;
    new_event_id bigint;
BEGIN
    SELECT a.actor_key,a.actor_kind,u.username,p.name_ar,u.role_code,a.identity_label
      INTO STRICT actor_row
      FROM public.audit_actors a
      LEFT JOIN public.user_accounts u ON u.id=a.user_account_id
      LEFT JOIN public.people p ON p.id=u.person_id
     WHERE a.id=current_actor_id;
    IF p_target_actor_id IS NOT NULL THEN
        SELECT a.actor_key,u.username,coalesce(p.name_ar,a.identity_label),u.role_code
          INTO STRICT target_actor_key,target_username,target_display_name,target_role
          FROM public.audit_actors a
          LEFT JOIN public.user_accounts u ON u.id=a.user_account_id
          LEFT JOIN public.people p ON p.id=u.person_id
         WHERE a.id=p_target_actor_id;
    END IF;
    IF p_attempted_username IS NOT NULL AND p_attempted_username<>'' THEN
        safe_attempt_truncated := char_length(p_attempted_username)>64;
        safe_attempt := CASE
            WHEN public.audit_contains_secret_pattern(p_attempted_username) THEN '[redacted]'
            ELSE left(p_attempted_username,64)
        END;
        IF safe_attempt='[redacted]' THEN safe_attempt_truncated := true; END IF;
    END IF;
    INSERT INTO public.audit_events(
        actor_id,actor_key_snapshot,actor_username_snapshot,
        actor_display_name_snapshot,actor_role_snapshot,
        target_actor_id,target_actor_key_snapshot,target_username_snapshot,
        target_display_name_snapshot,target_role_snapshot,
        action,outcome,entity_schema,entity_table,entity_key,changed_fields,
        before_values,after_values,request_id,correlation_id,audit_session_id,
        ip_address,user_agent,user_agent_truncated,device_class,
        attempted_username,attempted_username_truncated,resource_identifier,
        reason_code,parameters,event_metadata
    ) VALUES (
        current_actor_id,actor_row.actor_key,actor_row.username,
        coalesce(actor_row.name_ar,actor_row.identity_label),actor_row.role_code,
        p_target_actor_id,target_actor_key,target_username,target_display_name,target_role,
        p_action,p_outcome,p_entity_schema,p_entity_table,p_entity_key,
        coalesce(p_changed_fields,ARRAY[]::text[]),
        coalesce(p_before_values,'{}'::jsonb),coalesce(p_after_values,'{}'::jsonb),
        (context_value->>'request_id')::uuid,
        (context_value->>'correlation_id')::uuid,
        (context_value->>'audit_session_id')::uuid,
        nullif(context_value->>'ip_address','')::inet,
        nullif(context_value->>'user_agent',''),
        (context_value->>'user_agent_truncated')::boolean,
        context_value->>'device_class',safe_attempt,safe_attempt_truncated,
        nullif(left(coalesce(p_resource_identifier,''),256),''),
        p_reason_code,coalesce(p_parameters,'{}'::jsonb),coalesce(p_event_metadata,'{}'::jsonb)
    ) RETURNING id INTO new_event_id;
    RETURN new_event_id;
END;
$WRITE_EVENT$;

CREATE FUNCTION public.audit_append_semantic_event(
    p_action text,
    p_outcome text,
    p_entity_schema text,
    p_entity_table text,
    p_entity_key jsonb,
    p_target_actor_id integer,
    p_attempted_username text,
    p_resource_identifier text,
    p_parameters jsonb,
    p_reason_code text,
    p_event_metadata jsonb
)
RETURNS bigint
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $SEMANTIC_EVENT$
DECLARE
    current_actor_id integer := public.audit_current_actor_id();
    current_kind text;
    current_key text;
    current_user_account_id integer;
    target_kind text;
    target_user_account_id integer;
BEGIN
    SELECT actor_kind,actor_key,user_account_id
      INTO STRICT current_kind,current_key,current_user_account_id
      FROM public.audit_actors WHERE id=current_actor_id;
    IF p_target_actor_id IS NOT NULL THEN
        SELECT actor_kind,user_account_id INTO STRICT target_kind,target_user_account_id
          FROM public.audit_actors WHERE id=p_target_actor_id;
        IF target_kind<>'human' OR target_user_account_id IS NULL THEN
            RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Semantic target must be a human account actor';
        END IF;
    END IF;
    IF p_action NOT IN (
        'login_succeeded','login_failed','account_locked',
        'password_changed','password_initialized','password_reset',
        'archive','restore','account_created','account_enabled','account_disabled',
        'role_changed','report_executed','export_completed','download_completed'
    ) THEN
        RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='Unsupported semantic audit action';
    END IF;
    IF p_outcome NOT IN ('succeeded','failed','blocked')
       OR NOT public.audit_safe_flat_object(coalesce(p_parameters,'{}'::jsonb))
       OR NOT public.audit_safe_flat_object(coalesce(p_event_metadata,'{}'::jsonb))
       OR (p_reason_code IS NOT NULL AND p_reason_code !~ '^[a-z][a-z0-9_]{0,63}$') THEN
        RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='Unsafe semantic audit payload';
    END IF;
    IF p_resource_identifier IS NOT NULL AND (
        p_resource_identifier='' OR char_length(p_resource_identifier)>256
        OR public.audit_contains_secret_pattern(p_resource_identifier)
    ) THEN
        RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='Unsafe semantic resource identifier';
    END IF;
    IF (p_entity_schema IS NULL) IS DISTINCT FROM (p_entity_table IS NULL)
       OR (p_entity_schema IS NULL) IS DISTINCT FROM (p_entity_key IS NULL)
       OR (p_entity_key IS NOT NULL AND
           (p_entity_schema<>'public'
            OR NOT EXISTS (
                SELECT 1 FROM public.audit_event_table_rules r
                 WHERE r.entity_schema=p_entity_schema AND r.entity_table=p_entity_table
            )
            OR NOT public.audit_safe_flat_object(p_entity_key)
            OR octet_length(p_entity_key::text)>2048)) THEN
        RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='Invalid semantic audit entity';
    END IF;
    IF p_action='login_succeeded' THEN
        IF current_kind<>'human' OR p_outcome<>'succeeded'
           OR p_target_actor_id IS NOT NULL OR p_attempted_username IS NOT NULL
           OR p_entity_table<>'user_accounts'
           OR p_entity_key IS DISTINCT FROM jsonb_build_object('id',current_user_account_id) THEN
            RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Login-success actor or shape is invalid';
        END IF;
    ELSIF p_action='login_failed' THEN
        IF current_key<>'system_authentication' OR p_outcome NOT IN ('failed','blocked')
           OR coalesce(p_attempted_username,'')=''
           OR (p_target_actor_id IS NULL AND p_entity_key IS NOT NULL)
           OR (p_target_actor_id IS NOT NULL AND (
               p_entity_table<>'user_accounts'
               OR p_entity_key IS DISTINCT FROM jsonb_build_object('id',target_user_account_id)
           )) THEN
            RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Login-failure actor or shape is invalid';
        END IF;
    ELSIF p_action='account_locked' THEN
        IF current_key<>'system_authentication' OR p_outcome<>'succeeded'
           OR p_target_actor_id IS NULL OR p_entity_table<>'user_accounts'
           OR p_entity_key IS DISTINCT FROM jsonb_build_object('id',target_user_account_id) THEN
            RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Lockout actor or shape is invalid';
        END IF;
    ELSIF p_action='password_changed' THEN
        IF current_kind<>'human' OR p_outcome<>'succeeded'
           OR p_target_actor_id IS DISTINCT FROM current_actor_id
           OR p_entity_table<>'user_accounts'
           OR p_entity_key IS DISTINCT FROM jsonb_build_object('id',current_user_account_id) THEN
            RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Self-password actor or shape is invalid';
        END IF;
    ELSIF p_action IN ('password_initialized','password_reset') THEN
        IF current_key<>'system_administration' OR p_outcome<>'succeeded'
           OR p_target_actor_id IS NULL OR p_entity_table<>'user_accounts'
           OR p_entity_key IS DISTINCT FROM jsonb_build_object('id',target_user_account_id) THEN
            RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Administrative password actor or shape is invalid';
        END IF;
    ELSIF p_action IN ('archive','restore','account_created','account_enabled','account_disabled','role_changed') THEN
        IF current_kind<>'human' OR p_outcome<>'succeeded' OR p_entity_key IS NULL THEN
            RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Lifecycle actor or shape is invalid';
        END IF;
    ELSIF p_action IN ('report_executed','export_completed','download_completed') THEN
        IF current_kind<>'human' OR coalesce(p_resource_identifier,'')='' THEN
            RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Report/export/download actor or shape is invalid';
        END IF;
    END IF;
    RETURN public.audit_write_event(
        p_action,p_outcome,p_entity_schema,p_entity_table,p_entity_key,
        ARRAY[]::text[],'{}'::jsonb,'{}'::jsonb,p_target_actor_id,
        p_attempted_username,p_resource_identifier,p_parameters,p_reason_code,p_event_metadata
    );
END;
$SEMANTIC_EVENT$;

CREATE FUNCTION public.audit_capture_row_event()
RETURNS trigger
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $ROW_EVENT$
DECLARE
    table_rule public.audit_event_table_rules%ROWTYPE;
    old_value jsonb;
    new_value jsonb;
    key_source jsonb;
    entity_key jsonb;
    fields text[];
    before_payload jsonb := '{}'::jsonb;
    after_payload jsonb := '{}'::jsonb;
    action_name text;
BEGIN
    SELECT * INTO STRICT table_rule
      FROM public.audit_event_table_rules
     WHERE entity_schema=TG_TABLE_SCHEMA AND entity_table=TG_TABLE_NAME;
    old_value := CASE WHEN TG_OP='INSERT' THEN NULL ELSE to_jsonb(OLD) END;
    new_value := CASE WHEN TG_OP='DELETE' THEN NULL ELSE to_jsonb(NEW) END;
    key_source := coalesce(new_value,old_value);
    SELECT jsonb_object_agg(key_name,key_source->key_name ORDER BY ordinal)
      INTO entity_key
      FROM unnest(table_rule.key_fields) WITH ORDINALITY AS keys(key_name,ordinal);

    IF TG_OP='INSERT' THEN
        SELECT array_agg(f.field_name ORDER BY f.field_name),
               jsonb_object_agg(
                   f.field_name,
                    public.audit_bound_json_value(
                        new_value->f.field_name,f.max_text_characters,f.capture_mode)
                   ORDER BY f.field_name)
          INTO fields,after_payload
          FROM public.audit_event_fields f
         WHERE f.entity_schema=TG_TABLE_SCHEMA AND f.entity_table=TG_TABLE_NAME;
        action_name := CASE WHEN table_rule.entity_kind='relationship'
                            THEN 'relationship_added' ELSE 'record_created' END;
    ELSIF TG_OP='UPDATE' THEN
        SELECT array_agg(f.field_name ORDER BY f.field_name),
               coalesce(jsonb_object_agg(
                   f.field_name,
                    public.audit_bound_json_value(
                        old_value->f.field_name,f.max_text_characters,f.capture_mode)
                   ORDER BY f.field_name),'{}'::jsonb),
               coalesce(jsonb_object_agg(
                   f.field_name,
                    public.audit_bound_json_value(
                        new_value->f.field_name,f.max_text_characters,f.capture_mode)
                   ORDER BY f.field_name),'{}'::jsonb)
          INTO fields,before_payload,after_payload
          FROM public.audit_event_fields f
         WHERE f.entity_schema=TG_TABLE_SCHEMA AND f.entity_table=TG_TABLE_NAME
           AND (old_value->f.field_name) IS DISTINCT FROM (new_value->f.field_name);
        IF fields IS NULL OR cardinality(fields)=0 THEN RETURN NEW; END IF;
        action_name := CASE WHEN table_rule.entity_kind='relationship'
                            THEN 'relationship_updated' ELSE 'record_updated' END;
    ELSE
        IF table_rule.entity_kind<>'relationship' THEN
            RAISE EXCEPTION 'Physical record deletion is outside the Task 3.3B/D25 contract';
        END IF;
        SELECT array_agg(f.field_name ORDER BY f.field_name),
               jsonb_object_agg(
                   f.field_name,
                    public.audit_bound_json_value(
                        old_value->f.field_name,f.max_text_characters,f.capture_mode)
                   ORDER BY f.field_name)
          INTO fields,before_payload
          FROM public.audit_event_fields f
         WHERE f.entity_schema=TG_TABLE_SCHEMA AND f.entity_table=TG_TABLE_NAME;
        action_name := 'relationship_removed';
    END IF;
    PERFORM public.audit_write_event(
        action_name,'succeeded',TG_TABLE_SCHEMA,TG_TABLE_NAME,entity_key,
        fields,before_payload,after_payload,NULL,NULL,NULL,'{}'::jsonb,NULL,'{}'::jsonb
    );
    RETURN CASE WHEN TG_OP='DELETE' THEN OLD ELSE NEW END;
END;
$ROW_EVENT$;

CREATE TRIGGER audit_events_no_change
BEFORE UPDATE OR DELETE ON public.audit_events
FOR EACH ROW EXECUTE FUNCTION public.refuse_audit_event_change();
CREATE TRIGGER audit_events_no_truncate
BEFORE TRUNCATE ON public.audit_events
FOR EACH STATEMENT EXECUTE FUNCTION public.refuse_audit_event_change();
CREATE TRIGGER audit_event_table_rules_no_change
BEFORE UPDATE OR DELETE ON public.audit_event_table_rules
FOR EACH ROW EXECUTE FUNCTION public.refuse_audit_event_change();
CREATE TRIGGER audit_event_table_rules_no_truncate
BEFORE TRUNCATE ON public.audit_event_table_rules
FOR EACH STATEMENT EXECUTE FUNCTION public.refuse_audit_event_change();
CREATE TRIGGER audit_event_fields_no_change
BEFORE UPDATE OR DELETE ON public.audit_event_fields
FOR EACH ROW EXECUTE FUNCTION public.refuse_audit_event_change();
CREATE TRIGGER audit_event_fields_no_truncate
BEFORE TRUNCATE ON public.audit_event_fields
FOR EACH STATEMENT EXECUTE FUNCTION public.refuse_audit_event_change();
CREATE TRIGGER audit_event_checkpoints_no_change
BEFORE UPDATE OR DELETE ON public.audit_event_checkpoints
FOR EACH ROW EXECUTE FUNCTION public.refuse_audit_event_change();
CREATE TRIGGER audit_event_checkpoints_no_truncate
BEFORE TRUNCATE ON public.audit_event_checkpoints
FOR EACH STATEMENT EXECUTE FUNCTION public.refuse_audit_event_change();

DO $INSTALL_ROW_TRIGGERS$
DECLARE
    table_rule record;
BEGIN
    FOR table_rule IN
        SELECT entity_table,entity_kind FROM public.audit_event_table_rules ORDER BY entity_table
    LOOP
        EXECUTE format(
            'CREATE TRIGGER audit_event_capture AFTER INSERT OR UPDATE%s ON public.%I '
            'FOR EACH ROW EXECUTE FUNCTION public.audit_capture_row_event()',
            CASE WHEN table_rule.entity_kind='relationship' THEN ' OR DELETE' ELSE '' END,
            table_rule.entity_table
        );
    END LOOP;
END
$INSTALL_ROW_TRIGGERS$;

CREATE UNIQUE INDEX audit_events_single_baseline_idx
    ON public.audit_events(action) WHERE action='audit_baseline_established';
CREATE INDEX audit_events_entity_newest_idx
    ON public.audit_events(entity_schema,entity_table,entity_key,occurred_at DESC,id DESC)
    WHERE entity_schema IS NOT NULL;
CREATE INDEX audit_events_actor_newest_idx
    ON public.audit_events(actor_id,occurred_at DESC,id DESC);
CREATE INDEX audit_events_time_newest_idx
    ON public.audit_events(occurred_at DESC,id DESC);
CREATE INDEX audit_events_action_outcome_newest_idx
    ON public.audit_events(action,outcome,occurred_at DESC,id DESC);
CREATE INDEX audit_events_request_idx
    ON public.audit_events(request_id,occurred_at,id);
CREATE INDEX audit_events_correlation_idx
    ON public.audit_events(correlation_id,occurred_at,id);

DO $BASELINE$
DECLARE
    profile_name text;
    protected_rows bigint;
    created_attributions bigint := 0;
    updated_attributions bigint := 0;
    unknown_updates bigint := 0;
    audited_table text;
    baseline_id bigint;
    created_count bigint;
    updated_count bigint;
    unknown_count bigint;
    event_hash text;
    allowlist_hash text;
    baseline_metadata jsonb;
BEGIN
    protected_rows := (SELECT count(*) FROM public.invoices)
                    +(SELECT count(*) FROM public.payments)
                    +(SELECT count(*) FROM public.invoice_allocations)
                    +(SELECT count(*) FROM public.attendance);
    profile_name := CASE WHEN protected_rows=5209 THEN 'historical-live'
                         ELSE 'canonical-clean-replay' END;
    FOREACH audited_table IN ARRAY ARRAY(
        SELECT entity_table FROM public.audit_event_table_rules ORDER BY entity_table
    ) LOOP
        EXECUTE format(
            'SELECT count(*) FILTER(WHERE created_by=1),'
            'count(*) FILTER(WHERE updated_by=1),count(*) FILTER(WHERE updated_by IS NULL) '
            'FROM public.%I',audited_table
        ) INTO STRICT created_count,updated_count,unknown_count;
        created_attributions := created_attributions+created_count;
        updated_attributions := updated_attributions+updated_count;
        unknown_updates := unknown_updates+unknown_count;
    END LOOP;
    baseline_metadata := jsonb_build_object(
        'profile',profile_name,
        'access_history_available',false,
        'migrations_applied_before',56,
        'audit_actor_count',7,
        'created_attributions',created_attributions,
        'updated_attributions',updated_attributions,
        'unknown_update_actors',unknown_updates,
        'protected_rows',protected_rows,
        'protected_digest',CASE WHEN profile_name='historical-live'
            THEN 'b50879f52200275e70515cb4e1daa76594c304237a40b864205108e15490aeab' ELSE NULL END,
        'attribution_digest',CASE WHEN profile_name='historical-live'
            THEN 'edf4be9e8668fc65005deaa69cababf79dec1ac1b3e12f2356b9e6da892c009d' ELSE NULL END,
        'reconciliation_digest',CASE WHEN profile_name='historical-live'
            THEN 'c314cd64142cc2cef36b4dc8a35715db7660fed9d9aba2d06b383e86d2fa54ec' ELSE NULL END
    );
    INSERT INTO public.audit_events(
        actor_id,actor_key_snapshot,actor_display_name_snapshot,action,outcome,
        request_id,correlation_id,audit_session_id,device_class,event_metadata
    ) VALUES (
        1,'system_migration','Migration system','audit_baseline_established','succeeded',
        gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),'system',baseline_metadata
    ) RETURNING id INTO baseline_id;
    SELECT encode(sha256(convert_to((to_jsonb(e)-'occurred_at')::text,'UTF8')),'hex')
      INTO STRICT event_hash FROM public.audit_events e WHERE e.id=baseline_id;
    SELECT encode(sha256(convert_to(string_agg(
        f.entity_schema||E'\x1f'||f.entity_table||E'\x1f'||f.field_name||E'\x1f'||
        f.max_text_characters::text||E'\x1f'||f.capture_mode,
        E'\n' ORDER BY f.entity_schema,f.entity_table,f.field_name
    ),'UTF8')),'hex')
      INTO STRICT allowlist_hash FROM public.audit_event_fields f;
    INSERT INTO public.audit_event_checkpoints(
        checkpoint_key,migration_name,baseline_profile,event_count,
        first_event_id,through_event_id,event_digest,allowlist_digest
    ) VALUES (
        'task_3_3b_baseline','20260902180000_append_only_audit_events',profile_name,
        1,baseline_id,baseline_id,event_hash,allowlist_hash
    );
END
$BASELINE$;

REVOKE ALL ON TABLE public.audit_events,public.audit_event_table_rules,
    public.audit_event_fields,public.audit_event_checkpoints FROM PUBLIC,litigation_runtime;
REVOKE ALL ON SEQUENCE public.audit_events_id_seq FROM PUBLIC,litigation_runtime;
REVOKE ALL ON FUNCTION public.refuse_audit_event_change() FROM PUBLIC,litigation_runtime;
REVOKE ALL ON FUNCTION public.audit_contains_secret_pattern(text) FROM PUBLIC,litigation_runtime;
REVOKE ALL ON FUNCTION public.audit_bound_json_value(jsonb,integer,text) FROM PUBLIC,litigation_runtime;
REVOKE ALL ON FUNCTION public.audit_safe_flat_object(jsonb) FROM PUBLIC,litigation_runtime;
REVOKE ALL ON FUNCTION public.audit_set_event_context(uuid,uuid,uuid,inet,text,text) FROM PUBLIC,litigation_runtime;
REVOKE ALL ON FUNCTION public.audit_ensure_event_context() FROM PUBLIC,litigation_runtime;
REVOKE ALL ON FUNCTION public.audit_write_event(text,text,text,text,jsonb,text[],jsonb,jsonb,integer,text,text,jsonb,text,jsonb) FROM PUBLIC,litigation_runtime;
REVOKE ALL ON FUNCTION public.audit_append_semantic_event(text,text,text,text,jsonb,integer,text,text,jsonb,text,jsonb) FROM PUBLIC,litigation_runtime;
REVOKE ALL ON FUNCTION public.audit_capture_row_event() FROM PUBLIC,litigation_runtime;
GRANT EXECUTE ON FUNCTION public.audit_set_event_context(uuid,uuid,uuid,inet,text,text)
    TO litigation_runtime;
GRANT EXECUTE ON FUNCTION public.audit_append_semantic_event(text,text,text,text,jsonb,integer,text,text,jsonb,text,jsonb)
    TO litigation_runtime;

DO $POSTCONDITION$
DECLARE
    actual_tables text[];
    trigger_count bigint;
BEGIN
    SELECT array_agg(entity_table ORDER BY entity_table) INTO actual_tables
      FROM public.audit_event_table_rules;
    IF actual_tables IS DISTINCT FROM ARRAY[
        'admin_tasks','attendance','client_logos','clients','contacts','documents',
        'fee_letter_matters','fee_letters','hearing_attendees','hearings',
        'invoice_allocations','invoices','lookup_client_branch','lookup_court',
        'lookup_degree','lookup_hearing_action','lookup_importance',
        'lookup_invoice_status','lookup_invoice_type','lookup_lawyer_share_role',
        'lookup_matter_category','lookup_matter_destination','lookup_matter_type',
        'lookup_party_role','lookup_team','lookup_venue',
        'matter_fee_letter_references','matter_lawyers','matter_parties',
        'matter_party_roles','matters','payments','people','person_name_alias',
        'power_of_attorney_lawyers','powers_of_attorney','task_actions','user_accounts'
    ]::text[] THEN
        RAISE EXCEPTION 'Task 3.3B exact 38-table rule inventory differs';
    END IF;
    IF EXISTS (
        SELECT 1 FROM public.audit_event_fields f
        LEFT JOIN information_schema.columns c
          ON c.table_schema=f.entity_schema AND c.table_name=f.entity_table
         AND c.column_name=f.field_name
        WHERE c.column_name IS NULL OR c.data_type IN ('bytea','json','jsonb')
           OR (f.field_name='password_hash' AND f.capture_mode<>'redacted')
           OR (f.capture_mode='redacted' AND NOT (
               f.entity_table='user_accounts' AND f.field_name='password_hash'))
           OR f.field_name IN ('legacy_source_payload','created_at','created_by','updated_at','updated_by')
           OR f.field_name LIKE '%_normalised'
    ) OR EXISTS (
        SELECT 1 FROM public.audit_event_table_rules r
        LEFT JOIN public.audit_event_fields f USING(entity_schema,entity_table)
        GROUP BY r.entity_schema,r.entity_table HAVING count(f.field_name)=0
    ) THEN
        RAISE EXCEPTION 'Task 3.3B explicit field allowlist is unsafe or incomplete';
    END IF;
    SELECT count(*) INTO trigger_count
      FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid
      JOIN pg_namespace n ON n.oid=c.relnamespace
     WHERE n.nspname='public' AND t.tgname='audit_event_capture'
       AND NOT t.tgisinternal AND t.tgenabled='O';
    IF trigger_count<>38 THEN
        RAISE EXCEPTION 'Task 3.3B expected 38 enabled row-event triggers, found %',trigger_count;
    END IF;
    IF (SELECT count(*) FROM public.audit_events)<>1
       OR (SELECT count(*) FROM public.audit_events WHERE action='audit_baseline_established')<>1
       OR (SELECT count(*) FROM public.audit_event_checkpoints)<>1 THEN
        RAISE EXCEPTION 'Task 3.3B must establish exactly one aggregate baseline event/checkpoint';
    END IF;
    IF has_table_privilege('litigation_runtime','public.audit_events','SELECT')
       OR has_table_privilege('litigation_runtime','public.audit_events','INSERT')
       OR has_table_privilege('litigation_runtime','public.audit_events','UPDATE')
       OR has_table_privilege('litigation_runtime','public.audit_events','DELETE')
       OR has_table_privilege('litigation_runtime','public.audit_events','TRUNCATE')
       OR has_table_privilege('litigation_runtime','public.audit_events','TRIGGER')
       OR NOT has_function_privilege('litigation_runtime',
          'public.audit_set_event_context(uuid,uuid,uuid,inet,text,text)','EXECUTE')
       OR NOT has_function_privilege('litigation_runtime',
          'public.audit_append_semantic_event(text,text,text,text,jsonb,integer,text,text,jsonb,text,jsonb)','EXECUTE') THEN
        RAISE EXCEPTION 'Task 3.3B runtime append-only privilege boundary differs';
    END IF;
    IF EXISTS (
        SELECT 1 FROM pg_index i JOIN pg_class c ON c.oid=i.indexrelid
        WHERE i.indrelid='public.audit_events'::regclass
          AND pg_get_indexdef(i.indexrelid) ~* ' USING gin '
    ) THEN
        RAISE EXCEPTION 'Task 3.3B refuses an unrestricted JSON GIN index';
    END IF;
    IF (SELECT count(*) FROM public.audit_actors)<>7
       OR (SELECT count(*) FROM public.user_accounts WHERE updated_by IS NULL)<>4 THEN
        RAISE EXCEPTION 'Task 3.3B changed the protected actor state';
    END IF;
END
$POSTCONDITION$;

COMMIT;
