-- =========================================================================
--  0024 — STAGING SCHEMA (task 2.2)
--
--  GENERATED. Do not edit this file by hand.
--      npm run generate:staging-schema -- <this file>
--  Source of truth for the names: the extraction's own
--  _migration/meta/columns.csv. 191 columns, most of them Arabic;
--  retyping them is where a silent error would enter.
--
--  EVERY SOURCE COLUMN IS `text`, nullable, with no default and no
--  check. A load must not be able to fail on a bad date or a
--  non-numeric number — those arrive intact and are dealt with at
--  Gate 3, where the firm can see them. A row rejected at the door
--  is a row nobody ever sees again.
--
--  NULL and empty string stay distinct. An unassigned `lawyerA` is
--  not the same as one that was cleared. The extractor writes NULL
--  as a bare empty field and '' as "", and PostgreSQL CSV COPY reads
--  back exactly that distinction, so the schema only has to stay out
--  of the way.
--
--  Names are VERBATIM — Arabic, `Cash/probono`, `Inv-No` and all.
--  Staging must be directly comparable to the source. Renaming to
--  snake_case ASCII happens at transform, stage D.
--
--  THE EXTRACTION THIS DESCRIBES
--      source     D:\chatGPT\Litigation-Database\migration-source\Litigation database (ID 23194).accdb
--      bytes      46,661,632
--      modified   2026-08-23T07:31:52.6811852Z
--      sha256     40EBF988D4C952A676A4A00A403AE9576D87C18E35D4F7E3BAD0A62DF92D5979
--      extracted  2026-08-23T14:57:47.5065241+03:00
--      tables     17
--      rows       30,885
-- =========================================================================

CREATE SCHEMA staging;
COMMENT ON SCHEMA staging IS
    'Stage B of the Access migration. Every source column is text: a load can never fail on a type conversion, so no row is rejected at the door. Cleaning happens at Gate 3. See docs/MIGRATION.md.';

-- -------------------------------------------------------------------------
--  THE EXTRACTED TABLES — column names exactly as Access holds them
-- -------------------------------------------------------------------------

CREATE TABLE staging."admin work table" (
    src_file    text    NOT NULL,
    src_row_num integer NOT NULL,
    "ID_Task" text,
    "تاريخ التنفيذ" text,
    "النتيجة" text,
    "القائم بالعمل" text,
    "القرار السابق" text,
    "آخر متابعة" text,
    "المحكمة" text,
    "الدائرة" text,
    "الجهة" text,
    "العمل المطلوب" text,
    "تاريخ الإنشاء" text,
    "الحالة" text,
    "تنبيه" text,
    "آخر موعد" text,
    "matterID" text,
    PRIMARY KEY (src_file, src_row_num)
);
COMMENT ON TABLE staging."admin work table" IS
    'Access table admin work table. 15 columns, all text.';

CREATE TABLE staging."Attendance" (
    src_file    text    NOT NULL,
    src_row_num integer NOT NULL,
    "ID" text,
    "AttDate" text,
    "AttSituation" text,
    "المحامي" text,
    PRIMARY KEY (src_file, src_row_num)
);
COMMENT ON TABLE staging."Attendance" IS
    'Access table Attendance. 4 columns, all text.';

CREATE TABLE staging."Contacts" (
    src_file    text    NOT NULL,
    src_row_num integer NOT NULL,
    "ID" text,
    "Full_name" text,
    "Contact1" text,
    "E-mail Address" text,
    "Job Title" text,
    "Business Phone" text,
    "Home Phone" text,
    "Mobile Phone" text,
    "Fax Number" text,
    "Address" text,
    "City" text,
    "State/Province" text,
    "ZIP/Postal Code" text,
    "Country/Region" text,
    "Web Page" text,
    "clientID" text,
    PRIMARY KEY (src_file, src_row_num)
);
COMMENT ON TABLE staging."Contacts" IS
    'Access table Contacts. 16 columns, all text. The complex column Attachments is not here — a complex column holds a pointer, not data, and its real content is staged separately.';

CREATE TABLE staging."lawyers" (
    src_file    text    NOT NULL,
    src_row_num integer NOT NULL,
    "اسم المحامي" text,
    "LawyerID" text,
    "LawyerName" text,
    "Title" text,
    "AttTrack" text,
    PRIMARY KEY (src_file, src_row_num)
);
COMMENT ON TABLE staging."lawyers" IS
    'Access table lawyers. 5 columns, all text.';

CREATE TABLE staging."LawyerShare4Invoices" (
    src_file    text    NOT NULL,
    src_row_num integer NOT NULL,
    "ID" text,
    "المحامي" text,
    "الصفة" text,
    "النسبة" text,
    "الدعوى" text,
    PRIMARY KEY (src_file, src_row_num)
);
COMMENT ON TABLE staging."LawyerShare4Invoices" IS
    'Access table LawyerShare4Invoices. 5 columns, all text.';

CREATE TABLE staging."إجراءات المهام" (
    src_file    text    NOT NULL,
    src_row_num integer NOT NULL,
    "ID_process" text,
    "ID_Task" text,
    "تاريخ الإجراء" text,
    "القائم بالعمل" text,
    "النتيجة" text,
    "تقرير" text,
    "الموعد القادم" text,
    PRIMARY KEY (src_file, src_row_num)
);
COMMENT ON TABLE staging."إجراءات المهام" IS
    'Access table إجراءات المهام. 7 columns, all text.';

CREATE TABLE staging."التوكيلات" (
    src_file    text    NOT NULL,
    src_row_num integer NOT NULL,
    "العميل" text,
    "مسلسل" text,
    "اسم الموكل" text,
    "صفة الموكل بالتوكيل" text,
    "رقم التوكيل" text,
    "حرف" text,
    "السنة" text,
    "جهة الإصدار" text,
    "تاريخ الإصدار" text,
    "المحامون الصادر لهم التوكيل" text,
    "عدد النسخ" text,
    "ملاحظات" text,
    "الصفة" text,
    "clientID" text,
    "جرد" text,
    PRIMARY KEY (src_file, src_row_num)
);
COMMENT ON TABLE staging."التوكيلات" IS
    'Access table التوكيلات. 15 columns, all text.';

CREATE TABLE staging."الجلسات" (
    src_file    text    NOT NULL,
    src_row_num integer NOT NULL,
    "ID_hearings" text,
    "التاريخ" text,
    "القرار" text,
    "تقرير" text,
    "الحاضر" text,
    "lastDecision" text,
    "صالح/ضد" text,
    "الإجراء" text,
    "المحكمة" text,
    "حضور الجلسة القادمة" text,
    "الدائرة" text,
    "الجهة" text,
    "ملاحظات" text,
    "إخطار العميل بالقرار" text,
    "حاضر 1" text,
    "حاضر 2" text,
    "حاضر 3" text,
    "حاضر 4" text,
    "nextHearing" text,
    "matterID" text,
    "shortDecision" text,
    PRIMARY KEY (src_file, src_row_num)
);
COMMENT ON TABLE staging."الجلسات" IS
    'Access table الجلسات. 21 columns, all text.';

CREATE TABLE staging."الدعاوى" (
    src_file    text    NOT NULL,
    src_row_num integer NOT NULL,
    "clientID" text,
    "matterID" text,
    "matterAR" text,
    "matterEN" text,
    "client&Cap" text,
    "opponent&Cap" text,
    "matterSubject" text,
    "matterStatus" text,
    "matterCategory" text,
    "matterDegree" text,
    "matterImportance" text,
    "matterNotes2" text,
    "matterStartDate" text,
    "circutSecretary" text,
    "matterAskedAmount" text,
    "matterJudgedAmount" text,
    "clientBranch" text,
    "matterShelf" text,
    "courtFloor" text,
    "courtHall" text,
    "secretaryRoom" text,
    "matterCourt" text,
    "matterCircut" text,
    "matterDistination" text,
    "matterSelect" text,
    "matterPartner" text,
    "matterNotes1" text,
    "lawyerA" text,
    "lawyerB" text,
    "matteEvaluation" text,
    "matterEndDate" text,
    "الموقف الحالي" text,
    "نوع العميل" text,
    "المخصص المالي" text,
    "خطاب الأتعاب" text,
    "فريق العمل" text,
    "الرأي القانوني" text,
    "contractID" text,
    PRIMARY KEY (src_file, src_row_num)
);
COMMENT ON TABLE staging."الدعاوى" IS
    'Access table الدعاوى. 38 columns, all text.';

CREATE TABLE staging."السداد" (
    src_file    text    NOT NULL,
    src_row_num integer NOT NULL,
    "رقم الفاتورة" text,
    "التاريخ" text,
    "ID" text,
    "Credit" text,
    "Debit" text,
    "العملة" text,
    "بيان السداد" text,
    PRIMARY KEY (src_file, src_row_num)
);
COMMENT ON TABLE staging."السداد" IS
    'Access table السداد. 7 columns, all text.';

CREATE TABLE staging."العملاء" (
    src_file    text    NOT NULL,
    src_row_num integer NOT NULL,
    "ID_client" text,
    "Client_en" text,
    "Full_name" text,
    "العميل" text,
    "Cash/probono" text,
    "Status" text,
    "مكان التوكيل" text,
    "مكان المستندات" text,
    "contactLawyer" text,
    "clientStart" text,
    "clientEnd" text,
    PRIMARY KEY (src_file, src_row_num)
);
COMMENT ON TABLE staging."العملاء" IS
    'Access table العملاء. 11 columns, all text. The complex column logo is not here — a complex column holds a pointer, not data, and its real content is staged separately.';

CREATE TABLE staging."الفواتير" (
    src_file    text    NOT NULL,
    src_row_num integer NOT NULL,
    "Inv-No" text,
    "contractID" text,
    "Inv-Date" text,
    "Amount" text,
    "USD$" text,
    "Currency" text,
    "Inv-Details" text,
    "Inv-Status" text,
    "Inv-Type" text,
    "VAT?" text,
    "Pay-Date" text,
    "report" text,
    "R-#" text,
    "R-$" text,
    PRIMARY KEY (src_file, src_row_num)
);
COMMENT ON TABLE staging."الفواتير" IS
    'Access table الفواتير. 14 columns, all text.';

CREATE TABLE staging."المحامين" (
    src_file    text    NOT NULL,
    src_row_num integer NOT NULL,
    "lawyer_name" text,
    "lawyer_email" text,
    "Lawyer_EN" text,
    PRIMARY KEY (src_file, src_row_num)
);
COMMENT ON TABLE staging."المحامين" IS
    'Access table المحامين. 3 columns, all text.';

CREATE TABLE staging."المستندات" (
    src_file    text    NOT NULL,
    src_row_num integer NOT NULL,
    "مسلسل المستند ID" text,
    "العميل" text,
    "رقم الدعوى" text,
    "بيان المستند" text,
    "تاريخ المستند" text,
    "عدد الأوراق" text,
    "تاريخ الإيداع" text,
    "المحامي/الموظف المسئول" text,
    "ملاحظات" text,
    "بطاقة الحركة" text,
    "clientID" text,
    PRIMARY KEY (src_file, src_row_num)
);
COMMENT ON TABLE staging."المستندات" IS
    'Access table المستندات. 11 columns, all text.';

CREATE TABLE staging."تقسيم التحصيلات" (
    src_file    text    NOT NULL,
    src_row_num integer NOT NULL,
    "ID" text,
    "InvNo" text,
    "Lawyer" text,
    "Percent" text,
    "LawyerAs" text,
    PRIMARY KEY (src_file, src_row_num)
);
COMMENT ON TABLE staging."تقسيم التحصيلات" IS
    'Access table تقسيم التحصيلات. 5 columns, all text.';

CREATE TABLE staging."خطابات الأتعاب" (
    src_file    text    NOT NULL,
    src_row_num integer NOT NULL,
    "contractID" text,
    "mfilesID" text,
    "Cont-Type" text,
    "Cont-Date" text,
    "Cont-Details" text,
    "Cont-Structure" text,
    "Client" text,
    "clientID" text,
    "Status" text,
    PRIMARY KEY (src_file, src_row_num)
);
COMMENT ON TABLE staging."خطابات الأتعاب" IS
    'Access table خطابات الأتعاب. 9 columns, all text. The complex column Matter is not here — a complex column holds a pointer, not data, and its real content is staged separately.';

CREATE TABLE staging."فريق العمل" (
    src_file    text    NOT NULL,
    src_row_num integer NOT NULL,
    "ID" text,
    "الفريق" text,
    "التخصصات" text,
    "Code" text,
    "المراجع" text,
    PRIMARY KEY (src_file, src_row_num)
);
COMMENT ON TABLE staging."فريق العمل" IS
    'Access table فريق العمل. 5 columns, all text.';

-- -------------------------------------------------------------------------
--  THE COMPLEX COLUMNS
--
--  Attachment and multi-value columns are not stored in the visible
--  table: the visible column holds an internal pointer. Exporting
--  العملاء to CSV gives a `logo` column where all 318 rows look
--  populated with values like 136, 42, 1 — and only 54 clients have
--  a logo. Each one is staged as its own table, keyed back to its
--  parent row. See D11 and docs/MIGRATION.md.
-- -------------------------------------------------------------------------

CREATE TABLE staging."Contacts__Attachments" (
    src_file    text    NOT NULL,
    src_row_num integer NOT NULL,
    "parent_key" text,
    "file_name" text,
    "file_type" text,
    "byte_size" text,
    "stored_path" text,
    PRIMARY KEY (src_file, src_row_num)
);
COMMENT ON TABLE staging."Contacts__Attachments" IS
    'The complex column Contacts.Attachments, flattened. Extracted to complex/Contacts__Attachments__attachments.csv. parent_key points back at the row it belongs to.';

CREATE TABLE staging."العملاء__logo" (
    src_file    text    NOT NULL,
    src_row_num integer NOT NULL,
    "parent_key" text,
    "file_name" text,
    "file_type" text,
    "byte_size" text,
    "stored_path" text,
    PRIMARY KEY (src_file, src_row_num)
);
COMMENT ON TABLE staging."العملاء__logo" IS
    'The complex column العملاء.logo, flattened. Extracted to complex/العملاء__logo__attachments.csv. parent_key points back at the row it belongs to.';

CREATE TABLE staging."خطابات الأتعاب__Matter" (
    src_file    text    NOT NULL,
    src_row_num integer NOT NULL,
    "parent_key" text,
    "ordinal" text,
    "value" text,
    PRIMARY KEY (src_file, src_row_num)
);
COMMENT ON TABLE staging."خطابات الأتعاب__Matter" IS
    'The complex column خطابات الأتعاب.Matter, flattened. Extracted to complex/خطابات الأتعاب__Matter__values.csv. parent_key points back at the row it belongs to.';

-- -------------------------------------------------------------------------
--  ASSERTIONS
--
--  Not "did the CREATE statements run" — that much a syntax error
--  would catch. These prove the PROPERTIES the staging layer exists
--  for: nothing can reject a row. A NOT NULL, a default or a check
--  on a source column would each turn a load failure into a lost
--  row, and none of them would look wrong in a diff.
-- -------------------------------------------------------------------------

DO $STAGING$
DECLARE
    n integer;
BEGIN
    SELECT count(*) INTO n FROM information_schema.tables
     WHERE table_schema = 'staging' AND table_type = 'BASE TABLE';
    IF n <> 20 THEN
        RAISE EXCEPTION 'staging: % tables, expected 20', n;
    END IF;

    SELECT count(*) INTO n FROM information_schema.columns
     WHERE table_schema = 'staging';
    IF n <> 244 THEN
        RAISE EXCEPTION 'staging: % columns, expected 244 (204 from Access + 20 x 2 bookkeeping)', n;
    END IF;

    --  Every source column is text. A typed column here would be a
    --  column that can refuse a row.
    SELECT count(*) INTO n FROM information_schema.columns
     WHERE table_schema = 'staging'
       AND column_name NOT IN ('src_file', 'src_row_num')
       AND data_type <> 'text';
    IF n <> 0 THEN
        RAISE EXCEPTION 'staging: % source columns are not text', n;
    END IF;

    --  ...and every one of them is nullable, so NULL and '' can both
    --  arrive and stay different.
    SELECT count(*) INTO n FROM information_schema.columns
     WHERE table_schema = 'staging'
       AND column_name NOT IN ('src_file', 'src_row_num')
       AND is_nullable <> 'YES';
    IF n <> 0 THEN
        RAISE EXCEPTION 'staging: % source columns are NOT NULL', n;
    END IF;

    --  No defaults. A default would invent a value for a field the
    --  firm left empty, which is the opposite of what staging is for.
    SELECT count(*) INTO n FROM information_schema.columns
     WHERE table_schema = 'staging' AND column_default IS NOT NULL;
    IF n <> 0 THEN
        RAISE EXCEPTION 'staging: % columns have a default', n;
    END IF;

    --  No checks anywhere in the schema.
    SELECT count(*) INTO n
      FROM pg_constraint c
      JOIN pg_class t ON t.oid = c.conrelid
      JOIN pg_namespace ns ON ns.oid = t.relnamespace
     WHERE ns.nspname = 'staging' AND c.contype = 'c';
    IF n <> 0 THEN
        RAISE EXCEPTION 'staging: % check constraints', n;
    END IF;

    --  No foreign keys either. A staging row that fails to find its
    --  parent is a finding for Gate 3, not a load error.
    SELECT count(*) INTO n
      FROM pg_constraint c
      JOIN pg_class t ON t.oid = c.conrelid
      JOIN pg_namespace ns ON ns.oid = t.relnamespace
     WHERE ns.nspname = 'staging' AND c.contype = 'f';
    IF n <> 0 THEN
        RAISE EXCEPTION 'staging: % foreign keys', n;
    END IF;

    --  Every table keyed on the bookkeeping pair, so loading the same
    --  file twice is an error rather than a silent doubling.
    SELECT count(*) INTO n
      FROM pg_constraint c
      JOIN pg_class t ON t.oid = c.conrelid
      JOIN pg_namespace ns ON ns.oid = t.relnamespace
     WHERE ns.nspname = 'staging' AND c.contype = 'p';
    IF n <> 20 THEN
        RAISE EXCEPTION 'staging: % primary keys, expected 20', n;
    END IF;

    RAISE NOTICE 'staging: 20 tables, 204 source columns, all text, nothing can refuse a row';
END
$STAGING$;
