-- Generated by npm run generate:court-seed from sql/lookup-court-and-crosswalk.sql.
-- 308 courts, 94 crosswalk rules.
-- DO NOT EDIT BY HAND: correct the source file and regenerate, or the
-- reviewed data and the migration diverge.
--
-- The source file lists 309 courts. 1 of them is also a MERGE
-- SOURCE — a spelling of another court, not a court — so it is dropped and the
-- list is 308. 1 SPLIT court part was resolved through the merge
-- map for the same reason. See the generator header.

-- ---- 309 courts ----
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('القاهرة الاقتصادية', 10, now());   -- 2523 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('شمال القاهرة', 20, now());   -- 1447 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('شبين الكوم', 30, now());   -- 1333 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('النقض', 40, now());   -- 970 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('القضاء الإداري', 50, now());   -- 931 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('جنوب الجيزة', 60, now());   -- 743 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('استئناف القاهرة', 70, now());   -- 705 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('القاهرة الجديدة', 80, now());   -- 614 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('جنوب القاهرة', 90, now());   -- 566 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('الإدارية العليا', 100, now());   -- 508 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('استئناف شمال القاهرة', 110, now());   -- 503 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('الإسكندرية الاقتصادية', 120, now());   -- 405 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('6 أكتوبر -جنوب الجيزة الكلية', 130, now());   -- 398 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('القضاء الإداري بالعباسية', 140, now());   -- 360 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('خبراء القاهرة الاقتصادية', 150, now());   -- 296 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('شمال الجيزة', 160, now());   -- 260 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('استئناف شبين الكوم', 170, now());   -- 224 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('الهيئة العامة للاستثمار والمناطق الحرة', 180, now());   -- 223 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('خبراء شرق القاهرة', 190, now());   -- 218 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('خبراء شبين الكوم', 200, now());   -- 198 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('الإسكندرية', 210, now());   -- 173 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('6 أكتوبر', 220, now());   -- 162 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('الجيزة الابتدائية', 230, now());   -- 159 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('خبراء شمال الجيزة', 240, now());   -- 150 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('مجلس الدولة بالرحاب', 250, now());   -- 147 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('القضاء الإداري بالإسكندرية', 260, now());   -- 146 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('خبراء شمال القاهرة', 270, now());   -- 123 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('استئناف شمال الجيزة', 280, now());   -- 119 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('استئناف 6 أكتوبر', 290, now());   -- 117 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('خبراء جنوب القاهرة', 300, now());   -- 107 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('خبراء جنوب الجيزة', 310, now());   -- 104 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('نيابة الشئون المالية والتجارية', 320, now());   -- 83 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('حلوان', 330, now());   -- 77 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('استئناف عالي شبين الكوم', 340, now());   -- 66 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('تاج الدول', 350, now());   -- 64 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('القاهرة للأمور المستعجلة', 360, now());   -- 62 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('استئناف عالي القاهرة', 370, now());   -- 50 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('النزهة الجزئية', 380, now());   -- 50 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('الدقي', 390, now());   -- 48 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('جنوب الجيزة الابتدائية', 400, now());   -- 48 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('خبراء الكسب غير المشروع', 410, now());   -- 47 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('إدارية عليا', 420, now());   -- 46 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('استئناف الجيزة', 430, now());   -- 44 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('العجوزة الجزئية', 440, now());   -- 40 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('بنها', 450, now());   -- 39 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('خبراء وسط القاهرة', 460, now());   -- 36 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('عابدين', 470, now());   -- 36 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('الإسكندرية الابتدائية', 480, now());   -- 35 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('البساتين (المعادي)', 490, now());   -- 34 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('إمبابة الجزئية', 500, now());   -- 34 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('القضاء الأداري - مجلس الدولة', 510, now());   -- 33 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('جنوب القاهرة الأبتدائية', 520, now());   -- 33 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('خبراء الإسكندرية الاقتصادية', 530, now());   -- 33 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('المعادي', 540, now());   -- 30 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('المنصورة', 550, now());   -- 30 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('خبراء وسط الإسكندرية', 560, now());   -- 29 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('استئناف الإسكندرية (أبيس)', 570, now());   -- 28 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('الهيئة العامة للرقابة المالية', 580, now());   -- 28 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('استئناف عالي شمال القاهرة', 590, now());   -- 26 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('العجوزة', 600, now());   -- 26 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('مجلس الدولة', 610, now());   -- 26 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('مجلس الدولة بالجيزة', 620, now());   -- 24 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('خبراء وزارة العدل', 630, now());   -- 23 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('استئناف الإسكندرية', 640, now());   -- 22 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('استئناف شمال الجيزة (السودان)', 650, now());   -- 22 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('خبراء شمال الدقهلية', 660, now());   -- 22 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('نيابة القاهرة الجديدة', 670, now());   -- 22 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('الهيئة العامة للأستثمار- المنطقة الحرة', 680, now());   -- 21 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('شمال أسيوط', 690, now());   -- 21 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('استئناف القاهرة مأمورية شمال الجيزة', 700, now());   -- 20 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('العبور', 710, now());   -- 20 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('نيابة الأموال العامة', 720, now());   -- 20 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('نيابة شمال الجيزة', 730, now());   -- 20 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('القاهرة الجديدة الأبتدائية', 740, now());   -- 18 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('الأسرة', 750, now());   -- 17 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('العبور الجزئية', 760, now());   -- 17 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('خبراء مجلس الدولة', 770, now());   -- 17 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('رشيد الكلية', 780, now());   -- 17 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('استئناف التجمع', 790, now());   -- 16 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('القضاء الإداري بالإسماعيلية', 800, now());   -- 16 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('حلوان الأبتدائية', 810, now());   -- 16 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('مصلحة الضرائب', 820, now());   -- 16 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('مكتب خبراء شبرا الخيمة', 830, now());   -- 16 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('هيئة مفوضي الدولة', 840, now());   -- 16 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('شمال الجيزة - تنعقد في جنوب الجيزة', 850, now());   -- 15 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('غرب طنطا', 860, now());   -- 15 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('مركز التسوية و التحكيم الرياضي المصري', 870, now());   -- 15 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('نيابة 6 أكتوبر', 880, now());   -- 15 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('استئناف الخانكة', 890, now());   -- 14 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('القاهرة لاقتصادية', 900, now());   -- 14 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('اللجنة الأوليمبية المصرية', 910, now());   -- 14 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('لجنة التفتيش - الهيئة العامة للاستثمار', 920, now());   -- 14 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('مدينة نصر', 930, now());   -- 14 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('العبور (الخانكة)', 940, now());   -- 13 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('خبراء ولي العهد', 950, now());   -- 13 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('طنطا الاقتصادية', 960, now());   -- 12 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('قصر النيل الجزئية', 970, now());   -- 12 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('الشيخ زايد', 980, now());   -- 11 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('الطب الشرعي', 990, now());   -- 11 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('أسيوط الاقتصادية', 1000, now());   -- 11 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('شمال الجيزة (السودان)', 1010, now());   -- 11 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('مكتب خبراء شرق القاهرة -  العباسية', 1020, now());   -- 11 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('مكتب خبراء وسط القاهرة', 1030, now());   -- 11 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('استئناف القاهرة (دار القضاء العالي)', 1040, now());   -- 10 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('استئناف بنها', 1050, now());   -- 10 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('الهرم الجزئية', 1060, now());   -- 10 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('جنايات القاهرة', 1070, now());   -- 10 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('دار القضاء العالي', 1080, now());   -- 10 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('قويسنا', 1090, now());   -- 10 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('جنح منفلوط', 1100, now());   -- 9 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('خبراء طنطا الاقتصادية', 1110, now());   -- 9 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('قضاء إداري الأسكندرية', 1120, now());   -- 9 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('مصلحة الطب الشرعي', 1130, now());   -- 9 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('مكتب النائب العام بالرحاب', 1140, now());   -- 9 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('نيابة الأموال العامة العليا', 1150, now());   -- 9 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('هيئة الرقابة المالية', 1160, now());   -- 9 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('هيئة المفوضين', 1170, now());   -- 9 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('استئناف القاهرة مأمورية شمال القاهرة', 1180, now());   -- 8 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('السادات', 1190, now());   -- 8 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('العجوزة-تاج الدول', 1200, now());   -- 8 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('خبراء مجلس الدولة بالرحاب', 1210, now());   -- 8 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('مجلس الدولة بالعباسية', 1220, now());   -- 8 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('مصر الجديدة', 1230, now());   -- 8 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('مفوضي القضاء الإداري', 1240, now());   -- 8 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('مكتب خبراء شمال الجيزة', 1250, now());   -- 8 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('نيابة التهرب الضريبي', 1260, now());   -- 8 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('نيابة الهرم', 1270, now());   -- 8 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('استئناف دار القضاء', 1280, now());   -- 7 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('الجيزة', 1290, now());   -- 7 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('الخانكة', 1300, now());   -- 7 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('السويس', 1310, now());   -- 7 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('المحكمة الاقتصادية', 1320, now());   -- 7 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('المحكمة الدستورية', 1330, now());   -- 7 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('الهيئة العامة للاستثمار (لجان التظلمات)', 1340, now());   -- 7 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('مأمورية استئناف الجيزة', 1350, now());   -- 7 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('مصلحة الخبراء بمجمع المصالح - الدور الثامن - شمال أسيوط', 1360, now());   -- 7 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('مكتب خبراء جنوب القاهرة', 1370, now());   -- 7 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('استئناف القاهرة مأمورية استئناف الجيزة', 1380, now());   -- 6 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('الجيزة الابتدائية (تاج الدول)', 1390, now());   -- 6 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('الدقي (تاج الدول)', 1400, now());   -- 6 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('قسم أول المنصورة', 1410, now());   -- 6 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('قصر النيل - عابدين', 1420, now());   -- 6 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('كفر شكر الجزئية', 1430, now());   -- 6 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('مجلس الدولة بالدقي', 1440, now());   -- 6 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('استئناف 6 أكتوبر (شمال الجيزة)', 1450, now());   -- 5 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('استئناف الزقازيق', 1460, now());   -- 5 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('اسئناف شمال الجيزة', 1470, now());   -- 5 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('التجمع الخامس', 1480, now());   -- 5 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('الفيوم', 1490, now());   -- 5 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('المحكمة الإدارية لرئاسة الجمهورية', 1500, now());   -- 5 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('أسيوط', 1510, now());   -- 5 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('أول 6 أكتوبر', 1520, now());   -- 5 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('جنوب الجيزة (إمبابة)', 1530, now());   -- 5 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('خبراء الاستثمار', 1540, now());   -- 5 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('خبراء كسب غير مشروع', 1550, now());   -- 5 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('شرم الشيخ', 1560, now());   -- 5 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('لجنة تظلمات', 1570, now());   -- 5 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('محكمة مجلس الدولة بالدقي - القضاء الأداري', 1580, now());   -- 5 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('مكتب الخبراء المقيمين بمجلس الدولة', 1590, now());   -- 5 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('استئناف الأسماعيلية', 1600, now());   -- 4 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('استئناف عالي طنطا', 1610, now());   -- 4 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('الجيزة الكلية', 1620, now());   -- 4 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('الدقي الجزئية', 1630, now());   -- 4 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('الطور - مأمورية استئناف الإسماعيلية', 1640, now());   -- 4 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('باب الشعرية', 1650, now());   -- 4 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('بلبيس', 1660, now());   -- 4 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('جمارك الإسكندرية', 1670, now());   -- 4 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('جنح', 1680, now());   -- 4 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('جنح التهرب الضريبي', 1690, now());   -- 4 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('خبراء الإسكندرية', 1700, now());   -- 4 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('خبراء شبرا الخيمة', 1710, now());   -- 4 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('خبراء شمال القاهرة-ولي العهد', 1720, now());   -- 4 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('خبراء محكمة زنانيري', 1730, now());   -- 4 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('شمال القاهرة الإبتدائية', 1740, now());   -- 4 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('طنطا الابتدائية', 1750, now());   -- 4 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('لجنة التحفظ على أموال الإخوان', 1760, now());   -- 4 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('مجلس الدولة الرحاب', 1770, now());   -- 4 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('مجلس الدولة بالرحاب- هيئة مفوضي الدولة', 1780, now());   -- 4 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('محكمة خبراء تزييف وتزوير مبني المواردي السيدة زينب', 1790, now());   -- 4 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('مدينة نصر أول', 1800, now());   -- 4 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('مكتب خبراء شبين الكوم (مجمع المصالح الحكومية - الدور الرابع)', 1810, now());   -- 4 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('مكتب خبراء محرم بك', 1820, now());   -- 4 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('نيابة العجوزة', 1830, now());   -- 4 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('نيابة مصر الجديدة', 1840, now());   -- 4 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('وزارة الداخلية', 1850, now());   -- 4 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('وزارة العدل', 1860, now());   -- 4 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('استئناف الخانكة والعبور', 1870, now());   -- 3 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('استئناف عالي بنها', 1880, now());   -- 3 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('الاستئناف', 1890, now());   -- 3 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('الإسماعيلية', 1900, now());   -- 3 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('الأمور المستعجلة بعابدين', 1910, now());   -- 3 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('الرمل الجزئية', 1920, now());   -- 3 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('القاهرة التجارية', 1930, now());   -- 3 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('النيابة الإدارية', 1940, now());   -- 3 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('أسرة العجوزة', 1950, now());   -- 3 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('أسرة قصر النيل', 1960, now());   -- 3 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('أسيوط الابتدائية', 1970, now());   -- 3 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('بندر شبين الكوم', 1980, now());   -- 3 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('جنح العجوزة', 1990, now());   -- 3 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('جنح شبرا الخيمة أول', 2000, now());   -- 3 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('خبراء غرب الإسكندرية', 2010, now());   -- 3 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('دمنهور', 2020, now());   -- 3 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('زنانيري', 2030, now());   -- 3 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('لجنة التظلمات بالهيئة العامة الرقابة المالية', 2040, now());   -- 3 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('لجنة التفتيش', 2050, now());   -- 3 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('لجنة توفيق منازعات بوزارة السياحة', 2060, now());   -- 3 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('مجلس الدولة بالأسكندرية', 2070, now());   -- 3 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('مجلس الدولة بالجيزة - القضاء الإداري', 2080, now());   -- 3 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('محكمة', 2090, now());   -- 3 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('مركز المنصورة', 2100, now());   -- 3 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('مستأنف شبرا الخيمة', 2110, now());   -- 3 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('مكتب خبراء وزارة العدل بجنوب الجيزة', 2120, now());   -- 3 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('نيابة العامرية ثاني', 2130, now());   -- 3 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('هيئة الرقابة المالية، والبورصة المصرية', 2140, now());   -- 3 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('استئناف 6 أكتوبر (شمال الجيزة -  السودان)', 2150, now());   -- 2 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('استئناف المنصورة', 2160, now());   -- 2 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('استئناف جنوب الجيزة', 2170, now());   -- 2 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('الإسكندرية للأمور المستعجلة', 2180, now());   -- 2 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('الأسرة بزنانيري', 2190, now());   -- 2 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('البنك المركزي المصري', 2200, now());   -- 2 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('الجهاز التنفيذي للمنطقة الصناعية و مديرية المساحة', 2210, now());   -- 2 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('الدستورية العليا', 2220, now());   -- 2 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('الساحل', 2230, now());   -- 2 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('اللجنة الوزارية لفض منازعات الاستثمار', 2240, now());   -- 2 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('النيابة الكلية', 2250, now());   -- 2 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('أسرة 6 أكتوبر', 2260, now());   -- 2 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('ثالث الإسماعيلية', 2270, now());   -- 2 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('جنايات النزهة', 2280, now());   -- 2 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('جنايات شمال القاهرة', 2290, now());   -- 2 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('جنح الدقي', 2300, now());   -- 2 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('جهاز مدينة التجمع الخامس', 2310, now());   -- 2 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('خبراء الطب الشرعي', 2320, now());   -- 2 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('دار القضاء العالي محكمة النقض', 2330, now());   -- 2 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('طب شرعي - وزارة العدل', 2340, now());   -- 2 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('طب شرعي جنوب القاهرة', 2350, now());   -- 2 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('قسم شرطة الهرم', 2360, now());   -- 2 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('قسم شرطة مصر الجديدة', 2370, now());   -- 2 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('كرداسة', 2380, now());   -- 2 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('كوم حمادة', 2390, now());   -- 2 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('مبني المواردي السيدة زينب امام المترو', 2400, now());   -- 2 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('محضري مدينة نصر', 2410, now());   -- 2 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('مستعجل الإسكندرية', 2420, now());   -- 2 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('مصلحة الضرائب -لجنة إنهاء المنازعات المالية', 2430, now());   -- 2 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('مكتب عمل', 2440, now());   -- 2 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('مكتب عمل ميناء البصل', 2450, now());   -- 2 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('مكتب غرب  الإسكندرية', 2460, now());   -- 2 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('نيابة الزقازيق', 2470, now());   -- 2 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('نيابة أول أكتوبر', 2480, now());   -- 2 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('نيابة سيدي جابر لشئون الأسرة', 2490, now());   -- 2 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('نيابة عابدين', 2500, now());   -- 2 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('نيابة مدينة نصر أول الجزئية', 2510, now());   -- 2 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('هيئة الأوقاف المصرية', 2520, now());   -- 2 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('هيئة سوق المال', 2530, now());   -- 2 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('االقضاء الأداري', 2540, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('استئناف الجيزة- شارع السودان', 2550, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('استئناف القاهرة مأمورية استئناف شمال الجيزة', 2560, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('استئناف عالي المنصورة', 2570, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('الإدارة العامة لتكنولوجيا المعلومات', 2580, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('الإدارية العليا بالدقي', 2590, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('البساتين الجزئية', 2600, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('الجنايات', 2610, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('الشركة الهندسية للتنمية السياحية', 2620, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('الضرائب', 2630, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('العباسية', 2640, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('القاهرة الجديدة الجزئية', 2650, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('النزهة', 2660, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('النقض - مدني', 2670, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('النوبارية', 2680, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('الهيئة العامة للاستثمار بالإسكندرية', 2690, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('أسرة الخليفة', 2700, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('أكاديمية الشرطة -إدارة تكنولوجيا المعلومات', 2710, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('أكتوبر ثاني', 2720, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('بريد العتبة', 2730, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('جنايات العجوزة', 2740, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('جنح الطالبية', 2750, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('جنح مستأنف مدينة نصر', 2760, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('جنح مستأنف مصر الجديدة', 2770, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('جنوب المنصورة الكلية', 2780, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('حفظ العجوزة', 2790, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('خبراء شمال أسيوط', 2800, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('خبراء مجلس الدولة بالإسكندرية', 2810, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('خبراء محكمة الأسرة', 2820, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('شرطة مباحث التموين', 2830, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('شهر عقاري الدقي', 2840, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('قسم مدينة نصر أول', 2850, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('لجنة', 2860, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('لجنة إنهاء المنازعات الضريبية', 2870, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('لجنة تظلمات الهيئة العامة للرقابة المالية', 2880, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('مجلس الدولة بالجيزة - الإدارية العليا', 2890, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('محضري الدقي', 2900, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('محضري النزهة', 2910, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('مركز شرطة الزقازيق', 2920, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('مصلحة الجوازات والهجرة', 2930, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('مطروح الجزئية الكائن مقرها شارع شكري القوتلي أمام بنك الإسكندرية مطروح', 2940, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('مكتب عمل مدينة نصر', 2950, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('نيابة الأموال العامة العليا - تظلمات النائب العام', 2960, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('نيابة الدقي', 2970, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('نيابة الشيخ زايد', 2980, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('نيابة أمن الدولة العليا', 2990, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('نيابة جنوب المنصورة', 3000, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('نيابة شبين الكوم', 3010, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('نيابة شرق الإسكندرية (المنتزه)', 3020, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('نيابة شئون الأسرة -مال', 3030, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('نيابة قصر النيل الجزئية', 3040, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('نيابة مدينة نصر', 3050, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('هيئة الطاقة الجديدة والمتجددة', 3060, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('وزارة التربية والتعليم', 3070, now());   -- 1 uses
INSERT INTO "lookup_court" (label_ar, sort_order, updated_at) VALUES ('محكمة استئناف اسرة التجمع', 3080, now());   -- 1 uses

-- ---- 94 crosswalk rules ----
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', '6 أكتوبر (جنوب الجيزة)', 380, 'court', '6 أكتوبر -جنوب الجيزة الكلية', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'القاهرة الأقتصادية', 206, 'court', 'القاهرة الاقتصادية', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'الاسكندرية الاقتصادية', 109, 'court', 'الإسكندرية الاقتصادية', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'الهيئة العامة للاستثمار', 75, 'court', 'الهيئة العامة للاستثمار والمناطق الحرة', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'هيئة الاستثمار', 42, 'court', 'الهيئة العامة للاستثمار والمناطق الحرة', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'الهيئة العامة للأستثمار - المنطقة الحرة', 32, 'court', 'الهيئة العامة للاستثمار والمناطق الحرة', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'محكمة النقض', 27, 'court', 'النقض', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'القضاء الأداري', 25, 'court', 'القضاء الإداري', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'هيئة الأستثمار - المنطقة الحرة', 25, 'court', 'الهيئة العامة للاستثمار والمناطق الحرة', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'استئناف عال شبين الكوم', 21, 'court', 'استئناف عالي شبين الكوم', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'قضاء إداري', 21, 'court', 'القضاء الإداري', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'السادس من أكتوبر', 19, 'court', '6 أكتوبر', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'استئناف الإسكندرية بأبيس', 18, 'court', 'استئناف الإسكندرية (أبيس)', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'استئناف شمال الجيزة شارع السودان', 17, 'court', 'استئناف شمال الجيزة (السودان)', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'الأدارية العليا', 15, 'court', 'الإدارية العليا', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'المحكمة الإدارية العليا', 14, 'court', 'الإدارية العليا', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'هيئة الاستثمار - المنطقة الحرة', 13, 'court', 'الهيئة العامة للاستثمار والمناطق الحرة', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'أكتوبر', 10, 'court', '6 أكتوبر', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'القاهرة الجديدة الابتدائية', 8, 'court', 'القاهرة الجديدة الأبتدائية', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'جنوب الجيزة الأبتدائية', 8, 'court', 'جنوب الجيزة الابتدائية', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'جنوب القاهرة الابتدائية', 8, 'court', 'جنوب القاهرة الأبتدائية', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'استئناف عال القاهرة', 7, 'court', 'استئناف عالي القاهرة', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'القضاء الاداري بالعباسية', 7, 'court', 'القضاء الإداري بالعباسية', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'الهيئة العامة للأستثمار في صلاح سالم', 7, 'court', 'الهيئة العامة للاستثمار والمناطق الحرة', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'حلوان الابتدائية', 7, 'court', 'حلوان الأبتدائية', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'خبراء القاهرة الأقتصادية', 7, 'court', 'خبراء القاهرة الاقتصادية', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'الهيئة العامة للأستثمار  - المنطقة الحرة', 6, 'court', 'الهيئة العامة للاستثمار والمناطق الحرة', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'لجنة تفتيش بهيئة الأستثمار', 6, 'court', 'لجنة التفتيش - الهيئة العامة للاستثمار', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'محكمة حلوان الابتدائية', 6, 'court', 'حلوان الأبتدائية', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'مركز التسوية والتحكيم الرياضي', 6, 'court', 'مركز التسوية و التحكيم الرياضي المصري', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'أستئناف القاهرة', 5, 'court', 'استئناف القاهرة', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'محكمة جنوب القاهرة', 5, 'court', 'جنوب القاهرة', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'محكمة مجلس الدولة بالرحاب', 4, 'court', 'مجلس الدولة بالرحاب', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'مكتب خبراء شرق القاهرة بالعباسية', 4, 'court', 'مكتب خبراء شرق القاهرة -  العباسية', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'هيئة الأستثمار بمدينة نصر', 4, 'court', 'الهيئة العامة للاستثمار والمناطق الحرة', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'قضاء الأداري', 3, 'court', 'القضاء الإداري', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'محكمة شمال الجيزة', 3, 'court', 'شمال الجيزة', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'محكمة شمال الجيزة الابتدائية تنعقد في جنوب الجيزة', 3, 'court', 'شمال الجيزة - تنعقد في جنوب الجيزة', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'محكمة مدينة نصر', 3, 'court', 'مدينة نصر', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'مكتب خبراء العباسية', 3, 'court', 'مكتب خبراء شرق القاهرة -  العباسية', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'استئناف الخانكة و العبور', 2, 'court', 'استئناف الخانكة والعبور', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'الهيئة العامة للاستثمار بالمنطقة الحرة', 2, 'court', 'الهيئة العامة للاستثمار والمناطق الحرة', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'قصر النيل- عابدين', 2, 'court', 'قصر النيل - عابدين', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'محكمة القاهرة الجديدة', 2, 'court', 'القاهرة الجديدة', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', '6 أكتوبر -جنوب الجزة الكلية', 1, 'court', '6 أكتوبر -جنوب الجيزة الكلية', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'استئناف', 1, 'court', 'الاستئناف', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'اسرة العجوزة', 1, 'court', 'أسرة العجوزة', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'جهاز التنفيذي للمنطقة الصناعية و مديرية المساحة', 1, 'court', 'الجهاز التنفيذي للمنطقة الصناعية و مديرية المساحة', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'محكمة أستئناف القاهرة', 1, 'court', 'استئناف القاهرة', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'محكمة حلوان', 1, 'court', 'حلوان', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'محكمة عابدين', 1, 'court', 'عابدين', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'نقض', 1, 'court', 'النقض', 'Spelling variant. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'الجيزة الابتدائية  \n (السودان)', 5, 'SPLIT', 'الجيزة الابتدائية', 'Split: court=''الجيزة الابتدائية'', circuit=''(السودان)''');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'نيابة الأموال العامة \n العليا', 5, 'SPLIT', 'نيابة الأموال العامة', 'Split: court=''نيابة الأموال العامة'', circuit=''العليا''');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'خبراء مجلس الدولة (خبير/محمد هاشم)', 4, 'SPLIT', 'خبراء مجلس الدولة', 'Split: court=''خبراء مجلس الدولة'', hearing_note=''خبير/محمد هاشم''');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'القاهرة الجديدة \n استئناف محكمة الأسرة', 3, 'SPLIT', 'القاهرة الجديدة', 'Split: court=''القاهرة الجديدة'', circuit=''استئناف محكمة الأسرة''');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'نيابة الشئون المالية والتجارية \n  \n وكيل نيابة/ أسامة الطنطاوي', 3, 'SPLIT', 'نيابة الشئون المالية والتجارية', 'Split: court=''نيابة الشئون المالية والتجارية'', hearing_note=''وكيل نيابة/ أسامة الطنطاوي''');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'استئناف القاهرة \n  \n 62 تجاري', 2, 'SPLIT', 'استئناف القاهرة', 'Split: court=''استئناف القاهرة'', circuit=''62 تجاري''');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'استئناف شمال القاهرة \n  \n 87 تعويضات', 2, 'SPLIT', 'استئناف شمال القاهرة', 'Split: court=''استئناف شمال القاهرة'', circuit=''87 تعويضات''');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'استئناف عالي طنطا \n مأمورية شبين الكوم', 2, 'SPLIT', 'استئناف عالي طنطا', 'Split: court=''استئناف عالي طنطا'', circuit=''مأمورية شبين الكوم''');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'الإدارية العليا \n  \n 1 موضوعي', 2, 'SPLIT', 'الإدارية العليا', 'Split: court=''الإدارية العليا'', circuit=''1 موضوعي''');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'القاهرة الجديدة \n  \n 14 تعويضات', 2, 'SPLIT', 'القاهرة الجديدة', 'Split: court=''القاهرة الجديدة'', circuit=''14 تعويضات''');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'القضاء الإداري \n  \n 7 مفوضي استثمار', 2, 'SPLIT', 'القضاء الإداري', 'Split: court=''القضاء الإداري'', circuit=''7 مفوضي استثمار''');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'جنوب الجيزة \n  \n 12 مدني', 2, 'SPLIT', 'جنوب الجيزة', 'Split: court=''جنوب الجيزة'', circuit=''12 مدني''');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'شمال القاهرة7', 2, 'SPLIT', 'شمال القاهرة', 'Split: court=''شمال القاهرة'', circuit=''7''');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'استئناف الزقازيق \n  \n 19 استئناف', 1, 'SPLIT', 'استئناف الزقازيق', 'Split: court=''استئناف الزقازيق'', circuit=''19 استئناف''');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'استئناف القاهرة \n  \n 50 تجاري', 1, 'SPLIT', 'استئناف القاهرة', 'Split: court=''استئناف القاهرة'', circuit=''50 تجاري''');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'استئناف القاهرة مأمورية استئناف الجيزة \n  \n 118 تعويضات', 1, 'SPLIT', 'استئناف القاهرة مأمورية استئناف الجيزة', 'Split: court=''استئناف القاهرة مأمورية استئناف الجيزة'', circuit=''118 تعويضات''');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'استئناف عالي القاهرة \n  \n 4 تعويضات', 1, 'SPLIT', 'استئناف عالي القاهرة', 'Split: court=''استئناف عالي القاهرة'', circuit=''4 تعويضات''');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'الإدارية العليا \n  \n 1 طعون عليا', 1, 'SPLIT', 'الإدارية العليا', 'Split: court=''الإدارية العليا'', circuit=''1 طعون عليا''');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'الإدارية العليا \n  \n 2 فحص', 1, 'SPLIT', 'الإدارية العليا', 'Split: court=''الإدارية العليا'', circuit=''2 فحص''');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'الجيزة الابتدائية \n  \n 4 مدني حكومة', 1, 'SPLIT', 'الجيزة الابتدائية', 'Split: court=''الجيزة الابتدائية'', circuit=''4 مدني حكومة''');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'القاهرة الاقتصادية \n  \n 2 اقتصادي', 1, 'SPLIT', 'القاهرة الاقتصادية', 'Split: court=''القاهرة الاقتصادية'', circuit=''2 اقتصادي''');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'القاهرة الاقتصادية \n  \n 4 استئناف', 1, 'SPLIT', 'القاهرة الاقتصادية', 'Split: court=''القاهرة الاقتصادية'', circuit=''4 استئناف''');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'القضاء الإداري \n  \n 8 عقود', 1, 'SPLIT', 'القضاء الإداري', 'Split: court=''القضاء الإداري'', circuit=''8 عقود''');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'القضاء الإداري \n 3 أفراد مفوضين', 1, 'SPLIT', 'القضاء الإداري', 'Split: court=''القضاء الإداري'', circuit=''3 أفراد مفوضين''');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'النقض \n  \n جنائي', 1, 'SPLIT', 'النقض', 'Split: court=''النقض'', circuit=''جنائي''');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'النقض \n  \n مدني', 1, 'SPLIT', 'النقض', 'Split: court=''النقض'', circuit=''مدني''');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'جنوب الجيزة  \n  \n 7 مدني كلي', 1, 'SPLIT', 'جنوب الجيزة', 'Split: court=''جنوب الجيزة'', circuit=''7 مدني كلي''');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'جنوب الجيزة  \n  \n 9 مدني كلي', 1, 'SPLIT', 'جنوب الجيزة', 'Split: court=''جنوب الجيزة'', circuit=''9 مدني كلي''');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'جنوب الجيزة \n  \n 13 تعويضات', 1, 'SPLIT', 'جنوب الجيزة', 'Split: court=''جنوب الجيزة'', circuit=''13 تعويضات''');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'جنوب الجيزة \n  \n 6 مدني', 1, 'SPLIT', 'جنوب الجيزة', 'Split: court=''جنوب الجيزة'', circuit=''6 مدني''');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'جنوب القاهرة \n  \n 16 عمال', 1, 'SPLIT', 'جنوب القاهرة', 'Split: court=''جنوب القاهرة'', circuit=''16 عمال''');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'شمال القاهرة \n  \n 45 مدني', 1, 'SPLIT', 'شمال القاهرة', 'Split: court=''شمال القاهرة'', circuit=''45 مدني''');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'محكمة استئناف اسرة التجمع 21826/142 ق', 1, 'SPLIT', 'محكمة استئناف اسرة التجمع', 'Split: court=''محكمة استئناف اسرة التجمع'', case_number=''21826/142 ق''');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'مكتب خبراء وزارة العدل بجنوب الجيزة - (مروة السيد)', 1, 'SPLIT', 'مكتب خبراء وزارة العدل بجنوب الجيزة', 'Split: court=''مكتب خبراء وزارة العدل بجنوب الجيزة'', hearing_note=''مروة السيد''');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'هيئة الاستثمار  \n  \n لجان فض المنازعات', 1, 'SPLIT', 'الهيئة العامة للاستثمار والمناطق الحرة', 'Split: court=''هيئة الاستثمار'', circuit=''لجان فض المنازعات''');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'نقابة الأطباء', 67, 'matter_destination', 'نقابة الأطباء', 'Not a court — a venue or destination. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'مقر شركة أدخنة النخلة بشبين الكوم', 2, 'matter_destination', 'مقر شركة أدخنة النخلة بشبين الكوم', 'Not a court — a venue or destination. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'نادي المقطم الرياضي', 2, 'matter_destination', 'نادي المقطم الرياضي', 'Not a court — a venue or destination. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', '/', 1, NULL, NULL, 'Not a value. Discard; the original stays in legacy_court_raw.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', '26', 1, NULL, NULL, 'Not a value. Discard; the original stays in legacy_court_raw.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'كايرو فيستيفال سيتي', 1, 'matter_destination', 'كايرو فيستيفال سيتي', 'Not a court — a venue or destination. Confirmed by the firm.');
INSERT INTO migration_crosswalk (source_field, source_value, rows_affected, target_field, target_value, reviewer_note) VALUES ('court', 'مكتب بريد المعادي', 1, 'matter_destination', 'مكتب بريد المعادي', 'Not a court — a venue or destination. Confirmed by the firm.');

-- ==========================================================================
--  THE SEVEN "WRONG" VALUES — the firm's ruling, 24 August 2026
--
--  Source: sql/court-wrong-destinations.sql.
--
--  Five are real places where something happened; they are simply not courts,
--  and matter_destination already holds exactly this kind of value. Four are
--  added to that list, taking it 27 -> 31. Two are discarded: `/` and `26`
--  are not values. A discard is not a deletion — the row still loads, it
--  simply has no court, and legacy_court_raw keeps the original text (D10).
-- ==========================================================================

INSERT INTO "lookup_matter_destination" (label_ar, sort_order, updated_at) VALUES ('مقر شركة أدخنة النخلة بشبين الكوم', 280, now());
INSERT INTO "lookup_matter_destination" (label_ar, sort_order, updated_at) VALUES ('نادي المقطم الرياضي',               290, now());
INSERT INTO "lookup_matter_destination" (label_ar, sort_order, updated_at) VALUES ('مكتب بريد المعادي',                 300, now());
INSERT INTO "lookup_matter_destination" (label_ar, sort_order, updated_at) VALUES ('كايرو فيستيفال سيتي',               310, now());

-- ==========================================================================
--  POSTCONDITIONS
--
--  308 courts and 94 crosswalk rules, from all 401 distinct court names in
--  الدعاوى.matterCourt, الجلسات.المحكمة and admin work table.المحكمة, reviewed
--  by the firm: 307 KEEP, 52 MERGE, 35 SPLIT, 7 WRONG.
--
--  **308, NOT THE 309 THE SOURCE FILE STATES.** The 309th was
--  هيئة الاستثمار, which is a MERGE SOURCE — a spelling of
--  الهيئة العامة للاستثمار والمناطق الحرة — and had been taken into the list
--  verbatim from a SPLIT's court part. The firm's review was consistent; the
--  first version of the generator was not. Counted, reported, and the counted
--  number used. The fifth time in this project that a stated count was wrong
--  while the list it described was right.
--
--  WHY NO NORMALISER COULD HAVE DONE THIS REVIEW — decision D22.
--  Ten spellings of the Investment Authority collapse into one court; they
--  differ by the definite article, by hamza, AND BY BRANCH LOCATION
--  (في صلاح سالم against بمدينة نصر). In the other direction the firm kept
--  القضاء الإداري, بالعباسية and بالإسكندرية apart: same name, different
--  buildings. A tool cannot tell those two cases apart, because the
--  difference is not in the text. **Both directions are asserted below** —
--  asserting only the fold would not notice an over-merge.
--
--  FOUR RULES CARRIED INTO STAGE 2 — full text in the source file:
--    1. A SPLIT row writes to MORE THAN ONE column. Never discard the
--       remainder.
--    2. Three raw values carry an INDIVIDUAL'S NAME, not a circuit — two
--       court experts and a prosecutor. They go to الجلسات.ملاحظات, the
--       HEARING note, not the matter note: the name belongs to the hearing it
--       was recorded against.
--    3. الجيزة الابتدائية / (السودان) — 5 rows where (السودان) is not a
--       circuit but is recorded as one. Loads as circuit text; flag at Gate 3.
--    4. A court value in neither the crosswalk nor lookup_court is a
--       QUARANTINE case. Never guess.
-- ==========================================================================

DO $COURT$
DECLARE
    n       integer;
    missing text;
BEGIN
    SELECT count(*) INTO n FROM "lookup_court";
    IF n <> 308 THEN
        RAISE EXCEPTION 'lookup_court: % rows, expected 308', n;
    END IF;

    SELECT count(*) INTO n FROM "migration_crosswalk" WHERE source_field = 'court';
    IF n <> 94 THEN
        RAISE EXCEPTION 'court crosswalk rules: %, expected 94', n;
    END IF;

    -- 52 MERGE + 35 SPLIT + 7 WRONG = 94. Each arm asserted, not just the sum.
    SELECT count(*) INTO n FROM "migration_crosswalk"
     WHERE source_field = 'court' AND target_field = 'court';
    IF n <> 52 THEN RAISE EXCEPTION 'MERGE rules: %, expected 52', n; END IF;

    SELECT count(*) INTO n FROM "migration_crosswalk"
     WHERE source_field = 'court' AND target_field = 'SPLIT';
    IF n <> 35 THEN RAISE EXCEPTION 'SPLIT rules: %, expected 35', n; END IF;

    SELECT count(*) INTO n FROM "migration_crosswalk"
     WHERE source_field = 'court'
       AND (target_field = 'matter_destination' OR target_field IS NULL);
    IF n <> 7 THEN RAISE EXCEPTION 'WRONG rules: %, expected 7', n; END IF;

    -- ----------------------------------------------------------------------
    --  NO CHAINS. THE ASSERTION THAT CAUGHT THE GENERATOR BUG.
    --
    --  A court that is also a crosswalk source means value -> court ->
    --  something else. Asserted regardless of how the label reached the list
    --  — a KEEP, a merge target, or a split's court part.
    -- ----------------------------------------------------------------------
    SELECT string_agg(c.label_ar, ', ') INTO missing
      FROM "lookup_court" c
      JOIN "migration_crosswalk" cw
        ON cw.source_value = c.label_ar AND cw.source_field = 'court';
    IF missing IS NOT NULL THEN
        RAISE EXCEPTION 'these are both a court and a crosswalk source, which is a two-step chain: %', missing;
    END IF;

    -- The dropped spelling must be gone from the list AND still resolve.
    SELECT count(*) INTO n FROM "lookup_court" WHERE label_ar = 'هيئة الاستثمار';
    IF n <> 0 THEN
        RAISE EXCEPTION 'هيئة الاستثمار is in the court list — it is a spelling of الهيئة العامة للاستثمار والمناطق الحرة, not a court';
    END IF;

    SELECT count(*) INTO n FROM "migration_crosswalk"
     WHERE source_field = 'court' AND source_value = 'هيئة الاستثمار'
       AND target_value = 'الهيئة العامة للاستثمار والمناطق الحرة';
    IF n <> 1 THEN
        RAISE EXCEPTION 'هيئة الاستثمار no longer resolves to the Investment Authority';
    END IF;

    -- ----------------------------------------------------------------------
    --  Every rule resolves
    -- ----------------------------------------------------------------------
    SELECT string_agg(cw.source_value, ', ') INTO missing
      FROM "migration_crosswalk" cw
     WHERE cw.source_field = 'court' AND cw.target_field = 'court'
       AND NOT EXISTS (SELECT 1 FROM "lookup_court" c WHERE c.label_ar = cw.target_value);
    IF missing IS NOT NULL THEN
        RAISE EXCEPTION 'merge targets that are not courts: %', missing;
    END IF;

    -- Every SPLIT's court part, AFTER resolution through the merge map.
    SELECT string_agg(cw.source_value, ', ') INTO missing
      FROM "migration_crosswalk" cw
     WHERE cw.source_field = 'court' AND cw.target_field = 'SPLIT'
       AND NOT EXISTS (SELECT 1 FROM "lookup_court" c WHERE c.label_ar = cw.target_value);
    IF missing IS NOT NULL THEN
        RAISE EXCEPTION 'SPLIT court parts that are not courts: %', missing;
    END IF;

    -- Every SPLIT must SAY where the remainder goes, or rule 1 has nothing to
    -- act on and the remainder is lost by omission.
    SELECT count(*) INTO n FROM "migration_crosswalk"
     WHERE source_field = 'court' AND target_field = 'SPLIT'
       AND (reviewer_note IS NULL
            OR (reviewer_note NOT LIKE '%circuit=%'
                AND reviewer_note NOT LIKE '%hearing_note=%'
                AND reviewer_note NOT LIKE '%case_number=%'));
    IF n <> 0 THEN
        RAISE EXCEPTION '% SPLIT rules do not say where the remainder goes', n;
    END IF;

    -- ----------------------------------------------------------------------
    --  D22, asserted in BOTH directions
    -- ----------------------------------------------------------------------
    SELECT count(*) INTO n FROM "migration_crosswalk"
     WHERE source_field = 'court'
       AND target_value = 'الهيئة العامة للاستثمار والمناطق الحرة';
    IF n < 9 THEN
        RAISE EXCEPTION 'only % spellings of the Investment Authority fold into one, expected at least 9', n;
    END IF;

    SELECT count(*) INTO n FROM "lookup_court"
     WHERE label_ar = 'الهيئة العامة للاستثمار والمناطق الحرة';
    IF n <> 1 THEN
        RAISE EXCEPTION 'the Investment Authority is not exactly one court';
    END IF;

    -- ...and the three administrative courts stay THREE. Same name, different
    -- buildings. A fuzzy match confident enough to fold the ten above would
    -- certainly have folded these.
    SELECT count(*) INTO n FROM "lookup_court"
     WHERE label_ar IN ('القضاء الإداري',
                        'القضاء الإداري بالعباسية',
                        'القضاء الإداري بالإسكندرية');
    IF n <> 3 THEN
        RAISE EXCEPTION 'the three administrative courts are % of 3 — different buildings, they must stay apart', n;
    END IF;

    -- ----------------------------------------------------------------------
    --  The three individuals, and the (السودان) row
    -- ----------------------------------------------------------------------
    SELECT count(*) INTO n FROM "migration_crosswalk"
     WHERE source_field = 'court' AND reviewer_note LIKE '%hearing_note=%';
    IF n <> 3 THEN
        RAISE EXCEPTION '% rules route a name to the HEARING note, expected 3', n;
    END IF;

    SELECT count(*) INTO n FROM "migration_crosswalk"
     WHERE source_field = 'court' AND target_value = 'الجيزة الابتدائية'
       AND reviewer_note LIKE '%(السودان)%';
    IF n <> 1 THEN
        RAISE EXCEPTION 'the الجيزة الابتدائية / (السودان) rule is missing';
    END IF;

    -- ----------------------------------------------------------------------
    --  The seven WRONG values, per the firm's ruling
    -- ----------------------------------------------------------------------
    SELECT count(*) INTO n FROM "lookup_matter_destination";
    IF n <> 31 THEN
        RAISE EXCEPTION 'lookup_matter_destination: %, expected 31 (27 + 4)', n;
    END IF;

    SELECT count(*) INTO n FROM "migration_crosswalk"
     WHERE source_field = 'court' AND target_field = 'matter_destination';
    IF n <> 5 THEN
        RAISE EXCEPTION 'destination rules: %, expected 5', n;
    END IF;

    SELECT string_agg(cw.source_value, ', ') INTO missing
      FROM "migration_crosswalk" cw
     WHERE cw.source_field = 'court' AND cw.target_field = 'matter_destination'
       AND NOT EXISTS (SELECT 1 FROM "lookup_matter_destination" d
                        WHERE d.label_ar = cw.target_value);
    IF missing IS NOT NULL THEN
        RAISE EXCEPTION 'destination targets that do not exist: %', missing;
    END IF;

    -- The two discards must be discards, and nothing else may be.
    SELECT count(*) INTO n FROM "migration_crosswalk"
     WHERE source_field = 'court' AND target_field IS NULL;
    IF n <> 2 THEN
        RAISE EXCEPTION 'court rules with no target: %, expected 2 (/ and 26)', n;
    END IF;

    SELECT count(*) INTO n FROM "migration_crosswalk"
     WHERE source_field = 'court' AND target_field IS NULL
       AND source_value IN ('/', '26');
    IF n <> 2 THEN
        RAISE EXCEPTION 'the two discards are not / and 26';
    END IF;

    -- Nothing is quarantined any more: the firm ruled on all seven.
    SELECT count(*) INTO n FROM "migration_crosswalk"
     WHERE source_field = 'court' AND target_field = 'quarantine';
    IF n <> 0 THEN
        RAISE EXCEPTION '% court rules are still quarantined', n;
    END IF;

    -- ----------------------------------------------------------------------
    --  Nothing else moved
    -- ----------------------------------------------------------------------
    SELECT count(*) INTO n FROM "migration_crosswalk";
    IF n <> 114 THEN
        RAISE EXCEPTION 'migration_crosswalk: % rows, expected 114 (20 + 94)', n;
    END IF;

    SELECT (SELECT count(*) FROM "lookup_matter_type")
         + (SELECT count(*) FROM "lookup_matter_category")
         + (SELECT count(*) FROM "lookup_degree")
         + (SELECT count(*) FROM "lookup_venue")
         + (SELECT count(*) FROM "lookup_importance")
         + (SELECT count(*) FROM "lookup_party_role")
         + (SELECT count(*) FROM "lookup_hearing_action")
         + (SELECT count(*) FROM "lookup_matter_destination")
         + (SELECT count(*) FROM "lookup_client_branch")
      INTO n;
    IF n <> 134 THEN
        RAISE EXCEPTION 'the nine original lists: % rows, expected 134 (130 + 4 destinations)', n;
    END IF;

    SELECT count(*) INTO n FROM "people";
    IF n <> 135 THEN RAISE EXCEPTION 'people: %, expected 135', n; END IF;

    RAISE NOTICE 'courts: 308 (309 stated, 1 was a merge source), 94 rules, 4 destinations added, 0 chains';
END
$COURT$;
